export enum UserRole {
  USER = 'USER',
  MODERATOR = 'MODERATOR',
  REGIONAL_MODERATOR = 'REGIONAL_MODERATOR',
  ADMIN = 'ADMIN',
  SUPER_ADMIN = 'SUPER_ADMIN',
}

export enum GardenType {
  VIRTUAL = 'VIRTUAL',
  REAL = 'REAL',
  HYBRID = 'HYBRID',
}

export enum CropStatus {
  SEED = 'SEED',
  SPROUTING = 'SPROUTING',
  GROWING = 'GROWING',
  MATURE = 'MATURE',
  HARVESTED = 'HARVESTED',
  WILTED = 'WILTED',
  DISEASED = 'DISEASED',
}

export enum TransactionStatus {
  PENDING = 'PENDING',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  DISPUTED = 'DISPUTED',
}

export enum SensorType {
  SOIL_MOISTURE = 'SOIL_MOISTURE',
  HUMIDITY = 'HUMIDITY',
  PH = 'PH',
  TEMPERATURE = 'TEMPERATURE',
  LIGHT = 'LIGHT',
}

export enum ListingStatus {
  ACTIVE = 'ACTIVE',
  SOLD = 'SOLD',
  CANCELLED = 'CANCELLED',
  EXPIRED = 'EXPIRED',
}

export enum NotificationType {
  WATERING_REMINDER = 'WATERING_REMINDER',
  WEATHER_ALERT = 'WEATHER_ALERT',
  DISEASE_WARNING = 'DISEASE_WARNING',
  AI_RECOMMENDATION = 'AI_RECOMMENDATION',
  CROP_READY = 'CROP_READY',
  MARKETPLACE = 'MARKETPLACE',
  GOVT_SCHEME = 'GOVT_SCHEME',
  SEASONAL_EVENT = 'SEASONAL_EVENT',
}

export const ERROR_CODES = {
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  INVALID_TOKEN: 'INVALID_TOKEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  INSUFFICIENT_CREDITS: 'INSUFFICIENT_CREDITS',
  DEVICE_NOT_TRUSTED: 'DEVICE_NOT_TRUSTED',
  INVITE_EXPIRED: 'INVITE_EXPIRED',
  INVITE_MAXED: 'INVITE_MAXED',
  QR_EXPIRED: 'QR_EXPIRED',
  QR_ALREADY_USED: 'QR_ALREADY_USED',
  CROP_NOT_READY: 'CROP_NOT_READY',
  WEATHER_API_ERROR: 'WEATHER_API_ERROR',
  AI_SERVICE_ERROR: 'AI_SERVICE_ERROR',
  BLOCKCHAIN_ERROR: 'BLOCKCHAIN_ERROR',
} as const;

export const XP_THRESHOLDS = [
  0, 100, 250, 500, 1000, 2000, 3500, 5500, 8000, 11000,
  15000, 20000, 26000, 33000, 41000, 50000, 60000, 72000, 85000, 100000,
];

export const GROWTH_INTERVAL_HOURS = 6;
export const HYDRATION_DECAY_RATE = 5;
export const NUTRIENT_DECAY_RATE = 3;
export const HEALTH_DECAY_RATE_DISEASED = 15;

export const REPUTATION_ACTIONS = {
  TRADE_COMPLETE: { score: 10, reason: 'Completed a marketplace trade' },
  GARDEN_STREAK: { score: 5, reason: 'Maintained garden activity streak' },
  QUEST_COMPLETE: { score: 15, reason: 'Completed a quest' },
  HELPFUL_REPORT: { score: 3, reason: 'Submitted a helpful moderation report' },
  MODERATION_ACTION: { score: 20, reason: 'Performed a moderation action' },
  INVITE_USED: { score: 5, reason: 'Invite was redeemed' },
};

export const ITEM_RARITIES = {
  COMMON: 'COMMON',
  UNCOMMON: 'UNCOMMON',
  RARE: 'RARE',
  EPIC: 'EPIC',
  LEGENDARY: 'LEGENDARY',
};

export const ITEM_TYPES = {
  SEED: 'SEED',
  FERTILIZER: 'FERTILIZER',
  TOOL: 'TOOL',
  COSMETIC: 'COSMETIC',
};

export const MARKETPLACE_CATEGORIES = {
  SEEDS: 'SEEDS',
  FERTILIZER: 'FERTILIZER',
  TOOLS: 'TOOLS',
  SERVICES: 'SERVICES',
  HARVEST: 'HARVEST',
};

export const GROUP_TYPES = {
  REGIONAL: 'REGIONAL',
  COMMUNITY: 'COMMUNITY',
  TRADE: 'TRADE',
  COOPERATIVE: 'COOPERATIVE',
};

export const GROUP_ROLES = {
  MEMBER: 'MEMBER',
  MODERATOR: 'MODERATOR',
  ADMIN: 'ADMIN',
};

export const QR_TYPES = {
  INVITE: 'INVITE',
  MARKETPLACE: 'MARKETPLACE',
  DEVICE_PAIRING: 'DEVICE_PAIRING',
  GARDEN_SHARE: 'GARDEN_SHARE',
  EVENT: 'EVENT',
};

export const MODERATION_TYPES = {
  ABUSE: 'ABUSE',
  SPAM: 'SPAM',
  HARASSMENT: 'HARASSMENT',
  SCAM: 'SCAM',
  FRAUD: 'FRAUD',
  INAPPROPRIATE: 'INAPPROPRIATE',
};

export const MODERATION_STATUS = {
  PENDING: 'PENDING',
  INVESTIGATING: 'INVESTIGATING',
  RESOLVED: 'RESOLVED',
  DISMISSED: 'DISMISSED',
};

export const WEATHER_CONDITIONS = {
  CLEAR: 'CLEAR',
  CLOUDY: 'CLOUDY',
  RAIN: 'RAIN',
  STORM: 'STORM',
  DROUGHT: 'DROUGHT',
  HEATWAVE: 'HEATWAVE',
};

export const ADVISORY_TYPES = {
  SCHEME: 'SCHEME',
  ADVISORY: 'ADVISORY',
  ALERT: 'ALERT',
  SUBSIDY: 'SUBSIDY',
  NEWS: 'NEWS',
};

export const DEVICE_TYPES = {
  ESP32: 'ESP32',
  RASPBERRY_PI: 'RASPBERRY_PI',
  CUSTOM: 'CUSTOM',
};

export const BLOCKCHAIN_CONTRACT_TYPES = {
  TOKEN: 'TOKEN',
  MARKETPLACE: 'MARKETPLACE',
  REPUTATION: 'REPUTATION',
  REWARD: 'REWARD',
};

export const BLOCKCHAIN_ACTIONS = {
  TRANSFER: 'TRANSFER',
  MINT: 'MINT',
  BURN: 'BURN',
  LIST: 'LIST',
  PURCHASE: 'PURCHASE',
};
