export const extraPlants = [
  // ═══════════════════════════════════════════════════════════════════════════
  // FRUIT TREES (30 species)
  // ═══════════════════════════════════════════════════════════════════════════
  { commonName: 'Mango', scientificName: 'Mangifera indica', family: 'Anacardiaceae', growingDays: 150, difficulty: 'MEDIUM', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: true, medicinal: false, toxic: false, tags: ['fruit', 'tropical', 'indian', 'tree'], minTemp: 15, maxTemp: 40, description: 'The king of fruits. Sweet, juicy drupe widely cultivated in tropical regions. Requires warm temperatures and well-drained soil.', baseYield: 8, tokensPerHarvest: 35 },
  { commonName: 'Apple', scientificName: 'Malus domestica', family: 'Rosaceae', growingDays: 180, difficulty: 'HARD', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'fall'], edible: true, medicinal: false, toxic: false, tags: ['fruit', 'temperate', 'tree'], minTemp: -10, maxTemp: 30, description: 'Popular temperate fruit tree requiring cold winters for dormancy. Many cultivars available for different climates.', baseYield: 7, tokensPerHarvest: 25 },
  { commonName: 'Peach', scientificName: 'Prunus persica', family: 'Rosaceae', growingDays: 150, difficulty: 'MEDIUM', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: true, medicinal: false, toxic: false, tags: ['fruit', 'temperate', 'stone-fruit', 'tree'], minTemp: -5, maxTemp: 35, description: 'Sweet stone fruit with fuzzy skin. Needs chilling hours in winter for proper fruiting.', baseYield: 7, tokensPerHarvest: 25 },
  { commonName: 'Pear', scientificName: 'Pyrus communis', family: 'Rosaceae', growingDays: 170, difficulty: 'MEDIUM', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'fall'], edible: true, medicinal: false, toxic: false, tags: ['fruit', 'temperate', 'tree'], minTemp: -15, maxTemp: 30, description: 'Elegant temperate fruit with buttery texture. Cold-hardy and adaptable to various soil types.', baseYield: 7, tokensPerHarvest: 25 },
  { commonName: 'Cherry', scientificName: 'Prunus avium', family: 'Rosaceae', growingDays: 140, difficulty: 'HARD', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: true, medicinal: false, toxic: false, tags: ['fruit', 'temperate', 'stone-fruit', 'tree'], minTemp: -10, maxTemp: 30, description: 'Sweet or sour stone fruit. Requires significant winter chill hours and well-drained soil.', baseYield: 5, tokensPerHarvest: 30 },
  { commonName: 'Plum', scientificName: 'Prunus domestica', family: 'Rosaceae', growingDays: 160, difficulty: 'MEDIUM', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: true, medicinal: false, toxic: false, tags: ['fruit', 'temperate', 'stone-fruit', 'tree'], minTemp: -10, maxTemp: 35, description: 'Versatile stone fruit used fresh, dried (prunes), or in preserves. Adaptable to many climates.', baseYield: 6, tokensPerHarvest: 20 },
  { commonName: 'Apricot', scientificName: 'Prunus armeniaca', family: 'Rosaceae', growingDays: 140, difficulty: 'MEDIUM', waterNeeds: 'LOW', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: true, medicinal: false, toxic: false, tags: ['fruit', 'temperate', 'stone-fruit', 'tree'], minTemp: -10, maxTemp: 35, description: 'Small, sweet stone fruit rich in vitamins. Drought-tolerant once established.', baseYield: 6, tokensPerHarvest: 20 },
  { commonName: 'Fig', scientificName: 'Ficus carica', family: 'Moraceae', growingDays: 120, difficulty: 'EASY', waterNeeds: 'LOW', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer', 'fall'], edible: true, medicinal: false, toxic: false, tags: ['fruit', 'mediterranean', 'tree'], minTemp: -5, maxTemp: 40, description: 'Sweet, soft fruit with a long history of cultivation. Drought-tolerant and easy to grow.', baseYield: 6, tokensPerHarvest: 20 },
  { commonName: 'Pomegranate', scientificName: 'Punica granatum', family: 'Lythraceae', growingDays: 150, difficulty: 'EASY', waterNeeds: 'LOW', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer', 'fall'], edible: true, medicinal: true, toxic: false, tags: ['fruit', 'mediterranean', 'indian', 'tree'], minTemp: -5, maxTemp: 40, description: 'Jewel-like arils packed with antioxidants. Very drought-tolerant and heat-resistant.', baseYield: 5, tokensPerHarvest: 25 },
  { commonName: 'Orange', scientificName: 'Citrus sinensis', family: 'Rutaceae', growingDays: 200, difficulty: 'MEDIUM', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['winter', 'spring'], edible: true, medicinal: false, toxic: false, tags: ['fruit', 'citrus', 'tree'], minTemp: 5, maxTemp: 40, description: 'Sweet citrus fruit rich in vitamin C. Evergreen tree that produces fragrant blossoms.', baseYield: 7, tokensPerHarvest: 25 },
  { commonName: 'Lime', scientificName: 'Citrus aurantiifolia', family: 'Rutaceae', growingDays: 180, difficulty: 'MEDIUM', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: true, medicinal: false, toxic: false, tags: ['fruit', 'citrus', 'tropical', 'tree'], minTemp: 10, maxTemp: 40, description: 'Small, tart citrus fruit essential in cooking and beverages. Prefers tropical and subtropical climates.', baseYield: 6, tokensPerHarvest: 20 },
  { commonName: 'Grapefruit', scientificName: 'Citrus paradisi', family: 'Rutaceae', growingDays: 210, difficulty: 'MEDIUM', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['winter', 'spring'], edible: true, medicinal: false, toxic: false, tags: ['fruit', 'citrus', 'tree'], minTemp: 5, maxTemp: 38, description: 'Large citrus fruit with a tangy-sweet flavor. Evergreen tree requiring warm conditions.', baseYield: 7, tokensPerHarvest: 25 },
  { commonName: 'Tangerine', scientificName: 'Citrus reticulata', family: 'Rutaceae', growingDays: 190, difficulty: 'EASY', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['winter', 'spring'], edible: true, medicinal: false, toxic: false, tags: ['fruit', 'citrus', 'tree'], minTemp: 5, maxTemp: 38, description: 'Small, easy-to-peel citrus fruit. Sweeter and less acidic than oranges.', baseYield: 6, tokensPerHarvest: 20 },
  { commonName: 'Grape', scientificName: 'Vitis vinifera', family: 'Vitaceae', growingDays: 140, difficulty: 'MEDIUM', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['summer', 'fall'], edible: true, medicinal: false, toxic: false, tags: ['fruit', 'vine', 'tree'], minTemp: -10, maxTemp: 40, description: 'Climbing vine producing clusters of edible berries. Used for eating, wine, and raisins.', baseYield: 6, tokensPerHarvest: 20 },
  { commonName: 'Guava', scientificName: 'Psidium guajava', family: 'Myrtaceae', growingDays: 120, difficulty: 'EASY', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer', 'fall'], edible: true, medicinal: true, toxic: false, tags: ['fruit', 'tropical', 'indian', 'tree'], minTemp: 10, maxTemp: 40, description: 'Tropical fruit with a distinctive fragrance. Extremely high in vitamin C.', baseYield: 7, tokensPerHarvest: 20 },
  { commonName: 'Papaya', scientificName: 'Carica papaya', family: 'Caricaceae', growingDays: 100, difficulty: 'EASY', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: true, medicinal: true, toxic: false, tags: ['fruit', 'tropical', 'tree'], minTemp: 15, maxTemp: 40, description: 'Fast-growing tropical fruit with sweet orange flesh. Contains papain enzyme for digestion.', baseYield: 7, tokensPerHarvest: 20 },
  { commonName: 'Avocado', scientificName: 'Persea americana', family: 'Lauraceae', growingDays: 180, difficulty: 'HARD', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: true, medicinal: false, toxic: false, tags: ['fruit', 'tropical', 'tree'], minTemp: 5, maxTemp: 35, description: 'Creamy fruit rich in healthy fats. Requires well-drained soil and consistent moisture.', baseYield: 5, tokensPerHarvest: 35 },
  { commonName: 'Banana', scientificName: 'Musa acuminata', family: 'Musaceae', growingDays: 120, difficulty: 'MEDIUM', waterNeeds: 'HIGH', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: true, medicinal: false, toxic: false, tags: ['fruit', 'tropical', 'tree'], minTemp: 15, maxTemp: 35, description: 'Large herbaceous plant producing sweet fruit. Needs rich soil, plenty of water, and warm temperatures.', baseYield: 8, tokensPerHarvest: 20 },
  { commonName: 'Coconut', scientificName: 'Cocos nucifera', family: 'Arecaceae', growingDays: 365, difficulty: 'HARD', waterNeeds: 'HIGH', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer', 'fall', 'winter'], edible: true, medicinal: false, toxic: false, tags: ['fruit', 'tropical', 'tree'], minTemp: 18, maxTemp: 40, description: 'Iconic tropical palm producing large drupes. Requires coastal or tropical conditions with high humidity.', baseYield: 6, tokensPerHarvest: 30 },
  { commonName: 'Lychee', scientificName: 'Litchi chinensis', family: 'Sapindaceae', growingDays: 150, difficulty: 'HARD', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: true, medicinal: false, toxic: false, tags: ['fruit', 'tropical', 'tree'], minTemp: 10, maxTemp: 38, description: 'Sweet, fragrant tropical fruit with translucent flesh. Needs subtropical climate with cool winters.', baseYield: 5, tokensPerHarvest: 30 },
  { commonName: 'Longan', scientificName: 'Dimocarpus longan', family: 'Sapindaceae', growingDays: 160, difficulty: 'HARD', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['summer'], edible: true, medicinal: true, toxic: false, tags: ['fruit', 'tropical', 'tree'], minTemp: 10, maxTemp: 38, description: 'Related to lychee with sweet, musky flavor. Smaller fruit with smoother shell.', baseYield: 5, tokensPerHarvest: 30 },
  { commonName: 'Passion Fruit', scientificName: 'Passiflora edulis', family: 'Passifloraceae', growingDays: 120, difficulty: 'MEDIUM', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer', 'fall'], edible: true, medicinal: false, toxic: false, tags: ['fruit', 'tropical', 'vine'], minTemp: 10, maxTemp: 35, description: 'Aromatic tropical fruit with juicy, seed-filled pulp. Vigorous climbing vine.', baseYield: 5, tokensPerHarvest: 25 },
  { commonName: 'Dragonfruit', scientificName: 'Hylocereus undatus', family: 'Cactaceae', growingDays: 120, difficulty: 'MEDIUM', waterNeeds: 'LOW', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: true, medicinal: false, toxic: false, tags: ['fruit', 'tropical', 'cactus'], minTemp: 10, maxTemp: 40, description: 'Exotic fruit from a climbing cactus. Vibrant pink skin with speckled white or red flesh.', baseYield: 4, tokensPerHarvest: 35 },
  { commonName: 'Persimmon', scientificName: 'Diospyros kaki', family: 'Ebenaceae', growingDays: 160, difficulty: 'MEDIUM', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['fall', 'winter'], edible: true, medicinal: false, toxic: false, tags: ['fruit', 'temperate', 'tree'], minTemp: -10, maxTemp: 35, description: 'Bright orange autumn fruit that sweetens after frost. Deciduous tree with striking fall foliage.', baseYield: 6, tokensPerHarvest: 25 },
  { commonName: 'Mulberry', scientificName: 'Morus alba', family: 'Moraceae', growingDays: 100, difficulty: 'EASY', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: true, medicinal: false, toxic: false, tags: ['fruit', 'tree'], minTemp: -15, maxTemp: 38, description: 'Sweet, dark berries produced on fast-growing trees. Very cold-hardy and adaptable.', baseYield: 6, tokensPerHarvest: 15 },
  { commonName: 'Olive', scientificName: 'Olea europaea', family: 'Oleaceae', growingDays: 180, difficulty: 'MEDIUM', waterNeeds: 'LOW', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer', 'fall'], edible: true, medicinal: true, toxic: false, tags: ['fruit', 'mediterranean', 'oil', 'tree'], minTemp: -5, maxTemp: 40, description: 'Ancient Mediterranean tree producing oil-rich fruits. Extremely drought-tolerant.', baseYield: 6, tokensPerHarvest: 25 },
  { commonName: 'Kiwi', scientificName: 'Actinidia deliciosa', family: 'Actinidiaceae', growingDays: 150, difficulty: 'HARD', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['fall'], edible: true, medicinal: false, toxic: false, tags: ['fruit', 'temperate', 'vine'], minTemp: -10, maxTemp: 30, description: 'Brown, fuzzy fruit with bright green flesh. Vigorous vine requiring cross-pollination.', baseYield: 5, tokensPerHarvest: 30 },
  { commonName: 'Sapodilla', scientificName: 'Manilkara zapota', family: 'Sapotaceae', growingDays: 200, difficulty: 'HARD', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: true, medicinal: false, toxic: false, tags: ['fruit', 'tropical', 'tree'], minTemp: 12, maxTemp: 38, description: 'Sweet, grainy-textured tropical fruit. Slow-growing evergreen tree native to Central America.', baseYield: 5, tokensPerHarvest: 25 },
  { commonName: 'Jackfruit', scientificName: 'Artocarpus heterophyllus', family: 'Moraceae', growingDays: 180, difficulty: 'MEDIUM', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: true, medicinal: false, toxic: false, tags: ['fruit', 'tropical', 'indian', 'tree'], minTemp: 12, maxTemp: 38, description: 'Largest tree-borne fruit in the world. Sweet when ripe, savory when unripe.', baseYield: 8, tokensPerHarvest: 30 },
  { commonName: 'Starfruit', scientificName: 'Averrhoa carambola', family: 'Oxalidaceae', growingDays: 150, difficulty: 'MEDIUM', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer', 'fall'], edible: true, medicinal: false, toxic: false, tags: ['fruit', 'tropical', 'tree'], minTemp: 12, maxTemp: 38, description: 'Star-shaped yellow fruit with a sweet-tart flavor. Best eaten fresh or in salads.', baseYield: 5, tokensPerHarvest: 25 },

  // ═══════════════════════════════════════════════════════════════════════════
  // FLOWERING ORNAMENTALS (25 species)
  // ═══════════════════════════════════════════════════════════════════════════
  { commonName: 'Rose', scientificName: 'Rosa indica', family: 'Rosaceae', growingDays: 90, difficulty: 'MEDIUM', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer', 'fall'], edible: false, medicinal: true, toxic: false, tags: ['flower', 'ornamental', 'fragrant'], minTemp: -10, maxTemp: 35, description: 'Classic flowering shrub with thorny stems. Many varieties in a wide range of colors and fragrances.', baseYield: 3, tokensPerHarvest: 15 },
  { commonName: 'Jasmine', scientificName: 'Jasminum sambac', family: 'Oleaceae', growingDays: 80, difficulty: 'EASY', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer', 'fall'], edible: false, medicinal: true, toxic: false, tags: ['flower', 'ornamental', 'fragrant', 'indian'], minTemp: 10, maxTemp: 38, description: 'Intensely fragrant white flowers. Climbing or sprawling shrub used in garlands and perfumes.', baseYield: 3, tokensPerHarvest: 15 },
  { commonName: 'Marigold', scientificName: 'Tagetes erecta', family: 'Asteraceae', growingDays: 50, difficulty: 'EASY', waterNeeds: 'LOW', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer', 'fall'], edible: false, medicinal: false, toxic: false, tags: ['flower', 'ornamental', 'indian'], minTemp: 10, maxTemp: 38, description: 'Bright orange and yellow flowers. Easy to grow, pest-repellent, and sacred in Indian rituals.', baseYield: 4, tokensPerHarvest: 10 },
  { commonName: 'Lavender', scientificName: 'Lavandula angustifolia', family: 'Lamiaceae', growingDays: 90, difficulty: 'EASY', waterNeeds: 'LOW', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: false, medicinal: true, toxic: false, tags: ['flower', 'ornamental', 'fragrant', 'herb'], minTemp: -10, maxTemp: 35, description: 'Aromatic purple flowering herb. Drought-tolerant, loved by pollinators, used in aromatherapy.', baseYield: 3, tokensPerHarvest: 15 },
  { commonName: 'Hibiscus', scientificName: 'Hibiscus rosa-sinensis', family: 'Malvaceae', growingDays: 100, difficulty: 'EASY', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer', 'fall'], edible: true, medicinal: true, toxic: false, tags: ['flower', 'ornamental', 'tropical'], minTemp: 10, maxTemp: 38, description: 'Large, showy tropical flowers in many colors. Used in teas, hair care, and traditional medicine.', baseYield: 4, tokensPerHarvest: 12 },
  { commonName: 'Lotus', scientificName: 'Nelumbo nucifera', family: 'Nelumbonaceae', growingDays: 120, difficulty: 'HARD', waterNeeds: 'HIGH', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: true, medicinal: true, toxic: false, tags: ['flower', 'ornamental', 'aquatic', 'sacred'], minTemp: 15, maxTemp: 38, description: 'Sacred aquatic flower rising above water on long stalks. Seeds and roots are edible.', baseYield: 3, tokensPerHarvest: 20 },
  { commonName: 'Orchid', scientificName: 'Orchidaceae spp.', family: 'Orchidaceae', growingDays: 150, difficulty: 'HARD', waterNeeds: 'LOW', sunlightNeeds: 'PARTIAL_SHADE', seasons: ['spring', 'summer'], edible: false, medicinal: false, toxic: false, tags: ['flower', 'ornamental', 'exotic'], minTemp: 12, maxTemp: 35, description: 'Exotic flowering plants with intricate blooms. Many species are epiphytic and need specialized care.', baseYield: 2, tokensPerHarvest: 25 },
  { commonName: 'Dahlia', scientificName: 'Dahlia pinnata', family: 'Asteraceae', growingDays: 100, difficulty: 'MEDIUM', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['summer', 'fall'], edible: false, medicinal: false, toxic: false, tags: ['flower', 'ornamental'], minTemp: 5, maxTemp: 30, description: 'Showy, multi-petaled flowers in vibrant colors. Tubers must be dug up in cold climates.', baseYield: 3, tokensPerHarvest: 15 },
  { commonName: 'Lily', scientificName: 'Lilium asiatic', family: 'Liliaceae', growingDays: 90, difficulty: 'MEDIUM', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: false, medicinal: false, toxic: true, tags: ['flower', 'ornamental', 'bulb'], minTemp: -15, maxTemp: 30, description: 'Elegant trumpet-shaped flowers with strong fragrance. Bulbs, leaves, and pollen are toxic to cats.', baseYield: 3, tokensPerHarvest: 15 },
  { commonName: 'Tulip', scientificName: 'Tulipa gesneriana', family: 'Liliaceae', growingDays: 80, difficulty: 'MEDIUM', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring'], edible: false, medicinal: false, toxic: false, tags: ['flower', 'ornamental', 'bulb'], minTemp: -15, maxTemp: 25, description: 'Iconic spring-blooming bulb flower. Requires cold winter dormancy for vibrant blooms.', baseYield: 3, tokensPerHarvest: 15 },
  { commonName: 'Chrysanthemum', scientificName: 'Chrysanthemum morifolium', family: 'Asteraceae', growingDays: 90, difficulty: 'EASY', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['fall'], edible: false, medicinal: true, toxic: false, tags: ['flower', 'ornamental'], minTemp: 0, maxTemp: 30, description: 'Classic fall-blooming flower in many forms. Used in teas and traditional Chinese medicine.', baseYield: 4, tokensPerHarvest: 12 },
  { commonName: 'Carnation', scientificName: 'Dianthus caryophyllus', family: 'Caryophyllaceae', growingDays: 90, difficulty: 'EASY', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: false, medicinal: false, toxic: false, tags: ['flower', 'ornamental'], minTemp: -5, maxTemp: 30, description: 'Fragrant, ruffled flowers popular in bouquets. Long-lasting cut flowers in many colors.', baseYield: 3, tokensPerHarvest: 12 },
  { commonName: 'Peony', scientificName: 'Paeonia lactiflora', family: 'Paeoniaceae', growingDays: 120, difficulty: 'MEDIUM', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: false, medicinal: true, toxic: false, tags: ['flower', 'ornamental'], minTemp: -20, maxTemp: 30, description: 'Lush, fragrant spring blooms that can live for decades. Deep taproot makes them very hardy.', baseYield: 3, tokensPerHarvest: 18 },
  { commonName: 'Bougainvillea', scientificName: 'Bougainvillea spectabilis', family: 'Nyctaginaceae', growingDays: 120, difficulty: 'EASY', waterNeeds: 'LOW', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer', 'fall'], edible: false, medicinal: false, toxic: false, tags: ['flower', 'ornamental', 'climber', 'tropical'], minTemp: 10, maxTemp: 40, description: 'Vibrant papery bracts in magenta, orange, and purple. Vigorous climbing shrub for warm climates.', baseYield: 4, tokensPerHarvest: 12 },
  { commonName: 'Zinnia', scientificName: 'Zinnia elegans', family: 'Asteraceae', growingDays: 60, difficulty: 'EASY', waterNeeds: 'LOW', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer', 'fall'], edible: false, medicinal: false, toxic: false, tags: ['flower', 'ornamental'], minTemp: 10, maxTemp: 38, description: 'Colorful, easy-to-grow annual. Attracts butterflies and makes excellent cut flowers.', baseYield: 4, tokensPerHarvest: 8 },
  { commonName: 'Petunia', scientificName: 'Petunia hybrida', family: 'Solanaceae', growingDays: 60, difficulty: 'EASY', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: false, medicinal: false, toxic: false, tags: ['flower', 'ornamental'], minTemp: 10, maxTemp: 35, description: 'Trailing or upright annual with trumpet-shaped flowers. Blooms profusely all season.', baseYield: 3, tokensPerHarvest: 8 },
  { commonName: 'Snapdragon', scientificName: 'Antirrhinum majus', family: 'Plantaginaceae', growingDays: 70, difficulty: 'EASY', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'fall'], edible: false, medicinal: false, toxic: false, tags: ['flower', 'ornamental'], minTemp: 5, maxTemp: 30, description: 'Dragon-mouth-shaped flowers on tall spikes. Cool-season annual that reseeds readily.', baseYield: 3, tokensPerHarvest: 8 },
  { commonName: 'Cosmos', scientificName: 'Cosmos bipinnatus', family: 'Asteraceae', growingDays: 55, difficulty: 'EASY', waterNeeds: 'LOW', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer', 'fall'], edible: false, medicinal: false, toxic: false, tags: ['flower', 'ornamental'], minTemp: 10, maxTemp: 38, description: 'Delicate, daisy-like flowers on feathery foliage. Thrives in poor soil with minimal care.', baseYield: 3, tokensPerHarvest: 8 },
  { commonName: 'Chamomile', scientificName: 'Matricaria chamomilla', family: 'Asteraceae', growingDays: 50, difficulty: 'EASY', waterNeeds: 'LOW', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: false, medicinal: true, toxic: false, tags: ['flower', 'ornamental', 'herb', 'medicinal'], minTemp: 5, maxTemp: 30, description: 'Daisy-like flowers with apple-scented foliage. Used for calming teas and companion planting.', baseYield: 3, tokensPerHarvest: 10 },
  { commonName: 'Geranium', scientificName: 'Pelargonium hortorum', family: 'Geraniaceae', growingDays: 70, difficulty: 'EASY', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer', 'fall'], edible: false, medicinal: false, toxic: false, tags: ['flower', 'ornamental'], minTemp: 5, maxTemp: 35, description: 'Clustered blooms in red, pink, and white. Popular container plant with aromatic foliage.', baseYield: 3, tokensPerHarvest: 10 },
  { commonName: 'Impatiens', scientificName: 'Impatiens walleriana', family: 'Balsaminaceae', growingDays: 55, difficulty: 'EASY', waterNeeds: 'HIGH', sunlightNeeds: 'PARTIAL_SHADE', seasons: ['spring', 'summer'], edible: false, medicinal: false, toxic: false, tags: ['flower', 'ornamental', 'shade'], minTemp: 10, maxTemp: 32, description: 'Bright, shade-tolerant annual. One of the best flowers for shady garden spots.', baseYield: 3, tokensPerHarvest: 8 },
  { commonName: 'Begonia', scientificName: 'Begonia semperflorens', family: 'Begoniaceae', growingDays: 60, difficulty: 'MEDIUM', waterNeeds: 'MODERATE', sunlightNeeds: 'PARTIAL_SHADE', seasons: ['spring', 'summer', 'fall'], edible: false, medicinal: false, toxic: false, tags: ['flower', 'ornamental', 'shade'], minTemp: 12, maxTemp: 30, description: 'Wax begonia with glossy leaves and constant blooms. Excellent for borders and containers.', baseYield: 3, tokensPerHarvest: 10 },
  { commonName: 'Azalea', scientificName: 'Rhododendron simsii', family: 'Ericaceae', growingDays: 120, difficulty: 'HARD', waterNeeds: 'MODERATE', sunlightNeeds: 'PARTIAL_SHADE', seasons: ['spring'], edible: false, medicinal: false, toxic: true, tags: ['flower', 'ornamental', 'shrub'], minTemp: -5, maxTemp: 30, description: 'Spectacular spring-blooming shrub with masses of colorful flowers. Needs acidic, well-drained soil.', baseYield: 3, tokensPerHarvest: 15 },
  { commonName: 'Magnolia', scientificName: 'Magnolia grandiflora', family: 'Magnoliaceae', growingDays: 180, difficulty: 'MEDIUM', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: false, medicinal: false, toxic: false, tags: ['flower', 'ornamental', 'tree'], minTemp: -5, maxTemp: 35, description: 'Large, fragrant white or pink flowers on a majestic evergreen tree. One of the oldest flowering genera.', baseYield: 3, tokensPerHarvest: 15 },

  // ═══════════════════════════════════════════════════════════════════════════
  // HERBS & SPICES (25 species)
  // ═══════════════════════════════════════════════════════════════════════════
  { commonName: 'Ginger', scientificName: 'Zingiber officinale', family: 'Zingiberaceae', growingDays: 100, difficulty: 'MEDIUM', waterNeeds: 'MODERATE', sunlightNeeds: 'PARTIAL_SHADE', seasons: ['spring', 'summer'], edible: true, medicinal: true, toxic: false, tags: ['spice', 'root', 'indian', 'medicinal'], minTemp: 15, maxTemp: 35, description: 'Pungent rhizome used as spice and medicine. Grows well in warm, humid conditions with partial shade.', baseYield: 5, tokensPerHarvest: 20 },
  { commonName: 'Cumin', scientificName: 'Cuminum cyminum', family: 'Apiaceae', growingDays: 90, difficulty: 'MEDIUM', waterNeeds: 'LOW', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: true, medicinal: true, toxic: false, tags: ['spice', 'indian', 'seed'], minTemp: 10, maxTemp: 35, description: 'Aromatic seed spice essential in Indian cooking. Grows best in warm, dry conditions.', baseYield: 4, tokensPerHarvest: 15 },
  { commonName: 'Mustard', scientificName: 'Brassica nigra', family: 'Brassicaceae', growingDays: 60, difficulty: 'EASY', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['winter', 'spring'], edible: true, medicinal: false, toxic: false, tags: ['spice', 'seed', 'oil', 'indian'], minTemp: 5, maxTemp: 30, description: 'Small seeds used as spice and for oil production. Fast-growing cool-season crop.', baseYield: 5, tokensPerHarvest: 12 },
  { commonName: 'Cardamom', scientificName: 'Elettaria cardamomum', family: 'Zingiberaceae', growingDays: 180, difficulty: 'HARD', waterNeeds: 'HIGH', sunlightNeeds: 'PARTIAL_SHADE', seasons: ['spring', 'summer'], edible: true, medicinal: true, toxic: false, tags: ['spice', 'indian', 'medicinal'], minTemp: 18, maxTemp: 35, description: 'Queen of spices. Small green pods with intense aromatic flavor. Needs tropical rainforest conditions.', baseYield: 3, tokensPerHarvest: 40 },
  { commonName: 'Clove', scientificName: 'Syzygium aromaticum', family: 'Myrtaceae', growingDays: 365, difficulty: 'HARD', waterNeeds: 'HIGH', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: true, medicinal: true, toxic: false, tags: ['spice', 'tropical', 'medicinal'], minTemp: 18, maxTemp: 35, description: 'Dried flower buds with intense warm flavor. Evergreen tree native to the Maluku Islands.', baseYield: 3, tokensPerHarvest: 35 },
  { commonName: 'Cinnamon', scientificName: 'Cinnamomum verum', family: 'Lauraceae', growingDays: 365, difficulty: 'HARD', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: true, medicinal: true, toxic: false, tags: ['spice', 'bark', 'tropical', 'medicinal'], minTemp: 18, maxTemp: 35, description: 'Aromatic bark used as spice. Evergreen tree native to Sri Lanka. Inner bark is harvested and dried.', baseYield: 4, tokensPerHarvest: 30 },
  { commonName: 'Black Pepper', scientificName: 'Piper nigrum', family: 'Piperaceae', growingDays: 180, difficulty: 'HARD', waterNeeds: 'HIGH', sunlightNeeds: 'PARTIAL_SHADE', seasons: ['spring', 'summer'], edible: true, medicinal: true, toxic: false, tags: ['spice', 'vine', 'indian', 'medicinal'], minTemp: 18, maxTemp: 35, description: 'King of spices. Climbing vine producing peppercorns. Native to the Malabar Coast of India.', baseYield: 4, tokensPerHarvest: 35 },
  { commonName: 'Bay Leaf', scientificName: 'Laurus nobilis', family: 'Lauraceae', growingDays: 150, difficulty: 'EASY', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: true, medicinal: true, toxic: false, tags: ['herb', 'leaf', 'mediterranean'], minTemp: -5, maxTemp: 35, description: 'Aromatic evergreen leaves used in cooking. Slow-growing tree or large shrub.', baseYield: 4, tokensPerHarvest: 15 },
  { commonName: 'Oregano', scientificName: 'Origanum vulgare', family: 'Lamiaceae', growingDays: 50, difficulty: 'EASY', waterNeeds: 'LOW', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: true, medicinal: true, toxic: false, tags: ['herb', 'mediterranean', 'medicinal'], minTemp: -10, maxTemp: 35, description: 'Aromatic Mediterranean herb essential in Italian and Greek cuisine. Drought-tolerant perennial.', baseYield: 3, tokensPerHarvest: 12 },
  { commonName: 'Thyme', scientificName: 'Thymus vulgaris', family: 'Lamiaceae', growingDays: 45, difficulty: 'EASY', waterNeeds: 'LOW', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: true, medicinal: true, toxic: false, tags: ['herb', 'mediterranean', 'medicinal'], minTemp: -15, maxTemp: 35, description: 'Low-growing aromatic herb with tiny leaves. Excellent ground cover and culinary staple.', baseYield: 3, tokensPerHarvest: 12 },
  { commonName: 'Rosemary', scientificName: 'Salvia rosmarinus', family: 'Lamiaceae', growingDays: 60, difficulty: 'EASY', waterNeeds: 'LOW', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: true, medicinal: true, toxic: false, tags: ['herb', 'mediterranean', 'medicinal'], minTemp: -5, maxTemp: 35, description: 'Woody aromatic herb with needle-like leaves. Excellent for roasts and bread.', baseYield: 3, tokensPerHarvest: 12 },
  { commonName: 'Parsley', scientificName: 'Petroselinum crispum', family: 'Apiaceae', growingDays: 40, difficulty: 'EASY', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'fall'], edible: true, medicinal: true, toxic: false, tags: ['herb', 'leaf', 'medicinal'], minTemp: 5, maxTemp: 30, description: 'Fresh, mild-flavored herb used as garnish and ingredient. Rich in vitamins A, C, and K.', baseYield: 3, tokensPerHarvest: 10 },
  { commonName: 'Dill', scientificName: 'Anethum graveolens', family: 'Apiaceae', growingDays: 40, difficulty: 'EASY', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: true, medicinal: false, toxic: false, tags: ['herb', 'leaf', 'seed'], minTemp: 10, maxTemp: 30, description: 'Feathery herb with distinctive flavor. Leaves and seeds both used in cooking.', baseYield: 3, tokensPerHarvest: 10 },
  { commonName: 'Fennel', scientificName: 'Foeniculum vulgare', family: 'Apiaceae', growingDays: 70, difficulty: 'EASY', waterNeeds: 'LOW', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: true, medicinal: true, toxic: false, tags: ['herb', 'seed', 'medicinal'], minTemp: 5, maxTemp: 35, description: 'Anise-flavored herb with bulb, fronds, and seeds all edible. Attracts beneficial insects.', baseYield: 4, tokensPerHarvest: 12 },
  { commonName: 'Lemongrass', scientificName: 'Cymbopogon citratus', family: 'Poaceae', growingDays: 75, difficulty: 'EASY', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: true, medicinal: true, toxic: false, tags: ['herb', 'tropical', 'indian', 'medicinal'], minTemp: 12, maxTemp: 38, description: 'Citronella-scented grass used in teas, curries, and mosquito repellent. Tropical perennial.', baseYield: 4, tokensPerHarvest: 12 },
  { commonName: 'Sage', scientificName: 'Salvia officinalis', family: 'Lamiaceae', growingDays: 60, difficulty: 'EASY', waterNeeds: 'LOW', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: true, medicinal: true, toxic: false, tags: ['herb', 'mediterranean', 'medicinal'], minTemp: -10, maxTemp: 35, description: 'Fuzzy, aromatic leaves used in stuffing and savory dishes. Medicinal herb for sore throats.', baseYield: 3, tokensPerHarvest: 12 },
  { commonName: 'Curry Leaf', scientificName: 'Murraya koenigii', family: 'Rutaceae', growingDays: 120, difficulty: 'MEDIUM', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: true, medicinal: true, toxic: false, tags: ['herb', 'leaf', 'indian', 'medicinal'], minTemp: 10, maxTemp: 38, description: 'Aromatic leaves essential in South Indian cooking. Small tree with curry-scented foliage.', baseYield: 4, tokensPerHarvest: 15 },
  { commonName: 'Tamarind', scientificName: 'Tamarindus indica', family: 'Fabaceae', growingDays: 200, difficulty: 'MEDIUM', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: true, medicinal: true, toxic: false, tags: ['fruit', 'spice', 'indian', 'tree'], minTemp: 10, maxTemp: 40, description: 'Sour-sweet pulp used as spice and in chutneys. Large deciduous tree native to tropical Africa.', baseYield: 6, tokensPerHarvest: 20 },
  { commonName: 'Saffron', scientificName: 'Crocus sativus', family: 'Iridaceae', growingDays: 120, difficulty: 'HARD', waterNeeds: 'LOW', sunlightNeeds: 'FULL_SUN', seasons: ['fall'], edible: true, medicinal: true, toxic: false, tags: ['spice', 'saffron', 'exotic'], minTemp: -5, maxTemp: 25, description: 'World\'s most expensive spice. Crimson stigmas hand-harvested from autumn crocus flowers.', baseYield: 1, tokensPerHarvest: 50 },
  { commonName: 'Vanilla', scientificName: 'Vanilla planifolia', family: 'Orchidaceae', growingDays: 270, difficulty: 'HARD', waterNeeds: 'HIGH', sunlightNeeds: 'PARTIAL_SHADE', seasons: ['spring', 'summer'], edible: true, medicinal: false, toxic: false, tags: ['spice', 'orchid', 'tropical'], minTemp: 18, maxTemp: 32, description: 'Climbing orchid producing the world\'s most popular flavor. Seed pods take 9 months to mature.', baseYield: 2, tokensPerHarvest: 45 },
  { commonName: 'Nutmeg', scientificName: 'Myristica fragrans', family: 'Myristicaceae', growingDays: 300, difficulty: 'HARD', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: true, medicinal: true, toxic: false, tags: ['spice', 'tropical', 'medicinal'], minTemp: 18, maxTemp: 35, description: 'Evergreen tree producing two spices: nutmeg (seed) and mace (aril). Native to the Banda Islands.', baseYield: 3, tokensPerHarvest: 40 },
  { commonName: 'Anise', scientificName: 'Pimpinella anisum', family: 'Apiaceae', growingDays: 70, difficulty: 'EASY', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: true, medicinal: true, toxic: false, tags: ['spice', 'herb', 'seed'], minTemp: 10, maxTemp: 30, description: 'Star-shaped seed with licorice flavor. Used in baking, liqueurs, and traditional medicine.', baseYield: 3, tokensPerHarvest: 15 },
  { commonName: 'Celery', scientificName: 'Apium graveolens', family: 'Apiaceae', growingDays: 80, difficulty: 'MEDIUM', waterNeeds: 'HIGH', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'fall'], edible: true, medicinal: true, toxic: false, tags: ['herb', 'vegetable', 'leaf'], minTemp: 5, maxTemp: 25, description: 'Crunchy stalks and aromatic leaves. Cool-season crop needing consistent moisture.', baseYield: 4, tokensPerHarvest: 10 },
  { commonName: 'Chives', scientificName: 'Allium schoenoprasum', family: 'Amaryllidaceae', growingDays: 30, difficulty: 'EASY', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer', 'fall'], edible: true, medicinal: false, toxic: false, tags: ['herb', 'leaf', 'onion-family'], minTemp: -15, maxTemp: 30, description: 'Mild onion-flavored herb with edible purple flowers. Hardy perennial that returns each year.', baseYield: 3, tokensPerHarvest: 8 },
  { commonName: 'Stevia', scientificName: 'Stevia rebaudiana', family: 'Asteraceae', growingDays: 90, difficulty: 'MEDIUM', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: true, medicinal: false, toxic: false, tags: ['herb', 'sweetener', 'medicinal'], minTemp: 10, maxTemp: 35, description: 'Natural zero-calorie sweetener from leaf extracts. 200-300 times sweeter than sugar.', baseYield: 3, tokensPerHarvest: 15 },

  // ═══════════════════════════════════════════════════════════════════════════
  // VEGETABLES (25 species)
  // ═══════════════════════════════════════════════════════════════════════════
  { commonName: 'Potato', scientificName: 'Solanum tuberosum', family: 'Solanaceae', growingDays: 80, difficulty: 'EASY', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'fall'], edible: true, medicinal: false, toxic: false, tags: ['vegetable', 'root', 'staple'], minTemp: 5, maxTemp: 30, description: 'Starchy tuber and global food staple. Grows best in cool weather with loose, well-drained soil.', baseYield: 8, tokensPerHarvest: 15 },
  { commonName: 'Sweet Potato', scientificName: 'Ipomoea batatas', family: 'Convolvulaceae', growingDays: 100, difficulty: 'EASY', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: true, medicinal: false, toxic: false, tags: ['vegetable', 'root', 'tuber'], minTemp: 15, maxTemp: 38, description: 'Orange-fleshed tuber rich in beta-carotene. Vigorous vine that thrives in warm climates.', baseYield: 7, tokensPerHarvest: 15 },
  { commonName: 'Beetroot', scientificName: 'Beta vulgaris', family: 'Amaranthaceae', growingDays: 55, difficulty: 'EASY', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'fall'], edible: true, medicinal: false, toxic: false, tags: ['vegetable', 'root', 'leafy'], minTemp: 5, maxTemp: 30, description: 'Deep red root vegetable with edible greens. Sweet, earthy flavor when roasted.', baseYield: 5, tokensPerHarvest: 12 },
  { commonName: 'Radish', scientificName: 'Raphanus sativus', family: 'Brassicaceae', growingDays: 25, difficulty: 'EASY', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'fall'], edible: true, medicinal: false, toxic: false, tags: ['vegetable', 'root'], minTemp: 5, maxTemp: 25, description: 'Fastest-growing root vegetable. Crunchy, peppery flavor. Great for beginners.', baseYield: 5, tokensPerHarvest: 8 },
  { commonName: 'Turnip', scientificName: 'Brassica rapa', family: 'Brassicaceae', growingDays: 50, difficulty: 'EASY', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['fall', 'winter'], edible: true, medicinal: false, toxic: false, tags: ['vegetable', 'root'], minTemp: 0, maxTemp: 25, description: 'Cool-season root vegetable with mild, slightly sweet flavor. Greens are also edible.', baseYield: 5, tokensPerHarvest: 10 },
  { commonName: 'Cabbage', scientificName: 'Brassica oleracea var. capitata', family: 'Brassicaceae', growingDays: 80, difficulty: 'MEDIUM', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['winter', 'spring', 'fall'], edible: true, medicinal: false, toxic: false, tags: ['vegetable', 'leafy', 'brassica'], minTemp: 5, maxTemp: 25, description: 'Compact head of layered leaves. Cool-season crop that sweetens after frost.', baseYield: 6, tokensPerHarvest: 12 },
  { commonName: 'Broccoli', scientificName: 'Brassica oleracea var. italica', family: 'Brassicaceae', growingDays: 70, difficulty: 'MEDIUM', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['fall', 'winter', 'spring'], edible: true, medicinal: false, toxic: false, tags: ['vegetable', 'brassica', 'green'], minTemp: 5, maxTemp: 25, description: 'Green flower heads packed with nutrients. Harvest before flowers open for best flavor.', baseYield: 5, tokensPerHarvest: 15 },
  { commonName: 'Bell Pepper', scientificName: 'Capsicum annuum var. grossum', family: 'Solanaceae', growingDays: 75, difficulty: 'MEDIUM', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: true, medicinal: false, toxic: false, tags: ['vegetable', 'pepper', 'colorful'], minTemp: 15, maxTemp: 35, description: 'Sweet, colorful pepper in red, yellow, orange, and green. Rich in vitamin C.', baseYield: 5, tokensPerHarvest: 15 },
  { commonName: 'Corn', scientificName: 'Zea mays', family: 'Poaceae', growingDays: 80, difficulty: 'MEDIUM', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: true, medicinal: false, toxic: false, tags: ['vegetable', 'grain', 'staple'], minTemp: 15, maxTemp: 35, description: 'Tall cereal grain producing ears of sweet kernels. Wind-pollinated, plant in blocks.', baseYield: 6, tokensPerHarvest: 12 },
  { commonName: 'Green Bean', scientificName: 'Phaseolus vulgaris', family: 'Fabaceae', growingDays: 55, difficulty: 'EASY', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: true, medicinal: false, toxic: false, tags: ['vegetable', 'legume', 'green'], minTemp: 10, maxTemp: 30, description: 'Snap beans eaten fresh or cooked. Bush and pole varieties available.', baseYield: 5, tokensPerHarvest: 12 },
  { commonName: 'Peas', scientificName: 'Pisum sativum', family: 'Fabaceae', growingDays: 55, difficulty: 'EASY', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['winter', 'spring'], edible: true, medicinal: false, toxic: false, tags: ['vegetable', 'legume', 'green'], minTemp: 5, maxTemp: 25, description: 'Sweet green spheres in pods. Cool-season crop that fixes nitrogen in soil.', baseYield: 5, tokensPerHarvest: 12 },
  { commonName: 'Bitter Gourd', scientificName: 'Momordica charantia', family: 'Cucurbitaceae', growingDays: 70, difficulty: 'MEDIUM', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: true, medicinal: true, toxic: false, tags: ['vegetable', 'gourd', 'indian', 'medicinal'], minTemp: 18, maxTemp: 38, description: 'Warty, bitter fruit used in Indian and Asian cooking. Medicinal properties for blood sugar.', baseYield: 5, tokensPerHarvest: 15 },
  { commonName: 'Ridge Gourd', scientificName: 'Luffa acutangula', family: 'Cucurbitaceae', growingDays: 60, difficulty: 'EASY', waterNeeds: 'HIGH', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: true, medicinal: false, toxic: false, tags: ['vegetable', 'gourd', 'indian'], minTemp: 18, maxTemp: 38, description: 'Ridged gourd with soft, spongy flesh. Vigorous climbing vine common in Indian kitchens.', baseYield: 6, tokensPerHarvest: 12 },
  { commonName: 'Bottle Gourd', scientificName: 'Lagenaria siceraria', family: 'Cucurbitaceae', growingDays: 65, difficulty: 'EASY', waterNeeds: 'HIGH', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: true, medicinal: true, toxic: false, tags: ['vegetable', 'gourd', 'indian', 'medicinal'], minTemp: 18, maxTemp: 38, description: 'Smooth-skinned gourd used in curries and drinks. Also used as a container when dried.', baseYield: 6, tokensPerHarvest: 12 },
  { commonName: 'Ash Gourd', scientificName: 'Benincasa hispida', family: 'Cucurbitaceae', growingDays: 80, difficulty: 'MEDIUM', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: true, medicinal: true, toxic: false, tags: ['vegetable', 'gourd', 'indian', 'medicinal'], minTemp: 18, maxTemp: 38, description: 'Waxy-coated gourd used in Indian sweets and juices. Long shelf life when mature.', baseYield: 6, tokensPerHarvest: 15 },
  { commonName: 'Snake Gourd', scientificName: 'Trichosanthes cucumerina', family: 'Cucurbitaceae', growingDays: 60, difficulty: 'EASY', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: true, medicinal: false, toxic: false, tags: ['vegetable', 'gourd', 'indian'], minTemp: 18, maxTemp: 38, description: 'Long, snake-like gourd common in South Indian cuisine. Vigorous climbing vine.', baseYield: 5, tokensPerHarvest: 12 },
  { commonName: 'Drumstick', scientificName: 'Moringa oleifera', family: 'Moringaceae', growingDays: 120, difficulty: 'EASY', waterNeeds: 'LOW', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: true, medicinal: true, toxic: false, tags: ['vegetable', 'tree', 'indian', 'medicinal'], minTemp: 15, maxTemp: 40, description: 'Fast-growing tree with edible pods, leaves, and flowers. Called the miracle tree for nutrition.', baseYield: 6, tokensPerHarvest: 20 },
  { commonName: 'Amaranth', scientificName: 'Amaranthus viridis', family: 'Amaranthaceae', growingDays: 35, difficulty: 'EASY', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: true, medicinal: false, toxic: false, tags: ['vegetable', 'leafy', 'green'], minTemp: 15, maxTemp: 38, description: 'Fast-growing leafy green with tender stems. Used in stir-fries and soups across Asia.', baseYield: 5, tokensPerHarvest: 10 },
  { commonName: 'Lettuce', scientificName: 'Lactuca sativa', family: 'Asteraceae', growingDays: 45, difficulty: 'EASY', waterNeeds: 'MODERATE', sunlightNeeds: 'PARTIAL_SHADE', seasons: ['spring', 'fall'], edible: true, medicinal: false, toxic: false, tags: ['vegetable', 'leafy', 'green'], minTemp: 5, maxTemp: 25, description: 'Crisp leafy vegetable for salads. Cool-season crop that bolts in heat.', baseYield: 4, tokensPerHarvest: 8 },
  { commonName: 'Kale', scientificName: 'Brassica oleracea var. sabellica', family: 'Brassicaceae', growingDays: 55, difficulty: 'EASY', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['fall', 'winter'], edible: true, medicinal: false, toxic: false, tags: ['vegetable', 'leafy', 'green', 'brassica'], minTemp: -5, maxTemp: 25, description: 'Hardy leafy green packed with nutrients. Sweetens after frost exposure.', baseYield: 5, tokensPerHarvest: 10 },
  { commonName: 'Asparagus', scientificName: 'Asparagus officinalis', family: 'Asparagaceae', growingDays: 120, difficulty: 'HARD', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring'], edible: true, medicinal: false, toxic: false, tags: ['vegetable', 'perennial'], minTemp: -10, maxTemp: 30, description: 'Perennial vegetable producing tender spears each spring. Crowns last 15-20 years.', baseYield: 4, tokensPerHarvest: 20 },
  { commonName: 'Artichoke', scientificName: 'Cynara cardunculus', family: 'Asteraceae', growingDays: 120, difficulty: 'HARD', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'fall'], edible: true, medicinal: false, toxic: false, tags: ['vegetable', 'thistle'], minTemp: 5, maxTemp: 30, description: 'Edible flower bud of a thistle plant. Mediterranean specialty with nutty flavor.', baseYield: 4, tokensPerHarvest: 18 },
  { commonName: 'Leek', scientificName: 'Allium ampeloprasum', family: 'Amaryllidaceae', growingDays: 100, difficulty: 'EASY', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['fall', 'winter', 'spring'], edible: true, medicinal: false, toxic: false, tags: ['vegetable', 'onion-family'], minTemp: -5, maxTemp: 25, description: 'Mild onion flavor with long white stalk. Hardy cool-season vegetable.', baseYield: 4, tokensPerHarvest: 12 },

  // ═══════════════════════════════════════════════════════════════════════════
  // MEDICINAL PLANTS (20 species)
  // ═══════════════════════════════════════════════════════════════════════════
  { commonName: 'Neem', scientificName: 'Azadirachta indica', family: 'Meliaceae', growingDays: 180, difficulty: 'EASY', waterNeeds: 'LOW', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: false, medicinal: true, toxic: true, tags: ['medicinal', 'tree', 'indian', 'pesticide'], minTemp: 10, maxTemp: 45, description: 'Versatile medicinal tree. Leaves, bark, and oil used for pest control, skincare, and dental health.', baseYield: 6, tokensPerHarvest: 15 },
  { commonName: 'Ashwagandha', scientificName: 'Withania somnifera', family: 'Solanaceae', growingDays: 120, difficulty: 'EASY', waterNeeds: 'LOW', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: false, medicinal: true, toxic: false, tags: ['medicinal', 'adaptogen', 'indian'], minTemp: 10, maxTemp: 40, description: 'Premier Ayurvedic adaptogen. Root extract reduces stress and boosts immunity.', baseYield: 4, tokensPerHarvest: 25 },
  { commonName: 'Brahmi', scientificName: 'Bacopa monnieri', family: 'Plantaginaceae', growingDays: 60, difficulty: 'MEDIUM', waterNeeds: 'HIGH', sunlightNeeds: 'PARTIAL_SHADE', seasons: ['spring', 'summer'], edible: false, medicinal: true, toxic: false, tags: ['medicinal', 'ayurvedic', 'indian'], minTemp: 15, maxTemp: 38, description: 'Brain tonic in Ayurveda. Small creeping herb that grows in wetlands. Enhances memory and cognition.', baseYield: 3, tokensPerHarvest: 25 },
  { commonName: 'Tulsi', scientificName: 'Ocimum tenuiflorum', family: 'Lamiaceae', growingDays: 40, difficulty: 'EASY', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer', 'fall'], edible: true, medicinal: true, toxic: false, tags: ['medicinal', 'herb', 'indian', 'sacred'], minTemp: 12, maxTemp: 38, description: 'Holy basil, sacred in Hinduism. Adaptogenic herb that boosts immunity and reduces stress.', baseYield: 4, tokensPerHarvest: 15 },
  { commonName: 'Moringa', scientificName: 'Moringa oleifera', family: 'Moringaceae', growingDays: 120, difficulty: 'EASY', waterNeeds: 'LOW', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: true, medicinal: true, toxic: false, tags: ['medicinal', 'tree', 'superfood', 'indian'], minTemp: 15, maxTemp: 40, description: 'Miracle tree with nutrient-dense leaves. Rich in vitamins, minerals, and amino acids.', baseYield: 6, tokensPerHarvest: 20 },
  { commonName: 'Shatavari', scientificName: 'Asparagus racemosus', family: 'Asparagaceae', growingDays: 150, difficulty: 'MEDIUM', waterNeeds: 'MODERATE', sunlightNeeds: 'PARTIAL_SHADE', seasons: ['spring', 'summer'], edible: false, medicinal: true, toxic: false, tags: ['medicinal', 'ayurvedic', 'indian'], minTemp: 12, maxTemp: 35, description: 'Queen of herbs in Ayurveda for women\'s health. Tuberous root used as a rejuvenative tonic.', baseYield: 3, tokensPerHarvest: 30 },
  { commonName: 'Giloy', scientificName: 'Tinospora cordifolia', family: 'Menispermaceae', growingDays: 120, difficulty: 'MEDIUM', waterNeeds: 'MODERATE', sunlightNeeds: 'PARTIAL_SHADE', seasons: ['spring', 'summer'], edible: false, medicinal: true, toxic: false, tags: ['medicinal', 'ayurvedic', 'indian', 'vine'], minTemp: 15, maxTemp: 38, description: 'Amrita (divine nectar) in Ayurveda. Climbing shrub used for fever, immunity, and diabetes.', baseYield: 4, tokensPerHarvest: 25 },
  { commonName: 'Amla', scientificName: 'Phyllanthus emblica', family: 'Phyllanthaceae', growingDays: 180, difficulty: 'MEDIUM', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['winter', 'spring'], edible: true, medicinal: true, toxic: false, tags: ['medicinal', 'fruit', 'indian', 'tree'], minTemp: 5, maxTemp: 40, description: 'Indian gooseberry, richest natural source of vitamin C. Foundational herb in Ayurveda.', baseYield: 5, tokensPerHarvest: 25 },
  { commonName: 'Haritaki', scientificName: 'Terminalia chebula', family: 'Combretaceae', growingDays: 200, difficulty: 'HARD', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: false, medicinal: true, toxic: false, tags: ['medicinal', 'ayurvedic', 'tree'], minTemp: 10, maxTemp: 40, description: 'King of medicines in Ayurveda. Dried fruit used in Triphala for digestive health.', baseYield: 4, tokensPerHarvest: 30 },
  { commonName: 'Bibhitaki', scientificName: 'Terminalia bellirica', family: 'Combretaceae', growingDays: 200, difficulty: 'HARD', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: false, medicinal: true, toxic: false, tags: ['medicinal', 'ayurvedic', 'tree'], minTemp: 10, maxTemp: 40, description: 'One of the three fruits in Triphala. Used for respiratory and digestive ailments.', baseYield: 4, tokensPerHarvest: 30 },
  { commonName: 'Guduchi', scientificName: 'Tinospora cordifolia', family: 'Menispermaceae', growingDays: 120, difficulty: 'MEDIUM', waterNeeds: 'MODERATE', sunlightNeeds: 'PARTIAL_SHADE', seasons: ['spring', 'summer'], edible: false, medicinal: true, toxic: false, tags: ['medicinal', 'ayurvedic', 'indian'], minTemp: 15, maxTemp: 38, description: 'Another name for Giloy. Immunomodulatory herb that enhances natural killer cell activity.', baseYield: 4, tokensPerHarvest: 25 },
  { commonName: 'Manjistha', scientificName: 'Rubia cordifolia', family: 'Rubiaceae', growingDays: 120, difficulty: 'MEDIUM', waterNeeds: 'MODERATE', sunlightNeeds: 'PARTIAL_SHADE', seasons: ['spring', 'summer'], edible: false, medicinal: true, toxic: false, tags: ['medicinal', 'ayurvedic', 'indian'], minTemp: 12, maxTemp: 35, description: 'Blood purifier in Ayurveda. Climbing herb with red roots used for skin and liver health.', baseYield: 3, tokensPerHarvest: 25 },
  { commonName: 'Shankhpushpi', scientificName: 'Convolvulus pluricaulis', family: 'Convolvulaceae', growingDays: 60, difficulty: 'MEDIUM', waterNeeds: 'MODERATE', sunlightNeeds: 'PARTIAL_SHADE', seasons: ['spring', 'summer'], edible: false, medicinal: true, toxic: false, tags: ['medicinal', 'ayurvedic', 'indian'], minTemp: 15, maxTemp: 35, description: 'Brain tonic and nervine herb. Small blue flowers used for memory and mental clarity.', baseYield: 3, tokensPerHarvest: 20 },
  { commonName: 'Bhringraj', scientificName: 'Eclipta alba', family: 'Asteraceae', growingDays: 45, difficulty: 'EASY', waterNeeds: 'HIGH', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: false, medicinal: true, toxic: false, tags: ['medicinal', 'ayurvedic', 'indian', 'hair-care'], minTemp: 15, maxTemp: 38, description: 'King of herbs for hair health. Used in oils and tonics for hair growth and liver support.', baseYield: 3, tokensPerHarvest: 18 },
  { commonName: 'Arjuna', scientificName: 'Terminalia arjuna', family: 'Combretaceae', growingDays: 365, difficulty: 'HARD', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: false, medicinal: true, toxic: false, tags: ['medicinal', 'ayurvedic', 'tree'], minTemp: 10, maxTemp: 40, description: 'Cardiac tonic bark in Ayurveda. Large tree with heart-strengthening bark extract.', baseYield: 5, tokensPerHarvest: 30 },
  { commonName: 'Triphala', scientificName: 'Triphala blend', family: 'Polyherbal', growingDays: 150, difficulty: 'MEDIUM', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: false, medicinal: true, toxic: false, tags: ['medicinal', 'ayurvedic', 'polyherbal'], minTemp: 10, maxTemp: 40, description: 'Traditional Ayurvedic blend of three fruits: Haritaki, Bibhitaki, and Amla. Digestive tonic.', baseYield: 3, tokensPerHarvest: 25 },
  { commonName: 'Yastimadhu', scientificName: 'Glycyrrhiza glabra', family: 'Fabaceae', growingDays: 120, difficulty: 'MEDIUM', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: true, medicinal: true, toxic: false, tags: ['medicinal', 'herb', 'root'], minTemp: 5, maxTemp: 35, description: 'Licorice root. Sweet root used for sore throats, digestion, and as a flavoring agent.', baseYield: 4, tokensPerHarvest: 20 },
  { commonName: 'Punarnava', scientificName: 'Boerhavia diffusa', family: 'Nyctaginaceae', growingDays: 60, difficulty: 'EASY', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: false, medicinal: true, toxic: false, tags: ['medicinal', 'ayurvedic', 'indian'], minTemp: 15, maxTemp: 40, description: 'Renewer of the body in Ayurveda. Used for kidney and urinary tract health.', baseYield: 3, tokensPerHarvest: 20 },
  { commonName: 'Kutaja', scientificName: 'Holarrhena antidysenterica', family: 'Apocynaceae', growingDays: 180, difficulty: 'MEDIUM', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: false, medicinal: true, toxic: false, tags: ['medicinal', 'ayurvedic', 'tree'], minTemp: 10, maxTemp: 40, description: 'Anti-dysenteric bark tree. Traditional remedy for diarrhea and intestinal infections.', baseYield: 4, tokensPerHarvest: 25 },

  // ═══════════════════════════════════════════════════════════════════════════
  // HARDWOOD/TIMBER TREES (20 species)
  // ═══════════════════════════════════════════════════════════════════════════
  { commonName: 'Teak', scientificName: 'Tectona grandis', family: 'Lamiaceae', growingDays: 365, difficulty: 'HARD', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: false, medicinal: false, toxic: false, tags: ['timber', 'hardwood', 'tree'], minTemp: 12, maxTemp: 40, description: 'Premier tropical hardwood. Extremely durable, water-resistant wood used in furniture and boat-building.', baseYield: 10, tokensPerHarvest: 50 },
  { commonName: 'Mahogany', scientificName: 'Swietenia macrophylla', family: 'Meliaceae', growingDays: 365, difficulty: 'HARD', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: false, medicinal: false, toxic: false, tags: ['timber', 'hardwood', 'tree'], minTemp: 15, maxTemp: 38, description: 'Prized hardwood with rich reddish-brown color. Used in fine furniture and cabinetry.', baseYield: 10, tokensPerHarvest: 50 },
  { commonName: 'Sal', scientificName: 'Shorea robusta', family: 'Dipterocarpaceae', growingDays: 365, difficulty: 'HARD', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: false, medicinal: false, toxic: false, tags: ['timber', 'hardwood', 'tree'], minTemp: 10, maxTemp: 40, description: 'Major Indian timber tree. Hard, durable wood used in construction and railway sleepers.', baseYield: 10, tokensPerHarvest: 45 },
  { commonName: 'Sheesham', scientificName: 'Dalbergia sissoo', family: 'Fabaceae', growingDays: 365, difficulty: 'MEDIUM', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: false, medicinal: false, toxic: false, tags: ['timber', 'hardwood', 'indian', 'tree'], minTemp: 5, maxTemp: 40, description: 'Indian rosewood. Fast-growing timber tree with durable, decorative heartwood.', baseYield: 8, tokensPerHarvest: 40 },
  { commonName: 'Sandalwood', scientificName: 'Santalum album', family: 'Santalaceae', growingDays: 365, difficulty: 'HARD', waterNeeds: 'LOW', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: false, medicinal: true, toxic: false, tags: ['timber', 'fragrant', 'indian', 'medicinal'], minTemp: 15, maxTemp: 40, description: 'Precious fragrant heartwood. Slow-growing hemiparasitic tree. Oil used in perfumery and medicine.', baseYield: 5, tokensPerHarvest: 50 },
  { commonName: 'Deodar', scientificName: 'Cedrus deodara', family: 'Pinaceae', growingDays: 365, difficulty: 'HARD', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: false, medicinal: false, toxic: false, tags: ['timber', 'conifer', 'tree'], minTemp: -15, maxTemp: 30, description: 'Himalayan cedar with drooping branches. Sacred wood used in temples and construction.', baseYield: 8, tokensPerHarvest: 40 },
  { commonName: 'Rosewood', scientificName: 'Dalbergia latifolia', family: 'Fabaceae', growingDays: 365, difficulty: 'HARD', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: false, medicinal: false, toxic: false, tags: ['timber', 'hardwood', 'indian', 'tree'], minTemp: 10, maxTemp: 40, description: 'East Indian rosewood. Highly prized for musical instruments and fine furniture.', baseYield: 8, tokensPerHarvest: 45 },
  { commonName: 'Ebony', scientificName: 'Diospyros ebenum', family: 'Ebenaceae', growingDays: 365, difficulty: 'HARD', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: false, medicinal: false, toxic: false, tags: ['timber', 'hardwood', 'tree'], minTemp: 15, maxTemp: 38, description: 'Jet-black hardwood among the most valuable timber. Dense, fine-grained wood for carving.', baseYield: 8, tokensPerHarvest: 45 },
  { commonName: 'Bamboo', scientificName: 'Bambusa vulgaris', family: 'Poaceae', growingDays: 90, difficulty: 'EASY', waterNeeds: 'HIGH', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: true, medicinal: false, toxic: false, tags: ['timber', 'grass', 'sustainable'], minTemp: 10, maxTemp: 40, description: 'Fastest-growing plant on Earth. Sustainable building material with countless uses.', baseYield: 10, tokensPerHarvest: 20 },
  { commonName: 'Shorea', scientificName: 'Shorea robusta', family: 'Dipterocarpaceae', growingDays: 365, difficulty: 'HARD', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: false, medicinal: false, toxic: false, tags: ['timber', 'hardwood', 'tree'], minTemp: 10, maxTemp: 40, description: 'Major timber tree of Indian sal forests. Hard wood used in construction.', baseYield: 9, tokensPerHarvest: 40 },
  { commonName: 'Cedar', scientificName: 'Cedrus libani', family: 'Pinaceae', growingDays: 365, difficulty: 'MEDIUM', waterNeeds: 'LOW', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: false, medicinal: false, toxic: false, tags: ['timber', 'conifer', 'tree'], minTemp: -20, maxTemp: 30, description: 'Fragrant evergreen conifer. Aromatic wood used for chests, closets, and construction.', baseYield: 8, tokensPerHarvest: 35 },
  { commonName: 'Pine', scientificName: 'Pinus sylvestris', family: 'Pinaceae', growingDays: 365, difficulty: 'EASY', waterNeeds: 'LOW', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: false, medicinal: false, toxic: false, tags: ['timber', 'conifer', 'tree'], minTemp: -30, maxTemp: 30, description: 'Most widespread conifer genus. Softwood used in construction, paper, and turpentine.', baseYield: 8, tokensPerHarvest: 30 },
  { commonName: 'Spruce', scientificName: 'Picea abies', family: 'Pinaceae', growingDays: 365, difficulty: 'EASY', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: false, medicinal: false, toxic: false, tags: ['timber', 'conifer', 'tree'], minTemp: -40, maxTemp: 25, description: 'Cold-hardy conifer with straight trunk. Major timber tree for construction and paper.', baseYield: 8, tokensPerHarvest: 30 },
  { commonName: 'Fir', scientificName: 'Abies alba', family: 'Pinaceae', growingDays: 365, difficulty: 'EASY', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: false, medicinal: false, toxic: false, tags: ['timber', 'conifer', 'tree'], minTemp: -30, maxTemp: 25, description: 'Elegant conifer with flat needles. Used as Christmas trees and in construction.', baseYield: 7, tokensPerHarvest: 30 },
  { commonName: 'Oak', scientificName: 'Quercus robur', family: 'Fagaceae', growingDays: 365, difficulty: 'MEDIUM', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: false, medicinal: false, toxic: false, tags: ['timber', 'hardwood', 'tree'], minTemp: -20, maxTemp: 35, description: 'Strong, durable hardwood. Acorns historically used as food. King of temperate forests.', baseYield: 9, tokensPerHarvest: 40 },
  { commonName: 'Walnut Timber', scientificName: 'Juglans regia', family: 'Juglandaceae', growingDays: 365, difficulty: 'MEDIUM', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: false, medicinal: false, toxic: false, tags: ['timber', 'hardwood', 'tree'], minTemp: -15, maxTemp: 35, description: 'Prized furniture wood with rich grain. Also produces edible walnuts.', baseYield: 8, tokensPerHarvest: 40 },
  { commonName: 'Maple', scientificName: 'Acer saccharum', family: 'Sapindaceae', growingDays: 365, difficulty: 'MEDIUM', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'fall'], edible: false, medicinal: false, toxic: false, tags: ['timber', 'hardwood', 'tree'], minTemp: -25, maxTemp: 30, description: 'Dense, hard wood for flooring and furniture. Also tapped for maple syrup.', baseYield: 8, tokensPerHarvest: 35 },
  { commonName: 'Birch', scientificName: 'Betula pendula', family: 'Betulaceae', growingDays: 365, difficulty: 'EASY', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: false, medicinal: false, toxic: false, tags: ['timber', 'hardwood', 'tree'], minTemp: -30, maxTemp: 25, description: 'Graceful tree with distinctive white bark. Light wood for plywood and turnery.', baseYield: 7, tokensPerHarvest: 25 },
  { commonName: 'Cypress', scientificName: 'Cupressus sempervirens', family: 'Cupressaceae', growingDays: 365, difficulty: 'EASY', waterNeeds: 'LOW', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: false, medicinal: false, toxic: false, tags: ['timber', 'conifer', 'tree'], minTemp: -10, maxTemp: 40, description: 'Tall, narrow evergreen iconic in Mediterranean landscapes. Rot-resistant wood.', baseYield: 7, tokensPerHarvest: 30 },

  // ═══════════════════════════════════════════════════════════════════════════
  // NUT TREES (15 species)
  // ═══════════════════════════════════════════════════════════════════════════
  { commonName: 'Almond', scientificName: 'Prunus dulcis', family: 'Rosaceae', growingDays: 180, difficulty: 'MEDIUM', waterNeeds: 'LOW', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'fall'], edible: true, medicinal: false, toxic: false, tags: ['nut', 'tree'], minTemp: -5, maxTemp: 40, description: 'Sweet nut with a hard shell. Drought-tolerant tree requiring mild winters.', baseYield: 5, tokensPerHarvest: 30 },
  { commonName: 'Cashew', scientificName: 'Anacardium occidentale', family: 'Anacardiaceae', growingDays: 180, difficulty: 'MEDIUM', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: true, medicinal: false, toxic: false, tags: ['nut', 'tropical', 'tree'], minTemp: 15, maxTemp: 40, description: 'Kidney-shaped nut growing outside the cashew apple. Tropical evergreen tree.', baseYield: 4, tokensPerHarvest: 35 },
  { commonName: 'Pecan', scientificName: 'Carya illinoinensis', family: 'Juglandaceae', growingDays: 180, difficulty: 'MEDIUM', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['fall'], edible: true, medicinal: false, toxic: false, tags: ['nut', 'tree'], minTemp: -15, maxTemp: 38, description: 'Rich, buttery nut native to North America. Large deciduous tree needing deep soil.', baseYield: 5, tokensPerHarvest: 30 },
  { commonName: 'Macadamia', scientificName: 'Macadamia integrifolia', family: 'Proteaceae', growingDays: 200, difficulty: 'HARD', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'fall'], edible: true, medicinal: false, toxic: false, tags: ['nut', 'tropical', 'tree'], minTemp: 5, maxTemp: 35, description: 'Hardest-shelled nut with creamy, rich flavor. Australian native requiring subtropical climate.', baseYield: 4, tokensPerHarvest: 35 },
  { commonName: 'Hazelnut', scientificName: 'Corylus avellana', family: 'Betulaceae', growingDays: 150, difficulty: 'EASY', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['fall'], edible: true, medicinal: false, toxic: false, tags: ['nut', 'shrub'], minTemp: -15, maxTemp: 30, description: 'Small, round nut with sweet flavor. Easy-to-grow shrub or small tree.', baseYield: 5, tokensPerHarvest: 25 },
  { commonName: 'Chestnut', scientificName: 'Castanea sativa', family: 'Fagaceae', growingDays: 150, difficulty: 'MEDIUM', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['fall'], edible: true, medicinal: false, toxic: false, tags: ['nut', 'tree'], minTemp: -15, maxTemp: 30, description: 'Sweet, starchy nut enclosed in spiny burrs. Major food tree in Europe and Asia.', baseYield: 6, tokensPerHarvest: 25 },
  { commonName: 'Pistachio', scientificName: 'Pistacia vera', family: 'Anacardiaceae', growingDays: 160, difficulty: 'MEDIUM', waterNeeds: 'LOW', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'fall'], edible: true, medicinal: false, toxic: false, tags: ['nut', 'tree'], minTemp: -10, maxTemp: 42, description: 'Open-shelled nut with distinctive flavor. Drought-tolerant tree needing hot summers.', baseYield: 4, tokensPerHarvest: 35 },
  { commonName: 'Areca Nut', scientificName: 'Areca catechu', family: 'Arecaceae', growingDays: 365, difficulty: 'HARD', waterNeeds: 'HIGH', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: false, medicinal: true, toxic: false, tags: ['nut', 'palm', 'indian'], minTemp: 18, maxTemp: 38, description: 'Betel nut palm. Seeds used in South Asian betel quid. Stimulant with medicinal properties.', baseYield: 5, tokensPerHarvest: 20 },
  { commonName: 'Betel Nut', scientificName: 'Areca catechu', family: 'Arecaceae', growingDays: 365, difficulty: 'HARD', waterNeeds: 'HIGH', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: false, medicinal: true, toxic: false, tags: ['nut', 'palm', 'indian'], minTemp: 18, maxTemp: 38, description: 'Another name for Areca Nut. Used in traditional stimulant preparations across Asia.', baseYield: 5, tokensPerHarvest: 20 },
  { commonName: 'Pine Nut', scientificName: 'Pinus gerardiana', family: 'Pinaceae', growingDays: 365, difficulty: 'HARD', waterNeeds: 'LOW', sunlightNeeds: 'FULL_SUN', seasons: ['fall'], edible: true, medicinal: false, toxic: false, tags: ['nut', 'conifer', 'tree'], minTemp: -10, maxTemp: 30, description: 'Edible seeds from pine cones. Chilgoza pine native to the Himalayas.', baseYield: 3, tokensPerHarvest: 35 },
  { commonName: 'Brazil Nut', scientificName: 'Bertholletia excelsa', family: 'Lecythidaceae', growingDays: 365, difficulty: 'HARD', waterNeeds: 'HIGH', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: true, medicinal: false, toxic: false, tags: ['nut', 'tropical', 'tree'], minTemp: 18, maxTemp: 35, description: 'Large, triangular nut from Amazon rainforest. Depends on specific orchid bee for pollination.', baseYield: 5, tokensPerHarvest: 40 },
  { commonName: 'Ginkgo', scientificName: 'Ginkgo biloba', family: 'Ginkgoaceae', growingDays: 365, difficulty: 'EASY', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'fall'], edible: true, medicinal: true, toxic: false, tags: ['nut', 'tree', 'medicinal', 'living-fossil'], minTemp: -20, maxTemp: 35, description: 'Living fossil tree with fan-shaped leaves. Nuts used in Chinese medicine and cooking.', baseYield: 4, tokensPerHarvest: 30 },
  { commonName: 'Tung', scientificName: 'Vernicia fordii', family: 'Euphorbiaceae', growingDays: 200, difficulty: 'MEDIUM', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: false, medicinal: false, toxic: true, tags: ['timber', 'oil', 'tree'], minTemp: 5, maxTemp: 35, description: 'Oil-producing tree. Tung oil from seeds used in varnishes and paints. Toxic if ingested.', baseYield: 6, tokensPerHarvest: 20 },
  { commonName: 'Tallow Tree', scientificName: 'Triadica sebifera', family: 'Euphorbiaceae', growingDays: 200, difficulty: 'EASY', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: false, medicinal: false, toxic: false, tags: ['timber', 'wax', 'tree'], minTemp: 5, maxTemp: 38, description: 'Seeds coated in white waxy tallow used for candles and soap. Fast-growing tree.', baseYield: 6, tokensPerHarvest: 20 },

  // ═══════════════════════════════════════════════════════════════════════════
  // VINE/CLIMBER PLANTS (12 species — no duplicates with fruit trees)
  // ═══════════════════════════════════════════════════════════════════════════
  { commonName: 'Ivy', scientificName: 'Hedera helix', family: 'Araliaceae', growingDays: 120, difficulty: 'EASY', waterNeeds: 'LOW', sunlightNeeds: 'PARTIAL_SHADE', seasons: ['spring', 'summer', 'fall'], edible: false, medicinal: false, toxic: true, tags: ['vine', 'ornamental', 'climber'], minTemp: -15, maxTemp: 30, description: 'Evergreen climbing vine for walls and ground cover. Fast-growing and shade-tolerant.', baseYield: 2, tokensPerHarvest: 8 },
  { commonName: 'Wisteria', scientificName: 'Wisteria sinensis', family: 'Fabaceae', growingDays: 120, difficulty: 'MEDIUM', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring'], edible: false, medicinal: false, toxic: true, tags: ['vine', 'ornamental', 'climber'], minTemp: -15, maxTemp: 35, description: 'Cascading clusters of fragrant purple flowers. Vigorous twining vine needing strong support.', baseYield: 2, tokensPerHarvest: 12 },
  { commonName: 'Morning Glory', scientificName: 'Ipomoea purpurea', family: 'Convolvulaceae', growingDays: 50, difficulty: 'EASY', waterNeeds: 'LOW', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: false, medicinal: false, toxic: true, tags: ['vine', 'ornamental', 'climber'], minTemp: 10, maxTemp: 35, description: 'Trumpet-shaped flowers that open each morning. Easy annual vine for fences and trellises.', baseYield: 2, tokensPerHarvest: 8 },
  { commonName: 'Moonflower', scientificName: 'Ipomoea alba', family: 'Convolvulaceae', growingDays: 60, difficulty: 'EASY', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['summer'], edible: false, medicinal: false, toxic: false, tags: ['vine', 'ornamental', 'climber', 'night-bloom'], minTemp: 12, maxTemp: 35, description: 'Large, fragrant white flowers that open at night. Magical evening garden plant.', baseYield: 2, tokensPerHarvest: 10 },
  { commonName: 'Pointed Gourd', scientificName: 'Trichosanthes dioica', family: 'Cucurbitaceae', growingDays: 70, difficulty: 'MEDIUM', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: true, medicinal: false, toxic: false, tags: ['vine', 'vegetable', 'indian'], minTemp: 18, maxTemp: 38, description: 'Parwal — a pointed gourd used in Indian curries. Climbing vine producing green-striped fruits.', baseYield: 5, tokensPerHarvest: 12 },
  { commonName: 'Malabar Spinach', scientificName: 'Basella alba', family: 'Basellaceae', growingDays: 55, difficulty: 'EASY', waterNeeds: 'HIGH', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: true, medicinal: false, toxic: false, tags: ['vine', 'vegetable', 'leafy', 'tropical'], minTemp: 18, maxTemp: 38, description: 'Heat-loving climbing spinach. Thick, mucilaginous leaves used in soups and stir-fries.', baseYield: 5, tokensPerHarvest: 10 },
  { commonName: 'Chayote', scientificName: 'Sechium edule', family: 'Cucurbitaceae', growingDays: 80, difficulty: 'EASY', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: true, medicinal: false, toxic: false, tags: ['vine', 'vegetable', 'gourd'], minTemp: 15, maxTemp: 35, description: 'Pear-shaped gourd with single large seed. Vigorous climber producing abundantly.', baseYield: 6, tokensPerHarvest: 12 },
  { commonName: 'Air Potato', scientificName: 'Dioscorea bulbifera', family: 'Dioscoreaceae', growingDays: 90, difficulty: 'EASY', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: true, medicinal: false, toxic: false, tags: ['vine', 'vegetable', 'tuber'], minTemp: 15, maxTemp: 38, description: 'Fast-growing yam vine producing aerial tubils. Edible tubers in some varieties.', baseYield: 5, tokensPerHarvest: 12 },
  { commonName: 'Yam', scientificName: 'Dioscorea alata', family: 'Dioscoreaceae', growingDays: 120, difficulty: 'MEDIUM', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: true, medicinal: false, toxic: false, tags: ['vine', 'vegetable', 'tuber', 'staple'], minTemp: 20, maxTemp: 38, description: 'Major tropical tuber crop. Large starchy tubers are a food staple in West Africa and Caribbean.', baseYield: 7, tokensPerHarvest: 15 },
  { commonName: 'Bitter Melon Vine', scientificName: 'Momordica charantia', family: 'Cucurbitaceae', growingDays: 70, difficulty: 'EASY', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: true, medicinal: true, toxic: false, tags: ['vine', 'vegetable', 'medicinal'], minTemp: 18, maxTemp: 38, description: 'Warty bitter fruit on vigorous climbing vine. Used in Asian cooking and diabetes management.', baseYield: 5, tokensPerHarvest: 15 },
  { commonName: 'Climbing Spinach', scientificName: 'Basella alba var. alba', family: 'Basellaceae', growingDays: 55, difficulty: 'EASY', waterNeeds: 'HIGH', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: true, medicinal: false, toxic: false, tags: ['vine', 'vegetable', 'leafy'], minTemp: 18, maxTemp: 38, description: 'Red-stemmed variety of Malabar spinach. Heat-tolerant leafy green for tropical gardens.', baseYield: 5, tokensPerHarvest: 10 },
  { commonName: 'Nasturtium', scientificName: 'Tropaeolum majus', family: 'Tropaeolaceae', growingDays: 50, difficulty: 'EASY', waterNeeds: 'LOW', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer', 'fall'], edible: true, medicinal: false, toxic: false, tags: ['vine', 'edible-flower', 'climber'], minTemp: 5, maxTemp: 30, description: 'Trailing or climbing vine with edible, peppery flowers and leaves. Great companion plant.', baseYield: 3, tokensPerHarvest: 10 },

  // ═══════════════════════════════════════════════════════════════════════════
  // CEREALS & GRAINS (10 species)
  // ═══════════════════════════════════════════════════════════════════════════
  { commonName: 'Wheat', scientificName: 'Triticum aestivum', family: 'Poaceae', growingDays: 100, difficulty: 'MEDIUM', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['winter', 'spring'], edible: true, medicinal: false, toxic: false, tags: ['grain', 'staple', 'cereal'], minTemp: -10, maxTemp: 30, description: 'Most widely grown cereal grain. Foundation of bread and pasta worldwide.', baseYield: 7, tokensPerHarvest: 15 },
  { commonName: 'Barley', scientificName: 'Hordeum vulgare', family: 'Poaceae', growingDays: 90, difficulty: 'EASY', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['winter', 'spring'], edible: true, medicinal: false, toxic: false, tags: ['grain', 'cereal'], minTemp: -10, maxTemp: 30, description: 'Hardy cereal grain used for animal feed, beer, and health foods. Tolerates poor soils.', baseYield: 6, tokensPerHarvest: 12 },
  { commonName: 'Oats', scientificName: 'Avena sativa', family: 'Poaceae', growingDays: 90, difficulty: 'EASY', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: true, medicinal: false, toxic: false, tags: ['grain', 'cereal', 'healthy'], minTemp: -10, maxTemp: 25, description: 'Nutritious cereal grain used for porridge and baking. Cool-season crop.', baseYield: 5, tokensPerHarvest: 12 },
  { commonName: 'Rye', scientificName: 'Secale cereale', family: 'Poaceae', growingDays: 100, difficulty: 'EASY', waterNeeds: 'LOW', sunlightNeeds: 'FULL_SUN', seasons: ['winter', 'spring'], edible: true, medicinal: false, toxic: false, tags: ['grain', 'cereal'], minTemp: -20, maxTemp: 25, description: 'Cold-hardy cereal grain. Used for bread, whiskey, and cover crops.', baseYield: 6, tokensPerHarvest: 12 },
  { commonName: 'Sorghum', scientificName: 'Sorghum bicolor', family: 'Poaceae', growingDays: 110, difficulty: 'EASY', waterNeeds: 'LOW', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: true, medicinal: false, toxic: false, tags: ['grain', 'cereal', 'drought-resistant'], minTemp: 10, maxTemp: 40, description: 'Drought-tolerant cereal grain. Used for food, animal feed, and biofuel in arid regions.', baseYield: 6, tokensPerHarvest: 12 },
  { commonName: 'Millet', scientificName: 'Pennisetum glauceum', family: 'Poaceae', growingDays: 70, difficulty: 'EASY', waterNeeds: 'LOW', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: true, medicinal: false, toxic: false, tags: ['grain', 'cereal', 'drought-resistant', 'indian'], minTemp: 15, maxTemp: 40, description: 'Small-seeded cereal grain important in Indian and African cuisines. Extremely drought-tolerant.', baseYield: 5, tokensPerHarvest: 10 },
  { commonName: 'Quinoa', scientificName: 'Chenopodium quinoa', family: 'Amaranthaceae', growingDays: 100, difficulty: 'MEDIUM', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: true, medicinal: false, toxic: false, tags: ['grain', 'superfood', 'protein'], minTemp: 5, maxTemp: 30, description: 'Protein-rich pseudo-cereal from the Andes. Complete amino acid profile.', baseYield: 5, tokensPerHarvest: 18 },
  { commonName: 'Grain Amaranth', scientificName: 'Amaranthus hypochondriacus', family: 'Amaranthaceae', growingDays: 80, difficulty: 'EASY', waterNeeds: 'LOW', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: true, medicinal: false, toxic: false, tags: ['grain', 'pseudo-cereal', 'protein'], minTemp: 15, maxTemp: 38, description: 'Ancient pseudo-cereal with high protein content. Both leaves and seeds are edible.', baseYield: 5, tokensPerHarvest: 12 },
  { commonName: 'Buckwheat', scientificName: 'Fagopyrum esculentum', family: 'Polygonaceae', growingDays: 70, difficulty: 'EASY', waterNeeds: 'LOW', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: true, medicinal: false, toxic: false, tags: ['grain', 'pseudo-cereal'], minTemp: 5, maxTemp: 30, description: 'Fast-growing pseudo-cereal with triangular seeds. Excellent cover crop and pollinator attractant.', baseYield: 4, tokensPerHarvest: 12 },
  { commonName: 'Sesame', scientificName: 'Sesamum indicum', family: 'Pedaliaceae', growingDays: 90, difficulty: 'EASY', waterNeeds: 'LOW', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: true, medicinal: false, toxic: false, tags: ['grain', 'oilseed', 'indian'], minTemp: 18, maxTemp: 38, description: 'Oil-rich seeds used in cooking and baking. Ancient crop with high oil content.', baseYield: 4, tokensPerHarvest: 15 },

  // ═══════════════════════════════════════════════════════════════════════════
  // LEGUMES (15 species)
  // ═══════════════════════════════════════════════════════════════════════════
  { commonName: 'Chickpea', scientificName: 'Cicer arietinum', family: 'Fabaceae', growingDays: 80, difficulty: 'EASY', waterNeeds: 'LOW', sunlightNeeds: 'FULL_SUN', seasons: ['winter', 'spring'], edible: true, medicinal: false, toxic: false, tags: ['legume', 'pulse', 'indian'], minTemp: 5, maxTemp: 30, description: 'Chana — the most important Indian pulse. Used in hummus, curries, and snacks.', baseYield: 5, tokensPerHarvest: 12 },
  { commonName: 'Pigeon Pea', scientificName: 'Cajanus cajan', family: 'Fabaceae', growingDays: 120, difficulty: 'EASY', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: true, medicinal: false, toxic: false, tags: ['legume', 'pulse', 'indian'], minTemp: 15, maxTemp: 38, description: 'Toor dal — essential Indian pulse. Perennial legume that fixes nitrogen in soil.', baseYield: 5, tokensPerHarvest: 12 },
  { commonName: 'Black Gram', scientificName: 'Vigna mungo', family: 'Fabaceae', growingDays: 70, difficulty: 'EASY', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: true, medicinal: false, toxic: false, tags: ['legume', 'pulse', 'indian'], minTemp: 18, maxTemp: 38, description: 'Urad dal — used in dosa batter and dal makhani. High-protein Indian pulse.', baseYield: 5, tokensPerHarvest: 12 },
  { commonName: 'Green Gram', scientificName: 'Vigna radiata', family: 'Fabaceae', growingDays: 55, difficulty: 'EASY', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: true, medicinal: false, toxic: false, tags: ['legume', 'pulse', 'indian'], minTemp: 18, maxTemp: 38, description: 'Moong dal — light, easily digestible pulse. Sprouted for salads and curries.', baseYield: 5, tokensPerHarvest: 12 },
  { commonName: 'Cowpea', scientificName: 'Vigna unguiculata', family: 'Fabaceae', growingDays: 60, difficulty: 'EASY', waterNeeds: 'LOW', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: true, medicinal: false, toxic: false, tags: ['legume', 'pulse'], minTemp: 18, maxTemp: 38, description: 'Lobia — heat-tolerant legume. Both green pods and dried beans are edible.', baseYield: 5, tokensPerHarvest: 10 },
  { commonName: 'Lentil', scientificName: 'Lens culinaris', family: 'Fabaceae', growingDays: 80, difficulty: 'EASY', waterNeeds: 'LOW', sunlightNeeds: 'FULL_SUN', seasons: ['winter', 'spring'], edible: true, medicinal: false, toxic: false, tags: ['legume', 'pulse'], minTemp: -5, maxTemp: 25, description: 'Small lens-shaped pulse. One of the oldest cultivated crops. High in protein and fiber.', baseYield: 5, tokensPerHarvest: 12 },
  { commonName: 'Soybean', scientificName: 'Glycine max', family: 'Fabaceae', growingDays: 90, difficulty: 'MEDIUM', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: true, medicinal: false, toxic: false, tags: ['legume', 'oilseed', 'protein'], minTemp: 15, maxTemp: 35, description: 'Protein-rich legume used for tofu, soy milk, and oil. Fixes nitrogen in soil.', baseYield: 6, tokensPerHarvest: 15 },
  { commonName: 'Groundnut', scientificName: 'Arachis hypogaea', family: 'Fabaceae', growingDays: 90, difficulty: 'EASY', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: true, medicinal: false, toxic: false, tags: ['legume', 'nut', 'oilseed', 'indian'], minTemp: 18, maxTemp: 38, description: 'Peanut — underground legume. High in protein and healthy fats. Important oilseed crop.', baseYield: 5, tokensPerHarvest: 12 },
  { commonName: 'Lima Bean', scientificName: 'Phaseolus lunatus', family: 'Fabaceae', growingDays: 80, difficulty: 'EASY', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: true, medicinal: false, toxic: false, tags: ['legume', 'bean'], minTemp: 15, maxTemp: 30, description: 'Butter bean with flat, large seeds. Creamy texture when cooked.', baseYield: 5, tokensPerHarvest: 10 },
  { commonName: 'Kidney Bean', scientificName: 'Phaseolus vulgaris', family: 'Fabaceae', growingDays: 70, difficulty: 'EASY', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: true, medicinal: false, toxic: false, tags: ['legume', 'bean', 'indian'], minTemp: 15, maxTemp: 30, description: 'Rajma — dark red kidney-shaped bean. Star of rajma curry, a North Indian favorite.', baseYield: 5, tokensPerHarvest: 12 },
  { commonName: 'Black-eyed Pea', scientificName: 'Vigna unguiculata', family: 'Fabaceae', growingDays: 65, difficulty: 'EASY', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: true, medicinal: false, toxic: false, tags: ['legume', 'bean'], minTemp: 18, maxTemp: 38, description: 'Cream-colored bean with distinctive black eye. Important in Southern US and African cuisine.', baseYield: 5, tokensPerHarvest: 10 },
  { commonName: 'Horse Gram', scientificName: 'Macrotyloma uniflorum', family: 'Fabaceae', growingDays: 75, difficulty: 'EASY', waterNeeds: 'LOW', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: true, medicinal: true, toxic: false, tags: ['legume', 'pulse', 'indian', 'medicinal'], minTemp: 15, maxTemp: 40, description: 'Kulthi — drought-resistant pulse with medicinal properties. Used in South Indian soups.', baseYield: 4, tokensPerHarvest: 10 },
  { commonName: 'Cluster Bean', scientificName: 'Cyamopsis tetragonoloba', family: 'Fabaceae', growingDays: 60, difficulty: 'EASY', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: true, medicinal: false, toxic: false, tags: ['legume', 'vegetable', 'indian'], minTemp: 18, maxTemp: 38, description: 'Guar — source of guar gum. Green pods used as vegetable in Indian cooking.', baseYield: 5, tokensPerHarvest: 10 },
  { commonName: 'French Bean', scientificName: 'Phaseolus vulgaris var. vulgaris', family: 'Fabaceae', growingDays: 55, difficulty: 'EASY', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: true, medicinal: false, toxic: false, tags: ['legume', 'vegetable', 'green'], minTemp: 10, maxTemp: 30, description: 'Green snap beans. Tender pods eaten fresh, frozen, or canned. Bush and pole varieties.', baseYield: 5, tokensPerHarvest: 10 },
  { commonName: 'Winged Bean', scientificName: 'Psophocarpus tetragonolobus', family: 'Fabaceae', growingDays: 80, difficulty: 'MEDIUM', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: true, medicinal: false, toxic: false, tags: ['legume', 'tropical', 'protein'], minTemp: 20, maxTemp: 35, description: 'Four-angled tropical bean. Every part is edible — pods, leaves, flowers, tubers, and seeds.', baseYield: 5, tokensPerHarvest: 12 },

  // ═══════════════════════════════════════════════════════════════════════════
  // ADDITIONAL VINES/CLIMBERS (3 species)
  // ═══════════════════════════════════════════════════════════════════════════
  { commonName: 'Rangoon Creeper', scientificName: 'Combretum indicum', family: 'Combretaceae', growingDays: 100, difficulty: 'EASY', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: false, medicinal: false, toxic: false, tags: ['vine', 'ornamental', 'climber', 'fragrant'], minTemp: 12, maxTemp: 38, description: 'Fragrant climber with flowers that change color from white to pink to red. Popular in tropical gardens.', baseYield: 3, tokensPerHarvest: 10 },
  { commonName: 'Madhablati', scientificName: 'Cryptolepis buchananii', family: 'Apocynaceae', growingDays: 100, difficulty: 'EASY', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: false, medicinal: true, toxic: false, tags: ['vine', 'medicinal', 'indian'], minTemp: 12, maxTemp: 38, description: 'Indian climbing shrub used in traditional medicine for skin diseases and joint pain.', baseYield: 3, tokensPerHarvest: 12 },
  { commonName: 'Betel Leaf', scientificName: 'Piper betle', family: 'Piperaceae', growingDays: 90, difficulty: 'MEDIUM', waterNeeds: 'HIGH', sunlightNeeds: 'PARTIAL_SHADE', seasons: ['spring', 'summer'], edible: false, medicinal: true, toxic: false, tags: ['vine', 'leaf', 'indian', 'medicinal'], minTemp: 18, maxTemp: 35, description: 'Heart-shaped leaf used in betel quid across South and Southeast Asia. Climbing vine on support trees.', baseYield: 4, tokensPerHarvest: 15 },

  // ═══════════════════════════════════════════════════════════════════════════
  // ADDITIONAL HERBS & SPICES (3 species)
  // ═══════════════════════════════════════════════════════════════════════════
  { commonName: 'Ajwain', scientificName: 'Trachyspermum ammi', family: 'Apiaceae', growingDays: 50, difficulty: 'EASY', waterNeeds: 'LOW', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: true, medicinal: true, toxic: false, tags: ['spice', 'herb', 'indian', 'medicinal'], minTemp: 15, maxTemp: 35, description: 'Carom seeds with thyme-like flavor. Essential in Indian tempering. Remedy for indigestion.', baseYield: 4, tokensPerHarvest: 12 },
  { commonName: 'Kalpasi', scientificName: 'Murraya koenigii', family: 'Rutaceae', growingDays: 120, difficulty: 'MEDIUM', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: false, medicinal: true, toxic: false, tags: ['spice', 'flower', 'indian'], minTemp: 12, maxTemp: 38, description: 'Stone flower lichen — a spice used in Chettinad and Maharashtrian cooking. Earthy, smoky flavor.', baseYield: 2, tokensPerHarvest: 20 },
  { commonName: 'Kokum', scientificName: 'Garcinia indica', family: 'Clusiaceae', growingDays: 200, difficulty: 'MEDIUM', waterNeeds: 'MODERATE', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: true, medicinal: true, toxic: false, tags: ['fruit', 'spice', 'indian', 'medicinal'], minTemp: 15, maxTemp: 38, description: 'Sour fruit used as a cooling agent in Konkani and Goan cuisine. Rinds dried as amchur substitute.', baseYield: 4, tokensPerHarvest: 18 },

  // ═══════════════════════════════════════════════════════════════════════════
  // ADDITIONAL FRUIT TREES (3 species)
  // ═══════════════════════════════════════════════════════════════════════════
  { commonName: 'Jujube', scientificName: 'Ziziphus mauritiana', family: 'Rhamnaceae', growingDays: 150, difficulty: 'EASY', waterNeeds: 'LOW', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer', 'fall'], edible: true, medicinal: true, toxic: false, tags: ['fruit', 'tree', 'indian', 'medicinal'], minTemp: 0, maxTemp: 42, description: 'Ber — small, sweet-sour fruit. Extremely drought-tolerant tree with medicinal bark.', baseYield: 6, tokensPerHarvest: 18 },
  { commonName: 'Wood Apple', scientificName: 'Feronia limonia', family: 'Rutaceae', growingDays: 180, difficulty: 'MEDIUM', waterNeeds: 'LOW', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: true, medicinal: true, toxic: false, tags: ['fruit', 'tree', 'indian'], minTemp: 10, maxTemp: 42, description: 'Bael — hard-shelled fruit with tangy pulp. Sacred to Lord Shiva. Used in sherbets and medicine.', baseYield: 5, tokensPerHarvest: 15 },
  { commonName: 'Karanja', scientificName: 'Pongamia pinnata', family: 'Fabaceae', growingDays: 180, difficulty: 'EASY', waterNeeds: 'LOW', sunlightNeeds: 'FULL_SUN', seasons: ['spring', 'summer'], edible: false, medicinal: true, toxic: true, tags: ['tree', 'medicinal', 'oil', 'indian'], minTemp: 10, maxTemp: 40, description: 'Indian beech — biofuel and medicinal oil tree. Seeds produce karanja oil for pest control.', baseYield: 6, tokensPerHarvest: 15 },
];
