import 'dotenv/config';
import { PrismaClient } from '@prisma/client';
import { v4 as uuidv4 } from 'uuid';
import * as bcrypt from 'bcrypt';

const prisma = new PrismaClient();

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function daysAgo(days: number): Date {
  const d = new Date();
  d.setDate(d.getDate() - days);
  return d;
}

function hoursAgo(hours: number): Date {
  const d = new Date();
  d.setHours(d.getHours() - hours);
  return d;
}

function randomInt(min: number, max: number): number {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

function randomFloat(min: number, max: number, decimals = 1): number {
  const val = Math.random() * (max - min) + min;
  return parseFloat(val.toFixed(decimals));
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main(): Promise<void> {
  console.log('🌱  GardenVerse Seed\n');

  // -----------------------------------------------------------------------
  // CLEAR existing data (reverse dependency order)
  // -----------------------------------------------------------------------
  console.log('Clearing existing data...');
  const clearOrder = [
    'tokenTransaction', 'appLog', 'session', 'auditLog',
    'userFeatureOverride', 'reputationLog', 'blockchainTransaction',
    'qrSession', 'moderationReport', 'sensorReading', 'iotDevice',
    'marketplaceTransaction', 'marketplaceListing', 'inventory',
    'message', 'groupMember', 'group', 'invite', 'aiScan',
    'notification', 'gardenPlanPlant', 'gardenPlan', 'cropVariety',
    'crop', 'weatherRecord', 'garden', 'plantCollection', 'speciesMastery', 'plantHybrid', 'plantSpecies', 'featureFlag',
    'dailyReward', 'userEnergy', 'userAchievement', 'achievement', 'userPurchase', 'shopItem',
    'user',
  ] as const;

  for (const model of clearOrder) {
    try {
      await (prisma as any)[model].deleteMany();
    } catch {
      // table might not exist yet – skip silently
    }
  }
  console.log('  ✓ Cleared existing data\n');

  // =======================================================================
  // 1. USERS (10)
  // =======================================================================
  console.log('Seeding users...');

  const passwordHash = await bcrypt.hash('Password123', 12);

  const userData = [
    {
      id: uuidv4(),
      email: 'admin@gardenverse.vercel.app',
      username: 'admin',
      displayName: 'Admin Gardener',
      passwordHash,
      role: 'SUPER_ADMIN' as const,
      isVerified: true,
      isOnboarded: true,
      avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=admin',
      bio: 'GardenVerse platform administrator and master gardener since day one.',
      geohash: '9q9h8',
      region: 'US-CA',
      level: 50,
      experience: 25000,
      greenCredits: 10000,
      ecoPoints: 5000,
      reputationTokens: 3000,
      sustainabilityScore: 98.5,
      trustScore: 100,
      marketplaceReliability: 100,
      communityStanding: 100,
      inviteCount: 25,
      currentStreak: 30,
      longestStreak: 60,
      lastActiveAt: hoursAgo(1),
    },
    {
      id: uuidv4(),
      email: 'jane@gardenverse.vercel.app',
      username: 'jane_gardener',
      displayName: 'Jane Gardener',
      passwordHash,
      role: 'MODERATOR' as const,
      isVerified: true,
      isOnboarded: true,
      avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=jane',
      bio: 'Community moderator and organic farming advocate.',
      geohash: '9q9h7',
      region: 'US-CA',
      level: 35,
      experience: 15000,
      greenCredits: 5000,
      ecoPoints: 3500,
      reputationTokens: 2000,
      sustainabilityScore: 92.0,
      trustScore: 98,
      marketplaceReliability: 95,
      communityStanding: 98,
      inviteCount: 15,
      currentStreak: 22,
      longestStreak: 45,
      lastActiveAt: hoursAgo(3),
    },
    {
      id: uuidv4(),
      email: 'alice@gardenverse.vercel.app',
      username: 'alice_green',
      displayName: 'Alice Green',
      passwordHash,
      role: 'USER' as const,
      isVerified: true,
      isOnboarded: true,
      avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=alice',
      bio: 'Premium gardener growing organic vegetables in my backyard.',
      geohash: '9q8zz',
      region: 'US-TX',
      level: 28,
      experience: 9500,
      greenCredits: 15000,
      ecoPoints: 4200,
      reputationTokens: 1800,
      sustainabilityScore: 88.0,
      trustScore: 95,
      marketplaceReliability: 92,
      communityStanding: 90,
      inviteCount: 8,
      currentStreak: 15,
      longestStreak: 30,
      lastActiveAt: hoursAgo(5),
    },
    {
      id: uuidv4(),
      email: 'reggie@gardenverse.vercel.app',
      username: 'reggie_veggie',
      displayName: 'Reggie Veggie',
      passwordHash,
      role: 'USER' as const,
      isVerified: true,
      isOnboarded: true,
      avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=reggie',
      bio: 'Growing my own food one veggie at a time.',
      geohash: 'dr5rs',
      region: 'US-NY',
      level: 15,
      experience: 4200,
      greenCredits: 1200,
      ecoPoints: 1800,
      reputationTokens: 600,
      sustainabilityScore: 72.5,
      trustScore: 88,
      marketplaceReliability: 85,
      communityStanding: 75,
      inviteCount: 3,
      currentStreak: 8,
      longestStreak: 14,
      lastActiveAt: hoursAgo(12),
    },
    {
      id: uuidv4(),
      email: 'guru@gardenverse.vercel.app',
      username: 'guru_garden',
      displayName: 'Guru Garden',
      passwordHash,
      role: 'USER' as const,
      isVerified: true,
      isOnboarded: true,
      avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=guru',
      bio: 'Expert gardener with 20 years of experience. Happy to help!',
      geohash: '9v7y0',
      region: 'US-FL',
      level: 42,
      experience: 19000,
      greenCredits: 8000,
      ecoPoints: 6000,
      reputationTokens: 4500,
      sustainabilityScore: 95.0,
      trustScore: 99,
      marketplaceReliability: 98,
      communityStanding: 97,
      inviteCount: 20,
      currentStreak: 45,
      longestStreak: 90,
      lastActiveAt: hoursAgo(2),
    },
    {
      id: uuidv4(),
      email: 'whisper@gardenverse.vercel.app',
      username: 'plant_whisperer',
      displayName: 'Plant Whisperer',
      passwordHash,
      role: 'USER' as const,
      isVerified: true,
      isOnboarded: true,
      avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=whisper',
      bio: 'I talk to my plants and they talk back. 🌿',
      geohash: '9x8j1',
      region: 'US-OR',
      level: 22,
      experience: 6800,
      greenCredits: 3000,
      ecoPoints: 2500,
      reputationTokens: 1200,
      sustainabilityScore: 82.0,
      trustScore: 90,
      marketplaceReliability: 88,
      communityStanding: 85,
      inviteCount: 6,
      currentStreak: 12,
      longestStreak: 25,
      lastActiveAt: hoursAgo(8),
    },
    {
      id: uuidv4(),
      email: 'thumb@gardenverse.vercel.app',
      username: 'green_thumb',
      displayName: 'Green Thumb',
      passwordHash,
      role: 'USER' as const,
      isVerified: true,
      isOnboarded: true,
      avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=thumb',
      bio: 'Everything I touch turns to green.',
      geohash: '9q5k3',
      region: 'US-WA',
      level: 18,
      experience: 5200,
      greenCredits: 2200,
      ecoPoints: 2000,
      reputationTokens: 900,
      sustainabilityScore: 76.0,
      trustScore: 92,
      marketplaceReliability: 90,
      communityStanding: 82,
      inviteCount: 4,
      currentStreak: 10,
      longestStreak: 20,
      lastActiveAt: hoursAgo(24),
    },
    {
      id: uuidv4(),
      email: 'warrior@gardenverse.vercel.app',
      username: 'eco_warrior',
      displayName: 'Eco Warrior',
      passwordHash,
      role: 'USER' as const,
      isVerified: true,
      isOnboarded: true,
      avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=warrior',
      bio: 'Fighting climate change one garden at a time.',
      geohash: '9q5k3',
      region: 'US-CO',
      level: 30,
      experience: 11000,
      greenCredits: 4500,
      ecoPoints: 8000,
      reputationTokens: 2500,
      sustainabilityScore: 96.0,
      trustScore: 94,
      marketplaceReliability: 91,
      communityStanding: 93,
      inviteCount: 10,
      currentStreak: 18,
      longestStreak: 35,
      lastActiveAt: hoursAgo(6),
    },
    {
      id: uuidv4(),
      email: 'lazy@gardenverse.vercel.app',
      username: 'lazy_gardener',
      displayName: 'Lazy Gardener',
      passwordHash,
      role: 'USER' as const,
      isVerified: false,
      isOnboarded: true,
      avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=lazy',
      bio: 'I tried gardening once.',
      geohash: '9q9h5',
      region: 'US-IL',
      level: 3,
      experience: 450,
      greenCredits: 50,
      ecoPoints: 30,
      reputationTokens: 10,
      sustainabilityScore: 15.0,
      trustScore: 25,
      marketplaceReliability: 20,
      communityStanding: 15,
      inviteCount: 0,
      currentStreak: 0,
      longestStreak: 2,
      lastActiveAt: daysAgo(60),
      deletedAt: daysAgo(30),
    },
    {
      id: uuidv4(),
      email: 'toxic@gardenverse.vercel.app',
      username: 'toxic_grower',
      displayName: 'Toxic Grower',
      passwordHash,
      role: 'USER' as const,
      isVerified: false,
      isOnboarded: false,
      avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=toxic',
      bio: null,
      geohash: null,
      region: null,
      level: 1,
      experience: 100,
      greenCredits: 0,
      ecoPoints: 0,
      reputationTokens: 0,
      sustainabilityScore: 5.0,
      trustScore: 0,
      marketplaceReliability: 0,
      communityStanding: 0,
      inviteCount: 0,
      currentStreak: 0,
      longestStreak: 0,
      lastActiveAt: daysAgo(90),
      deletedAt: daysAgo(45),
    },
  ];

  const createdUsers = await Promise.all(
    userData.map((u) => prisma.user.create({ data: u })),
  );
  const [
    admin,
    jane,
    alice,
    reggie,
    guru,
    whisper,
    thumb,
    warrior,
    lazyUser,
    toxicUser,
  ] = createdUsers;
  console.log(`  ✓ Created ${createdUsers.length} users`);

  // =======================================================================
  // 2. PLANT SPECIES (31)
  // =======================================================================
  console.log('Seeding plant species...');

  const plantSpeciesData = [
    {
      id: uuidv4(),
      commonName: 'Tomato',
      scientificName: 'Solanum lycopersicum',
      family: 'Solanaceae',
      genus: 'Solanum',
      species: 'lycopersicum',
      imageUrl: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=400',
      description: 'A versatile fruit widely used in cooking. Rich in vitamins and antioxidants.',
      growingDays: 70,
      difficulty: 'MEDIUM',
      waterNeeds: 'MODERATE',
      sunlightNeeds: 'FULL_SUN',
      soilPhMin: 6.0,
      soilPhMax: 6.8,
      matureHeightCm: 150,
      spacingCm: 60,
      edible: true,
      medicinal: false,
      attractsPollinators: false,
      isNative: false,
      seasons: ['SPRING', 'SUMMER'],
      tags: ['fruit', 'vegetable', 'popular', 'salad'],
      companionSpeciesIds: ['Ocimum basilicum', 'Tagetes erecta', 'Daucus carota', 'Allium cepa'],
      baseYield: 4,
      tokensPerHarvest: 15,
      growthTimeHours: 1680,
    },
    {
      id: uuidv4(),
      commonName: 'Basil',
      scientificName: 'Ocimum basilicum',
      family: 'Lamiaceae',
      genus: 'Ocimum',
      species: 'basilicum',
      imageUrl: 'https://images.unsplash.com/photo-1618375569909-3e861b4e0a30?w=400',
      description: 'Aromatic herb essential for Italian cuisine. Easy to grow in warm weather.',
      growingDays: 60,
      difficulty: 'EASY',
      waterNeeds: 'MODERATE',
      sunlightNeeds: 'FULL_SUN',
      soilPhMin: 6.0,
      soilPhMax: 7.0,
      matureHeightCm: 60,
      spacingCm: 25,
      edible: true,
      medicinal: true,
      attractsPollinators: false,
      isNative: false,
      seasons: ['SPRING', 'SUMMER'],
      tags: ['herb', 'culinary', 'aromatic', 'companion'],
      companionSpeciesIds: ['Solanum lycopersicum', 'Capsicum annuum'],
      baseYield: 3,
      tokensPerHarvest: 10,
      growthTimeHours: 1440,
    },
    {
      id: uuidv4(),
      commonName: 'Lettuce',
      scientificName: 'Lactuca sativa',
      family: 'Asteraceae',
      genus: 'Lactuca',
      species: 'sativa',
      imageUrl: 'https://images.unsplash.com/photo-1622206151226-18ca2c9ab4a1?w=400',
      description: 'A cool-season leafy green, perfect for salads and sandwiches.',
      growingDays: 50,
      difficulty: 'EASY',
      waterNeeds: 'HIGH',
      sunlightNeeds: 'PARTIAL_SHADE',
      soilPhMin: 6.0,
      soilPhMax: 7.0,
      matureHeightCm: 30,
      spacingCm: 20,
      edible: true,
      medicinal: false,
      attractsPollinators: false,
      isNative: false,
      seasons: ['SPRING', 'FALL'],
      tags: ['leafy', 'salad', 'cool-season', 'quick'],
      companionSpeciesIds: ['Daucus carota', 'Fragaria × ananassa', 'Allium cepa'],
      baseYield: 2,
      tokensPerHarvest: 8,
      growthTimeHours: 1200,
    },
    {
      id: uuidv4(),
      commonName: 'Carrot',
      scientificName: 'Daucus carota',
      family: 'Apiaceae',
      genus: 'Daucus',
      species: 'carota',
      imageUrl: 'https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?w=400',
      description: 'A root vegetable rich in beta-carotene. Grows best in loose, sandy soil.',
      growingDays: 80,
      difficulty: 'MEDIUM',
      waterNeeds: 'MODERATE',
      sunlightNeeds: 'FULL_SUN',
      soilPhMin: 6.0,
      soilPhMax: 6.8,
      matureHeightCm: 45,
      spacingCm: 10,
      edible: true,
      medicinal: false,
      attractsPollinators: false,
      isNative: false,
      seasons: ['SPRING', 'SUMMER', 'FALL'],
      tags: ['root', 'vegetable', 'vitamin', 'storage'],
      companionSpeciesIds: ['Solanum lycopersicum', 'Allium cepa', 'Lactuca sativa'],
      baseYield: 3,
      tokensPerHarvest: 12,
      growthTimeHours: 1920,
    },
    {
      id: uuidv4(),
      commonName: 'Strawberry',
      scientificName: 'Fragaria × ananassa',
      family: 'Rosaceae',
      genus: 'Fragaria',
      species: '× ananassa',
      imageUrl: 'https://images.unsplash.com/photo-1464965911861-746a04b4bca6?w=400',
      description: 'Sweet, juicy berries that are a favorite in gardens worldwide.',
      growingDays: 90,
      difficulty: 'MEDIUM',
      waterNeeds: 'MODERATE',
      sunlightNeeds: 'FULL_SUN',
      soilPhMin: 5.5,
      soilPhMax: 6.5,
      matureHeightCm: 20,
      spacingCm: 30,
      edible: true,
      medicinal: false,
      attractsPollinators: true,
      isNative: false,
      seasons: ['SPRING', 'SUMMER'],
      tags: ['fruit', 'berry', 'sweet', 'perennial'],
      companionSpeciesIds: ['Lactuca sativa', 'Spinacia oleracea', 'Vaccinium corymbosum'],
      baseYield: 3,
      tokensPerHarvest: 18,
      growthTimeHours: 2160,
    },
    {
      id: uuidv4(),
      commonName: 'Sunflower',
      scientificName: 'Helianthus annuus',
      family: 'Asteraceae',
      genus: 'Helianthus',
      species: 'annuus',
      imageUrl: 'https://images.unsplash.com/photo-1597848212624-a19eb35e2651?w=400',
      description: 'Tall, cheerful flowers that follow the sun. Seeds are edible and attract birds.',
      growingDays: 85,
      difficulty: 'EASY',
      waterNeeds: 'LOW',
      sunlightNeeds: 'FULL_SUN',
      soilPhMin: 6.0,
      soilPhMax: 7.5,
      matureHeightCm: 250,
      spacingCm: 45,
      edible: true,
      medicinal: false,
      attractsPollinators: true,
      isNative: true,
      seasons: ['SPRING', 'SUMMER'],
      tags: ['flower', 'tall', 'pollinator', 'ornamental'],
      companionSpeciesIds: ['Cucurbita pepo', 'Zea mays'],
      baseYield: 2,
      tokensPerHarvest: 8,
      growthTimeHours: 2040,
    },
    {
      id: uuidv4(),
      commonName: 'Lavender',
      scientificName: 'Lavandula angustifolia',
      family: 'Lamiaceae',
      genus: 'Lavandula',
      species: 'angustifolia',
      imageUrl: 'https://images.unsplash.com/photo-1589908809146-2f6f5b3f6f6b?w=400',
      description: 'Fragrant perennial herb with calming properties. Drought-tolerant once established.',
      growingDays: 100,
      difficulty: 'HARD',
      waterNeeds: 'LOW',
      sunlightNeeds: 'FULL_SUN',
      soilPhMin: 6.5,
      soilPhMax: 8.0,
      matureHeightCm: 90,
      spacingCm: 60,
      edible: true,
      medicinal: true,
      attractsPollinators: true,
      isNative: false,
      seasons: ['SPRING', 'SUMMER'],
      tags: ['herb', 'fragrant', 'medicinal', 'drought-tolerant'],
      companionSpeciesIds: ['Salvia rosmarinus', 'Thymus vulgaris', 'Tagetes erecta'],
      baseYield: 1,
      tokensPerHarvest: 15,
      growthTimeHours: 2400,
    },
    {
      id: uuidv4(),
      commonName: 'Mint',
      scientificName: 'Mentha spicata',
      family: 'Lamiaceae',
      genus: 'Mentha',
      species: 'spicata',
      imageUrl: 'https://images.unsplash.com/photo-1599946347371-68eb71b16afc?w=400',
      description: 'Vigorous spreading herb with refreshing flavor. Best grown in containers.',
      growingDays: 60,
      difficulty: 'EASY',
      waterNeeds: 'MODERATE',
      sunlightNeeds: 'PARTIAL_SHADE',
      soilPhMin: 6.0,
      soilPhMax: 7.0,
      matureHeightCm: 50,
      spacingCm: 40,
      edible: true,
      medicinal: true,
      attractsPollinators: true,
      isNative: false,
      seasons: ['SPRING', 'SUMMER', 'FALL'],
      tags: ['herb', 'culinary', 'tea', 'invasive-spreader'],
      companionSpeciesIds: ['Brassica oleracea var. italica', 'Solanum lycopersicum'],
      baseYield: 3,
      tokensPerHarvest: 8,
      growthTimeHours: 1440,
    },
    {
      id: uuidv4(),
      commonName: 'Bell Pepper',
      scientificName: 'Capsicum annuum',
      family: 'Solanaceae',
      genus: 'Capsicum',
      species: 'annuum',
      imageUrl: 'https://images.unsplash.com/photo-1563565375-f3f2db3c3c3c?w=400',
      description: 'Colorful sweet peppers rich in vitamin C. Thrives in warm temperatures.',
      growingDays: 75,
      difficulty: 'MEDIUM',
      waterNeeds: 'MODERATE',
      sunlightNeeds: 'FULL_SUN',
      soilPhMin: 6.0,
      soilPhMax: 6.8,
      matureHeightCm: 75,
      spacingCm: 45,
      edible: true,
      medicinal: false,
      attractsPollinators: false,
      isNative: false,
      seasons: ['SPRING', 'SUMMER'],
      tags: ['vegetable', 'colorful', 'vitamin', 'warm-season'],
      companionSpeciesIds: ['Ocimum basilicum', 'Solanum lycopersicum', 'Tagetes erecta'],
      baseYield: 4,
      tokensPerHarvest: 14,
      growthTimeHours: 1800,
    },
    {
      id: uuidv4(),
      commonName: 'Zucchini',
      scientificName: 'Cucurbita pepo',
      family: 'Cucurbitaceae',
      genus: 'Cucurbita',
      species: 'pepo',
      imageUrl: 'https://images.unsplash.com/photo-1579033461380-adb47c3eb938?w=400',
      description: 'Prolific summer squash that produces abundantly. Harvest when small for best flavor.',
      growingDays: 55,
      difficulty: 'EASY',
      waterNeeds: 'HIGH',
      sunlightNeeds: 'FULL_SUN',
      soilPhMin: 6.0,
      soilPhMax: 7.5,
      matureHeightCm: 60,
      spacingCm: 90,
      edible: true,
      medicinal: false,
      attractsPollinators: true,
      isNative: false,
      seasons: ['SUMMER'],
      tags: ['squash', 'prolific', 'warm-season', 'summer'],
      companionSpeciesIds: ['Zea mays', 'Phaseolus vulgaris'],
      baseYield: 5,
      tokensPerHarvest: 12,
      growthTimeHours: 1320,
    },
    // -----------------------------------------------------------------------
    // BROCOLLI
    // -----------------------------------------------------------------------
    {
      id: uuidv4(),
      commonName: 'Broccoli',
      scientificName: 'Brassica oleracea var. italica',
      family: 'Brassicaceae',
      genus: 'Brassica',
      species: 'oleracea var. italica',
      imageUrl: 'https://images.unsplash.com/photo-1584270354949-c26b0d5b4a0c?w=400',
      description: 'A nutrient-rich cruciferous vegetable packed with vitamins C and K. Grows best in cool weather.',
      growingDays: 70,
      difficulty: 'MEDIUM',
      minTemp: 5,
      maxTemp: 25,
      waterNeeds: 'MODERATE',
      sunlightNeeds: 'FULL_SUN',
      soilPhMin: 6.0,
      soilPhMax: 7.0,
      matureHeightCm: 75,
      spacingCm: 45,
      edible: true,
      medicinal: false,
      attractsPollinators: false,
      isNative: false,
      seasons: ['SPRING', 'FALL'],
      tags: ['vegetable', 'brassica', 'cool-season', 'superfood'],
      companionSpeciesIds: ['Solanum lycopersicum', 'Allium cepa'],
      baseYield: 3,
      tokensPerHarvest: 14,
      growthTimeHours: 1680,
    },
    // -----------------------------------------------------------------------
    // SPINACH
    // -----------------------------------------------------------------------
    {
      id: uuidv4(),
      commonName: 'Spinach',
      scientificName: 'Spinacia oleracea',
      family: 'Amaranthaceae',
      genus: 'Spinacia',
      species: 'oleracea',
      imageUrl: 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=400',
      description: 'A fast-growing leafy green rich in iron and vitamins. Perfect for spring and fall gardens.',
      growingDays: 40,
      difficulty: 'EASY',
      minTemp: 2,
      maxTemp: 22,
      waterNeeds: 'HIGH',
      sunlightNeeds: 'PARTIAL_SHADE',
      soilPhMin: 6.0,
      soilPhMax: 7.5,
      matureHeightCm: 30,
      spacingCm: 15,
      edible: true,
      medicinal: false,
      attractsPollinators: false,
      isNative: false,
      seasons: ['SPRING', 'FALL'],
      tags: ['leafy', 'cool-season', 'superfood', 'quick'],
      companionSpeciesIds: ['Fragaria × ananassa', 'Lactuca sativa'],
      baseYield: 2,
      tokensPerHarvest: 7,
      growthTimeHours: 960,
    },
    // -----------------------------------------------------------------------
    // ONION
    // -----------------------------------------------------------------------
    {
      id: uuidv4(),
      commonName: 'Onion',
      scientificName: 'Allium cepa',
      family: 'Amaryllidaceae',
      genus: 'Allium',
      species: 'cepa',
      imageUrl: 'https://images.unsplash.com/photo-1508747703725-719c5f5f6b11?w=400',
      description: 'A staple kitchen vegetable with layers of flavor. Bulbing onions require long days to mature.',
      growingDays: 100,
      difficulty: 'EASY',
      minTemp: 5,
      maxTemp: 28,
      waterNeeds: 'MODERATE',
      sunlightNeeds: 'FULL_SUN',
      soilPhMin: 6.0,
      soilPhMax: 7.0,
      matureHeightCm: 50,
      spacingCm: 15,
      edible: true,
      medicinal: true,
      attractsPollinators: false,
      isNative: false,
      seasons: ['SPRING', 'SUMMER'],
      tags: ['root', 'vegetable', 'culinary', 'storage'],
      companionSpeciesIds: ['Daucus carota', 'Lactuca sativa'],
      baseYield: 3,
      tokensPerHarvest: 10,
      growthTimeHours: 2400,
    },
    // -----------------------------------------------------------------------
    // POTATO
    // -----------------------------------------------------------------------
    {
      id: uuidv4(),
      commonName: 'Potato',
      scientificName: 'Solanum tuberosum',
      family: 'Solanaceae',
      genus: 'Solanum',
      species: 'tuberosum',
      imageUrl: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=400',
      description: 'A versatile tuber crop and global staple food. Grows underground and stores well.',
      growingDays: 90,
      difficulty: 'MEDIUM',
      minTemp: 7,
      maxTemp: 25,
      waterNeeds: 'MODERATE',
      sunlightNeeds: 'FULL_SUN',
      soilPhMin: 5.5,
      soilPhMax: 6.5,
      matureHeightCm: 60,
      spacingCm: 30,
      edible: true,
      medicinal: false,
      attractsPollinators: false,
      isNative: false,
      seasons: ['SPRING', 'SUMMER'],
      tags: ['root', 'tuber', 'staple', 'storage'],
      companionSpeciesIds: ['Zea mays', 'Phaseolus vulgaris'],
      baseYield: 4,
      tokensPerHarvest: 15,
      growthTimeHours: 2160,
    },
    // -----------------------------------------------------------------------
    // SWEET CORN
    // -----------------------------------------------------------------------
    {
      id: uuidv4(),
      commonName: 'Sweet Corn',
      scientificName: 'Zea mays',
      family: 'Poaceae',
      genus: 'Zea',
      species: 'mays',
      imageUrl: 'https://images.unsplash.com/photo-1551754655-cd27e38d2076?w=400',
      description: 'A tall warm-season grain crop with sweet kernels. Part of the Three Sisters planting method.',
      growingDays: 80,
      difficulty: 'MEDIUM',
      minTemp: 10,
      maxTemp: 35,
      waterNeeds: 'HIGH',
      sunlightNeeds: 'FULL_SUN',
      soilPhMin: 5.8,
      soilPhMax: 7.0,
      matureHeightCm: 250,
      spacingCm: 30,
      edible: true,
      medicinal: false,
      attractsPollinators: false,
      isNative: false,
      seasons: ['SUMMER'],
      tags: ['grain', 'tall', 'warm-season', 'three-sisters'],
      companionSpeciesIds: ['Phaseolus vulgaris', 'Cucurbita pepo'],
      baseYield: 3,
      tokensPerHarvest: 12,
      growthTimeHours: 1920,
    },
    // -----------------------------------------------------------------------
    // GREEN BEAN
    // -----------------------------------------------------------------------
    {
      id: uuidv4(),
      commonName: 'Green Bean',
      scientificName: 'Phaseolus vulgaris',
      family: 'Fabaceae',
      genus: 'Phaseolus',
      species: 'vulgaris',
      imageUrl: 'https://images.unsplash.com/photo-1567375698348-5d9d5ae99de0?w=400',
      description: 'A nitrogen-fixing legume that enriches soil. Easy to grow and prolific producers.',
      growingDays: 55,
      difficulty: 'EASY',
      minTemp: 10,
      maxTemp: 30,
      waterNeeds: 'MODERATE',
      sunlightNeeds: 'FULL_SUN',
      soilPhMin: 6.0,
      soilPhMax: 7.0,
      matureHeightCm: 50,
      spacingCm: 20,
      edible: true,
      medicinal: false,
      attractsPollinators: true,
      isNative: false,
      seasons: ['SPRING', 'SUMMER'],
      tags: ['legume', 'climbing', 'nitrogen-fixer', 'warm-season'],
      companionSpeciesIds: ['Zea mays', 'Daucus carota'],
      baseYield: 3,
      tokensPerHarvest: 9,
      growthTimeHours: 1320,
    },
    // -----------------------------------------------------------------------
    // RADISH
    // -----------------------------------------------------------------------
    {
      id: uuidv4(),
      commonName: 'Radish',
      scientificName: 'Raphanus sativus',
      family: 'Brassicaceae',
      genus: 'Raphanus',
      species: 'sativus',
      imageUrl: 'https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?w=400',
      description: 'One of the fastest-growing vegetables. Perfect for beginner gardeners and intercropping.',
      growingDays: 25,
      difficulty: 'EASY',
      minTemp: 2,
      maxTemp: 25,
      waterNeeds: 'MODERATE',
      sunlightNeeds: 'FULL_SUN',
      soilPhMin: 6.0,
      soilPhMax: 7.0,
      matureHeightCm: 15,
      spacingCm: 5,
      edible: true,
      medicinal: false,
      attractsPollinators: false,
      isNative: false,
      seasons: ['SPRING', 'FALL'],
      tags: ['root', 'quick', 'cool-season', 'salad'],
      companionSpeciesIds: ['Lactuca sativa', 'Spinacia oleracea'],
      baseYield: 2,
      tokensPerHarvest: 5,
      growthTimeHours: 600,
    },
    // -----------------------------------------------------------------------
    // ROSEMARY
    // -----------------------------------------------------------------------
    {
      id: uuidv4(),
      commonName: 'Rosemary',
      scientificName: 'Salvia rosmarinus',
      family: 'Lamiaceae',
      genus: 'Salvia',
      species: 'rosmarinus',
      imageUrl: 'https://images.unsplash.com/photo-1512236258305-32fb110fdb01?w=400',
      description: 'An aromatic evergreen herb with needle-like leaves. Drought-tolerant and deer-resistant.',
      growingDays: 90,
      difficulty: 'EASY',
      minTemp: 5,
      maxTemp: 35,
      waterNeeds: 'LOW',
      sunlightNeeds: 'FULL_SUN',
      soilPhMin: 6.0,
      soilPhMax: 8.0,
      matureHeightCm: 120,
      spacingCm: 60,
      edible: true,
      medicinal: true,
      attractsPollinators: true,
      isNative: false,
      seasons: ['SPRING', 'SUMMER'],
      tags: ['herb', 'perennial', 'aromatic', 'drought-tolerant'],
      companionSpeciesIds: ['Salvia officinalis', 'Thymus vulgaris'],
      baseYield: 2,
      tokensPerHarvest: 10,
      growthTimeHours: 2160,
    },
    // -----------------------------------------------------------------------
    // THYME
    // -----------------------------------------------------------------------
    {
      id: uuidv4(),
      commonName: 'Thyme',
      scientificName: 'Thymus vulgaris',
      family: 'Lamiaceae',
      genus: 'Thymus',
      species: 'vulgaris',
      imageUrl: 'https://images.unsplash.com/photo-1599935433002-b7952b1f1b8a?w=400',
      description: 'A low-growing perennial herb with tiny aromatic leaves. Excellent ground cover.',
      growingDays: 80,
      difficulty: 'EASY',
      minTemp: 0,
      maxTemp: 35,
      waterNeeds: 'LOW',
      sunlightNeeds: 'FULL_SUN',
      soilPhMin: 6.0,
      soilPhMax: 8.0,
      matureHeightCm: 25,
      spacingCm: 30,
      edible: true,
      medicinal: true,
      attractsPollinators: true,
      isNative: false,
      seasons: ['SPRING', 'SUMMER'],
      tags: ['herb', 'perennial', 'ground-cover', 'aromatic'],
      companionSpeciesIds: ['Salvia rosmarinus', 'Lavandula angustifolia'],
      baseYield: 2,
      tokensPerHarvest: 7,
      growthTimeHours: 1920,
    },
    // -----------------------------------------------------------------------
    // SAGE
    // -----------------------------------------------------------------------
    {
      id: uuidv4(),
      commonName: 'Sage',
      scientificName: 'Salvia officinalis',
      family: 'Lamiaceae',
      genus: 'Salvia',
      species: 'officinalis',
      imageUrl: 'https://images.unsplash.com/photo-1599935433002-b7952b1f1b8a?w=400',
      description: 'A woody perennial herb with velvety leaves. Used in culinary and medicinal applications.',
      growingDays: 85,
      difficulty: 'MEDIUM',
      minTemp: 5,
      maxTemp: 32,
      waterNeeds: 'LOW',
      sunlightNeeds: 'FULL_SUN',
      soilPhMin: 6.0,
      soilPhMax: 7.0,
      matureHeightCm: 60,
      spacingCm: 45,
      edible: true,
      medicinal: true,
      attractsPollinators: true,
      isNative: false,
      seasons: ['SPRING', 'SUMMER'],
      tags: ['herb', 'perennial', 'medicinal', 'aromatic'],
      companionSpeciesIds: ['Salvia rosmarinus', 'Thymus vulgaris'],
      baseYield: 2,
      tokensPerHarvest: 10,
      growthTimeHours: 2040,
    },
    // -----------------------------------------------------------------------
    // CILANTRO
    // -----------------------------------------------------------------------
    {
      id: uuidv4(),
      commonName: 'Cilantro',
      scientificName: 'Coriandrum sativum',
      family: 'Apiaceae',
      genus: 'Coriandrum',
      species: 'sativum',
      imageUrl: 'https://images.unsplash.com/photo-1618375569909-3e861b4e0a30?w=400',
      description: 'A fast-growing herb with distinct flavor. Both leaves (cilantro) and seeds (coriander) are used.',
      growingDays: 45,
      difficulty: 'EASY',
      minTemp: 5,
      maxTemp: 25,
      waterNeeds: 'MODERATE',
      sunlightNeeds: 'PARTIAL_SHADE',
      soilPhMin: 6.2,
      soilPhMax: 6.8,
      matureHeightCm: 45,
      spacingCm: 15,
      edible: true,
      medicinal: false,
      attractsPollinators: true,
      isNative: false,
      seasons: ['SPRING', 'FALL'],
      tags: ['herb', 'culinary', 'quick', 'cool-season'],
      companionSpeciesIds: ['Solanum lycopersicum', 'Mentha spicata'],
      baseYield: 2,
      tokensPerHarvest: 7,
      growthTimeHours: 1080,
    },
    // -----------------------------------------------------------------------
    // BLUEBERRY
    // -----------------------------------------------------------------------
    {
      id: uuidv4(),
      commonName: 'Blueberry',
      scientificName: 'Vaccinium corymbosum',
      family: 'Ericaceae',
      genus: 'Vaccinium',
      species: 'corymbosum',
      imageUrl: 'https://images.unsplash.com/photo-1498557850523-fd3d118b962e?w=400',
      description: 'A long-lived shrub producing antioxidant-rich berries. Requires acidic soil to thrive.',
      growingDays: 120,
      difficulty: 'HARD',
      minTemp: -10,
      maxTemp: 30,
      waterNeeds: 'HIGH',
      sunlightNeeds: 'FULL_SUN',
      soilPhMin: 4.5,
      soilPhMax: 5.5,
      matureHeightCm: 180,
      spacingCm: 120,
      edible: true,
      medicinal: true,
      attractsPollinators: true,
      isNative: true,
      seasons: ['SPRING', 'SUMMER'],
      tags: ['fruit', 'berry', 'shrub', 'acid-loving'],
      companionSpeciesIds: ['Fragaria × ananassa'],
      baseYield: 3,
      tokensPerHarvest: 20,
      growthTimeHours: 2880,
    },
    // -----------------------------------------------------------------------
    // WATERMELON
    // -----------------------------------------------------------------------
    {
      id: uuidv4(),
      commonName: 'Watermelon',
      scientificName: 'Citrullus lanatus',
      family: 'Cucurbitaceae',
      genus: 'Citrullus',
      species: 'lanatus',
      imageUrl: 'https://images.unsplash.com/photo-1563114771-0f8a1c3f6a3c?w=400',
      description: 'A large, sweet summer fruit that needs plenty of space and warmth to thrive.',
      growingDays: 90,
      difficulty: 'HARD',
      minTemp: 15,
      maxTemp: 38,
      waterNeeds: 'HIGH',
      sunlightNeeds: 'FULL_SUN',
      soilPhMin: 6.0,
      soilPhMax: 7.0,
      matureHeightCm: 30,
      spacingCm: 120,
      edible: true,
      medicinal: false,
      attractsPollinators: true,
      isNative: false,
      seasons: ['SUMMER'],
      tags: ['fruit', 'vine', 'warm-season', 'thirsty'],
      companionSpeciesIds: ['Zea mays', 'Helianthus annuus'],
      baseYield: 2,
      tokensPerHarvest: 25,
      growthTimeHours: 2160,
    },
    // -----------------------------------------------------------------------
    // LEMON
    // -----------------------------------------------------------------------
    {
      id: uuidv4(),
      commonName: 'Lemon',
      scientificName: 'Citrus limon',
      family: 'Rutaceae',
      genus: 'Citrus',
      species: 'limon',
      imageUrl: 'https://images.unsplash.com/photo-1590502593747-42a996133562?w=400',
      description: 'A popular citrus tree that produces tart yellow fruit. Requires warm, frost-free climate.',
      growingDays: 365,
      difficulty: 'EXPERT',
      minTemp: 2,
      maxTemp: 40,
      waterNeeds: 'MODERATE',
      sunlightNeeds: 'FULL_SUN',
      soilPhMin: 5.5,
      soilPhMax: 6.5,
      matureHeightCm: 300,
      spacingCm: 400,
      edible: true,
      medicinal: true,
      attractsPollinators: true,
      isNative: false,
      seasons: ['SPRING', 'SUMMER', 'FALL'],
      tags: ['fruit', 'citrus', 'tree', 'evergreen'],
      companionSpeciesIds: ['Lavandula angustifolia'],
      baseYield: 5,
      tokensPerHarvest: 25,
      growthTimeHours: 8760,
    },
    // -----------------------------------------------------------------------
    // GRAPE
    // -----------------------------------------------------------------------
    {
      id: uuidv4(),
      commonName: 'Grape',
      scientificName: 'Vitis vinifera',
      family: 'Vitaceae',
      genus: 'Vitis',
      species: 'vinifera',
      imageUrl: 'https://images.unsplash.com/photo-1534239697798-120952b76f2b?w=400',
      description: 'A climbing vine grown for its fruit used in wine, juice, and fresh eating. Long-lived perennial.',
      growingDays: 180,
      difficulty: 'EXPERT',
      minTemp: -5,
      maxTemp: 38,
      waterNeeds: 'LOW',
      sunlightNeeds: 'FULL_SUN',
      soilPhMin: 5.5,
      soilPhMax: 7.0,
      matureHeightCm: 300,
      spacingCm: 200,
      edible: true,
      medicinal: true,
      attractsPollinators: true,
      isNative: false,
      seasons: ['SPRING', 'SUMMER', 'FALL'],
      tags: ['fruit', 'vine', 'wine', 'perennial'],
      companionSpeciesIds: ['Ocimum basilicum', 'Mentha spicata'],
      baseYield: 5,
      tokensPerHarvest: 22,
      growthTimeHours: 4320,
    },
    // -----------------------------------------------------------------------
    // MARIGOLD
    // -----------------------------------------------------------------------
    {
      id: uuidv4(),
      commonName: 'Marigold',
      scientificName: 'Tagetes erecta',
      family: 'Asteraceae',
      genus: 'Tagetes',
      species: 'erecta',
      imageUrl: 'https://images.unsplash.com/photo-1585068499486-5d1b6f8a2a3b?w=400',
      description: 'A bright, cheerful flower that repels pests and attracts pollinators. An excellent companion plant.',
      growingDays: 50,
      difficulty: 'EASY',
      minTemp: 5,
      maxTemp: 35,
      waterNeeds: 'LOW',
      sunlightNeeds: 'FULL_SUN',
      soilPhMin: 6.0,
      soilPhMax: 7.5,
      matureHeightCm: 80,
      spacingCm: 25,
      edible: false,
      medicinal: true,
      attractsPollinators: true,
      isNative: false,
      seasons: ['SPRING', 'SUMMER'],
      tags: ['flower', 'companion', 'ornamental', 'pest-repellent'],
      companionSpeciesIds: ['Solanum lycopersicum', 'Capsicum annuum'],
      baseYield: 2,
      tokensPerHarvest: 6,
      growthTimeHours: 1200,
    },
    // -----------------------------------------------------------------------
    // LILY
    // -----------------------------------------------------------------------
    {
      id: uuidv4(),
      commonName: 'Lily',
      scientificName: 'Lilium candidum',
      family: 'Liliaceae',
      genus: 'Lilium',
      species: 'candidum',
      imageUrl: 'https://images.unsplash.com/photo-1490750967868-88aa4f44baee?w=400',
      description: 'An elegant perennial bulb flower with large, fragrant white blooms. A garden classic.',
      growingDays: 90,
      difficulty: 'MEDIUM',
      minTemp: -5,
      maxTemp: 30,
      waterNeeds: 'MODERATE',
      sunlightNeeds: 'PARTIAL_SHADE',
      soilPhMin: 6.0,
      soilPhMax: 7.0,
      matureHeightCm: 100,
      spacingCm: 30,
      edible: false,
      medicinal: false,
      attractsPollinators: true,
      isNative: false,
      seasons: ['SPRING', 'SUMMER'],
      tags: ['flower', 'ornamental', 'perennial', 'bulb'],
      companionSpeciesIds: [],
      baseYield: 1,
      tokensPerHarvest: 8,
      growthTimeHours: 2160,
    },
    // -----------------------------------------------------------------------
    // DAISY
    // -----------------------------------------------------------------------
    {
      id: uuidv4(),
      commonName: 'Daisy',
      scientificName: 'Bellis perennis',
      family: 'Asteraceae',
      genus: 'Bellis',
      species: 'perennis',
      imageUrl: 'https://images.unsplash.com/photo-1490750967868-88aa4f44baee?w=400',
      description: 'A cheerful, hardy perennial flower that brightens any garden. Great for borders and wildflower meadows.',
      growingDays: 60,
      difficulty: 'EASY',
      minTemp: -5,
      maxTemp: 28,
      waterNeeds: 'MODERATE',
      sunlightNeeds: 'FULL_SUN',
      soilPhMin: 6.0,
      soilPhMax: 7.5,
      matureHeightCm: 30,
      spacingCm: 20,
      edible: false,
      medicinal: true,
      attractsPollinators: true,
      isNative: false,
      seasons: ['SPRING', 'SUMMER'],
      tags: ['flower', 'ornamental', 'perennial', 'wildflower'],
      companionSpeciesIds: ['Lactuca sativa', 'Allium cepa'],
      baseYield: 1,
      tokensPerHarvest: 5,
      growthTimeHours: 1440,
    },
    // -----------------------------------------------------------------------
    // ALOE VERA
    // -----------------------------------------------------------------------
    {
      id: uuidv4(),
      commonName: 'Aloe Vera',
      scientificName: 'Aloe barbadensis miller',
      family: 'Asphodelaceae',
      genus: 'Aloe',
      species: 'barbadensis miller',
      imageUrl: 'https://images.unsplash.com/photo-1597225244661-0a1dc0c3e5e1?w=400',
      description: 'A succulent plant with thick, fleshy leaves containing healing gel. Easy indoor or warm climate grower.',
      growingDays: 180,
      difficulty: 'EASY',
      minTemp: 10,
      maxTemp: 40,
      waterNeeds: 'LOW',
      sunlightNeeds: 'FULL_SUN',
      soilPhMin: 6.0,
      soilPhMax: 8.0,
      matureHeightCm: 60,
      spacingCm: 30,
      edible: false,
      medicinal: true,
      attractsPollinators: true,
      isNative: false,
      seasons: ['SUMMER'],
      tags: ['succulent', 'medicinal', 'indoor', 'drought-tolerant'],
      companionSpeciesIds: [],
      baseYield: 1,
      tokensPerHarvest: 12,
      growthTimeHours: 4320,
    },
    // -----------------------------------------------------------------------
    // MUSHROOM
    // -----------------------------------------------------------------------
    {
      id: uuidv4(),
      commonName: 'Mushroom',
      scientificName: 'Agaricus bisporus',
      family: 'Agaricaceae',
      genus: 'Agaricus',
      species: 'bisporus',
      imageUrl: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=400',
      description: 'The common button mushroom. Grows in dark, humid environments on composted material.',
      growingDays: 30,
      difficulty: 'HARD',
      minTemp: 10,
      maxTemp: 25,
      waterNeeds: 'HIGH',
      sunlightNeeds: 'SHADE',
      soilPhMin: 6.0,
      soilPhMax: 7.5,
      matureHeightCm: 10,
      spacingCm: 5,
      edible: true,
      medicinal: false,
      attractsPollinators: false,
      isNative: true,
      seasons: ['SPRING', 'FALL'],
      tags: ['fungus', 'shade', 'edible', 'indoor'],
      companionSpeciesIds: [],
      baseYield: 3,
      tokensPerHarvest: 15,
      growthTimeHours: 720,
    },
    // -----------------------------------------------------------------------
    // TEA PLANT
    // -----------------------------------------------------------------------
    {
      id: uuidv4(),
      commonName: 'Tea Plant',
      scientificName: 'Camellia sinensis',
      family: 'Theaceae',
      genus: 'Camellia',
      species: 'sinensis',
      imageUrl: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400',
      description: 'The plant that produces all true tea (green, black, oolong). A long-lived evergreen shrub.',
      growingDays: 365,
      difficulty: 'EXPERT',
      minTemp: 5,
      maxTemp: 32,
      waterNeeds: 'HIGH',
      sunlightNeeds: 'PARTIAL_SHADE',
      soilPhMin: 4.5,
      soilPhMax: 6.0,
      matureHeightCm: 200,
      spacingCm: 150,
      edible: true,
      medicinal: true,
      attractsPollinators: true,
      isNative: false,
      seasons: ['SPRING', 'SUMMER'],
      tags: ['beverage', 'evergreen', 'shrub', 'perennial'],
      companionSpeciesIds: [],
      baseYield: 2,
      tokensPerHarvest: 20,
      growthTimeHours: 8760,
    },
  ];

  const createdSpecies = await Promise.all(
    plantSpeciesData.map((s) => prisma.plantSpecies.create({ data: s })),
  );
  const [
    tomato,
    basil,
    lettuce,
    carrot,
    strawberry,
    sunflower,
    lavender,
    mint,
    bellPepper,
    zucchini,
  ] = createdSpecies;
  console.log(`  ✓ Created ${createdSpecies.length} plant species`);

  // =======================================================================
  // 3. GARDENS (5)
  // =======================================================================
  console.log('Seeding gardens...');

  const gardenData = [
    {
      id: uuidv4(),
      name: 'Admin\'s Demo Garden',
      type: 'HYBRID' as const,
      description: 'A showcase garden demonstrating all GardenVerse features.',
      soilQuality: 85.0,
      irrigationLevel: 75.0,
      sunlightExposure: 80.0,
      address: '123 Garden St, San Francisco, CA',
      timezone: 'America/Los_Angeles',
      theme: 'cottage',
      decorations: {
        fence: 'wooden',
        pathway: 'stone',
        waterFeature: 'birdbath',
        seating: 'bench',
      },
      userId: admin.id,
    },
    {
      id: uuidv4(),
      name: 'Jane\'s Organic Patch',
      type: 'REAL' as const,
      description: 'Certified organic vegetable garden with companion planting.',
      soilQuality: 90.0,
      irrigationLevel: 65.0,
      sunlightExposure: 90.0,
      address: '456 Organic Ln, Los Angeles, CA',
      timezone: 'America/Los_Angeles',
      theme: 'rustic',
      decorations: {
        fence: 'bamboo',
        pathway: 'gravel',
        compostBin: true,
        greenhouse: false,
      },
      userId: jane.id,
    },
    {
      id: uuidv4(),
      name: 'Alice\'s Zen Garden',
      type: 'VIRTUAL' as const,
      description: 'A peaceful virtual garden inspired by Japanese zen principles.',
      soilQuality: 70.0,
      irrigationLevel: 55.0,
      sunlightExposure: 60.0,
      timezone: 'America/Chicago',
      theme: 'zen',
      decorations: {
        style: 'japanese',
        elements: ['bamboo', 'stone_lantern', 'koi_pond'],
        sandPattern: 'waves',
      },
      userId: alice.id,
    },
    {
      id: uuidv4(),
      name: 'Reggie\'s Veggie Plot',
      type: 'REAL' as const,
      description: 'Small urban backyard garden producing fresh vegetables.',
      soilQuality: 55.0,
      irrigationLevel: 70.0,
      sunlightExposure: 65.0,
      address: '789 Urban Ave, New York, NY',
      timezone: 'America/New_York',
      theme: 'urban',
      decorations: {
        containers: ['pots', 'raised_beds'],
        trellis: true,
        vertical_garden: true,
      },
      userId: reggie.id,
    },
    {
      id: uuidv4(),
      name: 'Guru\'s Greenhouse',
      type: 'HYBRID' as const,
      description: 'Advanced hybrid garden with climate-controlled greenhouse.',
      soilQuality: 95.0,
      irrigationLevel: 85.0,
      sunlightExposure: 95.0,
      address: '321 Tropical Dr, Miami, FL',
      timezone: 'America/New_York',
      theme: 'modern',
      decorations: {
        greenhouse: 'glass',
        hydroponics: true,
        automated_irrigation: true,
        climate_control: true,
      },
      userId: guru.id,
    },
  ];

  const createdGardens = await Promise.all(
    gardenData.map((g) => prisma.garden.create({ data: g })),
  );
  const [adminGarden, janeGarden, aliceGarden, reggieGarden, guruGarden] =
    createdGardens;
  console.log(`  ✓ Created ${createdGardens.length} gardens`);

  // =======================================================================
  // 4. CROPS (15 across gardens)
  // =======================================================================
  console.log('Seeding crops...');

  const cropData = [
    // Admin's garden (3 crops)
    {
      id: uuidv4(),
      name: 'Cherry Tomato',
      species: 'Solanum lycopersicum',
      status: 'MATURE' as const,
      growthStage: 4,
      health: 92.0,
      hydration: 75.0,
      nutrientLevel: 80.0,
      plantedAt: daysAgo(60),
      lastWateredAt: hoursAgo(6),
      lastFertilizedAt: daysAgo(7),
      estimatedHarvest: daysAgo(-5),
      plotX: 0,
      plotY: 0,
      speciesId: tomato.id,
      gardenId: adminGarden.id,
      userId: admin.id,
    },
    {
      id: uuidv4(),
      name: 'Sweet Basil',
      species: 'Ocimum basilicum',
      status: 'GROWING' as const,
      growthStage: 2,
      health: 78.0,
      hydration: 60.0,
      nutrientLevel: 55.0,
      plantedAt: daysAgo(20),
      lastWateredAt: hoursAgo(12),
      lastFertilizedAt: daysAgo(10),
      estimatedHarvest: daysAgo(-25),
      plotX: 0,
      plotY: 1,
      speciesId: basil.id,
      gardenId: adminGarden.id,
      userId: admin.id,
    },
    {
      id: uuidv4(),
      name: 'Green Oak Lettuce',
      species: 'Lactuca sativa',
      status: 'HARVESTED' as const,
      growthStage: 5,
      health: 88.0,
      hydration: 70.0,
      nutrientLevel: 65.0,
      plantedAt: daysAgo(45),
      lastWateredAt: hoursAgo(8),
      lastFertilizedAt: daysAgo(14),
      estimatedHarvest: daysAgo(-2),
      harvestedAt: daysAgo(2),
      plotX: 1,
      plotY: 0,
      speciesId: lettuce.id,
      gardenId: adminGarden.id,
      userId: admin.id,
    },
    // Jane's garden (3 crops)
    {
      id: uuidv4(),
      name: 'Butterhead Lettuce',
      species: 'Lactuca sativa',
      status: 'MATURE' as const,
      growthStage: 4,
      health: 95.0,
      hydration: 80.0,
      nutrientLevel: 85.0,
      plantedAt: daysAgo(40),
      lastWateredAt: hoursAgo(4),
      lastFertilizedAt: daysAgo(5),
      estimatedHarvest: daysAgo(-2),
      plotX: 0,
      plotY: 0,
      speciesId: lettuce.id,
      gardenId: janeGarden.id,
      userId: jane.id,
    },
    {
      id: uuidv4(),
      name: 'Nantes Carrot',
      species: 'Daucus carota',
      status: 'SPROUTING' as const,
      growthStage: 1,
      health: 82.0,
      hydration: 65.0,
      nutrientLevel: 70.0,
      plantedAt: daysAgo(14),
      lastWateredAt: hoursAgo(10),
      lastFertilizedAt: daysAgo(7),
      estimatedHarvest: daysAgo(-66),
      plotX: 1,
      plotY: 0,
      speciesId: carrot.id,
      gardenId: janeGarden.id,
      userId: jane.id,
    },
    {
      id: uuidv4(),
      name: 'June-bearing Strawberry',
      species: 'Fragaria × ananassa',
      status: 'GROWING' as const,
      growthStage: 2,
      health: 70.0,
      hydration: 55.0,
      nutrientLevel: 60.0,
      plantedAt: daysAgo(30),
      lastWateredAt: hoursAgo(24),
      lastFertilizedAt: daysAgo(14),
      estimatedHarvest: daysAgo(-45),
      plotX: 2,
      plotY: 0,
      speciesId: strawberry.id,
      gardenId: janeGarden.id,
      userId: jane.id,
    },
    // Alice's garden (3 crops)
    {
      id: uuidv4(),
      name: 'Mammoth Sunflower',
      species: 'Helianthus annuus',
      status: 'MATURE' as const,
      growthStage: 4,
      health: 90.0,
      hydration: 45.0,
      nutrientLevel: 50.0,
      plantedAt: daysAgo(75),
      lastWateredAt: daysAgo(3),
      lastFertilizedAt: daysAgo(20),
      estimatedHarvest: daysAgo(-5),
      plotX: 0,
      plotY: 0,
      speciesId: sunflower.id,
      gardenId: aliceGarden.id,
      userId: alice.id,
    },
    {
      id: uuidv4(),
      name: 'English Lavender',
      species: 'Lavandula angustifolia',
      status: 'SEED' as const,
      growthStage: 0,
      health: 60.0,
      hydration: 30.0,
      nutrientLevel: 25.0,
      plantedAt: daysAgo(7),
      lastWateredAt: daysAgo(2),
      estimatedHarvest: daysAgo(-93),
      plotX: 1,
      plotY: 0,
      speciesId: lavender.id,
      gardenId: aliceGarden.id,
      userId: alice.id,
    },
    {
      id: uuidv4(),
      name: 'Spearmint',
      species: 'Mentha spicata',
      status: 'GROWING' as const,
      growthStage: 2,
      health: 85.0,
      hydration: 75.0,
      nutrientLevel: 70.0,
      plantedAt: daysAgo(25),
      lastWateredAt: hoursAgo(6),
      lastFertilizedAt: daysAgo(10),
      estimatedHarvest: daysAgo(-30),
      plotX: 2,
      plotY: 0,
      speciesId: mint.id,
      gardenId: aliceGarden.id,
      userId: alice.id,
    },
    // Reggie's garden (3 crops)
    {
      id: uuidv4(),
      name: 'Red Bell Pepper',
      species: 'Capsicum annuum',
      status: 'SPROUTING' as const,
      growthStage: 1,
      health: 65.0,
      hydration: 50.0,
      nutrientLevel: 45.0,
      plantedAt: daysAgo(10),
      lastWateredAt: hoursAgo(18),
      lastFertilizedAt: daysAgo(5),
      estimatedHarvest: daysAgo(-65),
      plotX: 0,
      plotY: 0,
      speciesId: bellPepper.id,
      gardenId: reggieGarden.id,
      userId: reggie.id,
    },
    {
      id: uuidv4(),
      name: 'Black Beauty Zucchini',
      species: 'Cucurbita pepo',
      status: 'GROWING' as const,
      growthStage: 2,
      health: 72.0,
      hydration: 65.0,
      nutrientLevel: 55.0,
      plantedAt: daysAgo(22),
      lastWateredAt: hoursAgo(8),
      lastFertilizedAt: daysAgo(7),
      estimatedHarvest: daysAgo(-28),
      plotX: 1,
      plotY: 0,
      speciesId: zucchini.id,
      gardenId: reggieGarden.id,
      userId: reggie.id,
    },
    {
      id: uuidv4(),
      name: 'Roma Tomato',
      species: 'Solanum lycopersicum',
      status: 'WILTED' as const,
      growthStage: 4,
      health: 15.0,
      hydration: 10.0,
      nutrientLevel: 5.0,
      plantedAt: daysAgo(65),
      lastWateredAt: daysAgo(14),
      lastFertilizedAt: daysAgo(30),
      estimatedHarvest: daysAgo(-2),
      weatherStressed: true,
      stressFactor: 0.85,
      plotX: 2,
      plotY: 0,
      speciesId: tomato.id,
      gardenId: reggieGarden.id,
      userId: reggie.id,
    },
    // Guru's garden (3 crops)
    {
      id: uuidv4(),
      name: 'Danvers Carrot',
      species: 'Daucus carota',
      status: 'HARVESTED' as const,
      growthStage: 5,
      health: 98.0,
      hydration: 80.0,
      nutrientLevel: 90.0,
      plantedAt: daysAgo(78),
      lastWateredAt: hoursAgo(4),
      lastFertilizedAt: daysAgo(3),
      estimatedHarvest: daysAgo(-5),
      harvestedAt: daysAgo(1),
      plotX: 0,
      plotY: 0,
      speciesId: carrot.id,
      gardenId: guruGarden.id,
      userId: guru.id,
    },
    {
      id: uuidv4(),
      name: 'Genovese Basil',
      species: 'Ocimum basilicum',
      status: 'MATURE' as const,
      growthStage: 4,
      health: 95.0,
      hydration: 75.0,
      nutrientLevel: 85.0,
      plantedAt: daysAgo(50),
      lastWateredAt: hoursAgo(3),
      lastFertilizedAt: daysAgo(4),
      estimatedHarvest: daysAgo(-5),
      plotX: 1,
      plotY: 0,
      speciesId: basil.id,
      gardenId: guruGarden.id,
      userId: guru.id,
    },
    {
      id: uuidv4(),
      name: 'Albion Strawberry',
      species: 'Fragaria × ananassa',
      status: 'GROWING' as const,
      growthStage: 3,
      health: 88.0,
      hydration: 72.0,
      nutrientLevel: 78.0,
      plantedAt: daysAgo(40),
      lastWateredAt: hoursAgo(5),
      lastFertilizedAt: daysAgo(6),
      estimatedHarvest: daysAgo(-40),
      plotX: 2,
      plotY: 0,
      speciesId: strawberry.id,
      gardenId: guruGarden.id,
      userId: guru.id,
    },
    {
      id: uuidv4(),
      name: 'Iceberg Lettuce',
      species: 'Lactuca sativa',
      status: 'SEED' as const,
      growthStage: 0,
      health: 100.0,
      hydration: 80.0,
      nutrientLevel: 70.0,
      plantedAt: daysAgo(3),
      lastWateredAt: hoursAgo(12),
      estimatedHarvest: daysAgo(-47),
      plotX: 3,
      plotY: 0,
      speciesId: lettuce.id,
      gardenId: guruGarden.id,
      userId: guru.id,
    },
  ];

  const createdCrops = await Promise.all(
    cropData.map((c) => prisma.crop.create({ data: c })),
  );
  const [
    // Admin's
    _adminTomato,
    _adminBasil,
    _adminLettuce,
    // Jane's
    janeLettuce,
    janeCarrot,
    janeStrawberry,
    // Alice's
    aliceSunflower,
    aliceLavender,
    aliceMint,
    // Reggie's
    reggiePepper,
    reggieZucchini,
    reggieTomato,
    // Guru's
    guruCarrot,
    guruBasil,
    guruStrawberry,
    guruLettuce,
  ] = createdCrops;
  console.log(`  ✓ Created ${createdCrops.length} crops`);

  // =======================================================================
  // 5. MARKETPLACE LISTINGS (5)
  // =======================================================================
  console.log('Seeding marketplace listings...');

  const listingsData = [
    {
      id: uuidv4(),
      title: 'Premium Roma Tomatoes',
      description: 'Homegrown organic Roma tomatoes. Perfect for sauces and canning.',
      category: 'vegetables',
      price: 5.99,
      currency: 'GREEN_CREDITS',
      quantity: 10,
      status: 'ACTIVE' as const,
      images: ['https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=400'],
      location: 'San Francisco, CA',
      isLocal: true,
      sellerId: alice.id,
      expiresAt: daysAgo(-30),
    },
    {
      id: uuidv4(),
      title: 'Fresh Basil Bunch',
      description: 'Hand-picked sweet basil, great for pesto and Italian dishes.',
      category: 'herbs',
      price: 2.5,
      currency: 'GREEN_CREDITS',
      quantity: 5,
      status: 'ACTIVE' as const,
      images: ['https://images.unsplash.com/photo-1618375569909-3e861b4e0a30?w=400'],
      location: 'New York, NY',
      isLocal: true,
      sellerId: reggie.id,
      expiresAt: daysAgo(-14),
    },
    {
      id: uuidv4(),
      title: 'Organic Carrots (1 lb)',
      description: 'Sweet, crunchy organic carrots freshly harvested.',
      category: 'vegetables',
      price: 3.99,
      currency: 'GREEN_CREDITS',
      quantity: 1,
      status: 'SOLD' as const,
      images: ['https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?w=400'],
      location: 'Miami, FL',
      isLocal: false,
      sellerId: guru.id,
      expiresAt: daysAgo(-5),
    },
    {
      id: uuidv4(),
      title: 'Strawberry Plant Starters',
      description: 'Ever-bearing strawberry plant starters, ready to transplant.',
      category: 'plants',
      price: 4.0,
      currency: 'GREEN_CREDITS',
      quantity: 6,
      status: 'ACTIVE' as const,
      images: ['https://images.unsplash.com/photo-1464965911861-746a04b4bca6?w=400'],
      location: 'Los Angeles, CA',
      isLocal: true,
      sellerId: jane.id,
      expiresAt: daysAgo(-21),
    },
    {
      id: uuidv4(),
      title: 'Dried Lavender Sachets',
      description: 'Hand-crafted dried lavender sachets. Perfect for drawers and closets.',
      category: 'crafts',
      price: 6.0,
      currency: 'GREEN_CREDITS',
      quantity: 3,
      status: 'EXPIRED' as const,
      images: ['https://images.unsplash.com/photo-1589908809146-2f6f5b3f6f6b?w=400'],
      location: 'Austin, TX',
      isLocal: false,
      sellerId: alice.id,
      expiresAt: daysAgo(10),
    },
  ];

  const createdListings = await Promise.all(
    listingsData.map((l) => prisma.marketplaceListing.create({ data: l })),
  );
  console.log(`  ✓ Created ${createdListings.length} marketplace listings`);

  // =======================================================================
  // 6. COMMUNITY GROUPS (5)
  // =======================================================================
  console.log('Seeding community groups...');

  const groupData = [
    {
      id: uuidv4(),
      name: 'Organic Farmers Collective',
      description:
        'A community for organic farmers to share tips, resources, and best practices for chemical-free gardening.',
      type: 'organic-farming',
      region: 'US-CA',
      isPrivate: false,
      iconUrl: 'https://api.dicebear.com/7.x/icons/svg?seed=organic',
    },
    {
      id: uuidv4(),
      name: 'Urban Gardeners United',
      description:
        'For city dwellers who grow food in small spaces — balconies, rooftops, and community plots.',
      type: 'urban-gardening',
      region: 'US-NY',
      isPrivate: false,
      iconUrl: 'https://api.dicebear.com/7.x/icons/svg?seed=urban',
    },
    {
      id: uuidv4(),
      name: 'Compost Club',
      description:
        'Everything compost! From worm bins to hot composting, share your black gold tips here.',
      type: 'compost-club',
      region: null,
      isPrivate: false,
      iconUrl: 'https://api.dicebear.com/7.x/icons/svg?seed=compost',
    },
    {
      id: uuidv4(),
      name: 'Seed Swap Society',
      description:
        'Trade heirloom and open-pollinated seeds with gardeners worldwide. Member-only marketplace.',
      type: 'seed-swap',
      region: null,
      isPrivate: true,
      iconUrl: 'https://api.dicebear.com/7.x/icons/svg?seed=seedswap',
    },
    {
      id: uuidv4(),
      name: 'Hydro Homies',
      description:
        'Dedicated to hydroponic and aquaponic growing systems. DIY setups welcome!',
      type: 'hydroponics',
      region: null,
      isPrivate: false,
      iconUrl: 'https://api.dicebear.com/7.x/icons/svg?seed=hydro',
    },
  ];

  const createdGroups = await Promise.all(
    groupData.map((g) => prisma.group.create({ data: g })),
  );
  const [organicGroup, urbanGroup, compostGroup, seedSwapGroup, hydroGroup] =
    createdGroups;
  console.log(`  ✓ Created ${createdGroups.length} groups`);

  // Group memberships
  const groupMemberData = [
    { groupId: organicGroup.id, userId: admin.id, role: 'ADMIN' },
    { groupId: organicGroup.id, userId: jane.id, role: 'MODERATOR' },
    { groupId: organicGroup.id, userId: alice.id, role: 'MEMBER' },
    { groupId: organicGroup.id, userId: guru.id, role: 'MEMBER' },
    { groupId: organicGroup.id, userId: whisper.id, role: 'MEMBER' },

    { groupId: urbanGroup.id, userId: reggie.id, role: 'ADMIN' },
    { groupId: urbanGroup.id, userId: alice.id, role: 'MEMBER' },
    { groupId: urbanGroup.id, userId: thumb.id, role: 'MEMBER' },
    { groupId: urbanGroup.id, userId: warrior.id, role: 'MEMBER' },

    { groupId: compostGroup.id, userId: warrior.id, role: 'ADMIN' },
    { groupId: compostGroup.id, userId: guru.id, role: 'MEMBER' },
    { groupId: compostGroup.id, userId: jane.id, role: 'MEMBER' },
    { groupId: compostGroup.id, userId: whisper.id, role: 'MEMBER' },

    { groupId: seedSwapGroup.id, userId: guru.id, role: 'ADMIN' },
    { groupId: seedSwapGroup.id, userId: admin.id, role: 'MEMBER' },
    { groupId: seedSwapGroup.id, userId: alice.id, role: 'MEMBER' },
    { groupId: seedSwapGroup.id, userId: jane.id, role: 'MEMBER' },
    { groupId: seedSwapGroup.id, userId: reggie.id, role: 'MEMBER' },

    { groupId: hydroGroup.id, userId: alice.id, role: 'ADMIN' },
    { groupId: hydroGroup.id, userId: guru.id, role: 'MEMBER' },
    { groupId: hydroGroup.id, userId: thumb.id, role: 'MEMBER' },
    { groupId: hydroGroup.id, userId: warrior.id, role: 'MEMBER' },
  ];

  await Promise.all(
    groupMemberData.map((gm) =>
      prisma.groupMember.create({
        data: {
          id: uuidv4(),
          groupId: gm.groupId,
          userId: gm.userId,
          role: gm.role,
        },
      }),
    ),
  );
  console.log(`  ✓ Created ${groupMemberData.length} group memberships`);

  // =======================================================================
  // 7. CHAT MESSAGES (20 across groups)
  // =======================================================================
  console.log('Seeding chat messages...');

  const messageData = [
    // Organic Farmers (5)
    {
      content: 'Welcome everyone to the Organic Farmers Collective! Let\'s share our best organic pest control methods.',
      senderId: admin.id,
      groupId: organicGroup.id,
      createdAt: daysAgo(14),
    },
    {
      content: 'I\'ve been using neem oil spray with great results against aphids. Mix 1 tsp per liter of water.',
      senderId: guru.id,
      groupId: organicGroup.id,
      createdAt: daysAgo(13),
    },
    {
      content: 'Has anyone tried companion planting with marigolds? They really help keep nematodes away.',
      senderId: jane.id,
      groupId: organicGroup.id,
      createdAt: daysAgo(12),
    },
    {
      content: 'Yes! I plant marigolds around all my tomato beds. Works like a charm.',
      senderId: alice.id,
      groupId: organicGroup.id,
      createdAt: daysAgo(11),
    },
    {
      content: 'Don\'t forget about diatomaceous earth for slug control. Food grade only!',
      senderId: whisper.id,
      groupId: organicGroup.id,
      createdAt: daysAgo(10),
    },
    // Urban Gardeners (4)
    {
      content: 'Just harvested my first balcony crop of cherry tomatoes! So rewarding.',
      senderId: reggie.id,
      groupId: urbanGroup.id,
      createdAt: daysAgo(9),
    },
    {
      content: 'Congrats! What variety did you grow? I recommend Tumbling Tom for small spaces.',
      senderId: alice.id,
      groupId: urbanGroup.id,
      createdAt: daysAgo(9),
    },
    {
      content: 'My vertical strawberry tower is going crazy this season. Perfect for small spaces!',
      senderId: thumb.id,
      groupId: urbanGroup.id,
      createdAt: daysAgo(8),
    },
    {
      content: 'Anyone know where to get good quality potting soil in bulk for rooftop gardens?',
      senderId: warrior.id,
      groupId: urbanGroup.id,
      createdAt: daysAgo(7),
    },
    // Compost Club (4)
    {
      content: 'My compost pile hit 140°F today! Perfect hot compost temperatures.',
      senderId: warrior.id,
      groupId: compostGroup.id,
      createdAt: daysAgo(6),
    },
    {
      content: 'Nice! Remember to turn it every 3 days to keep the aerobic bacteria happy.',
      senderId: guru.id,
      groupId: compostGroup.id,
      createdAt: daysAgo(6),
    },
    {
      content: 'I just started a worm bin. Any tips for keeping the red wigglers healthy?',
      senderId: whisper.id,
      groupId: compostGroup.id,
      createdAt: daysAgo(5),
    },
    {
      content: 'Keep bedding moist like a wrung-out sponge, and bury food scraps to prevent fruit flies.',
      senderId: jane.id,
      groupId: compostGroup.id,
      createdAt: daysAgo(5),
    },
    // Seed Swap Society (4)
    {
      content: 'I have extra heirloom tomato seeds: Brandywine, Cherokee Purple, and San Marzano. DM me for trades!',
      senderId: guru.id,
      groupId: seedSwapGroup.id,
      createdAt: daysAgo(4),
    },
    {
      content: 'Would love to trade some of my Thai basil seeds for your Brandywine!',
      senderId: alice.id,
      groupId: seedSwapGroup.id,
      createdAt: daysAgo(4),
    },
    {
      content: 'Just posted my seed catalog in the marketplace. Over 30 varieties available!',
      senderId: reggie.id,
      groupId: seedSwapGroup.id,
      createdAt: daysAgo(3),
    },
    {
      content: 'Remember to label everything with date and variety. I learned that the hard way!',
      senderId: jane.id,
      groupId: seedSwapGroup.id,
      createdAt: daysAgo(3),
    },
    // Hydro Homies (3)
    {
      content: 'My new NFT system is up and running. Lettuce growth is incredible!',
      senderId: alice.id,
      groupId: hydroGroup.id,
      createdAt: daysAgo(2),
    },
    {
      content: 'NFT is great for leafy greens. For fruiting plants try deep water culture instead.',
      senderId: guru.id,
      groupId: hydroGroup.id,
      createdAt: daysAgo(2),
    },
    {
      content: 'Just built a DIY hydroponic tower from PVC pipes. Cost me under $50!',
      senderId: thumb.id,
      groupId: hydroGroup.id,
      createdAt: daysAgo(1),
    },
  ];

  const createdMessages = await Promise.all(
    messageData.map((m) =>
      prisma.message.create({
        data: {
          id: uuidv4(),
          content: m.content,
          isEncrypted: false,
          senderId: m.senderId,
          groupId: m.groupId,
          createdAt: m.createdAt,
        },
      }),
    ),
  );
  console.log(`  ✓ Created ${createdMessages.length} chat messages`);

  // =======================================================================
  // 8. WEATHER RECORDS (7)
  // =======================================================================
  console.log('Seeding weather records...');

  const weatherData = [
    {
      id: uuidv4(),
      region: 'US-CA-SanFrancisco',
      temperature: 22.5,
      humidity: 65.0,
      rainfall: 0.0,
      windSpeed: 12.0,
      sunlightHours: 10.5,
      condition: 'PARTLY_CLOUDY',
      forecast: {
        summary: 'Mild with partial clouds',
        high: 24,
        low: 14,
        next7Days: [
          { day: 'Mon', condition: 'Sunny', high: 25, low: 15 },
          { day: 'Tue', condition: 'Partly Cloudy', high: 23, low: 14 },
          { day: 'Wed', condition: 'Foggy Morning', high: 22, low: 13 },
          { day: 'Thu', condition: 'Sunny', high: 26, low: 16 },
          { day: 'Fri', condition: 'Sunny', high: 27, low: 16 },
          { day: 'Sat', condition: 'Cloudy', high: 21, low: 12 },
          { day: 'Sun', condition: 'Rain', high: 18, low: 11 },
        ],
      },
      recordedAt: hoursAgo(1),
      expiresAt: hoursAgo(3),
    },
    {
      id: uuidv4(),
      region: 'US-TX-Austin',
      temperature: 34.0,
      humidity: 45.0,
      rainfall: 0.0,
      windSpeed: 8.0,
      sunlightHours: 13.0,
      condition: 'SUNNY',
      forecast: {
        summary: 'Hot and dry',
        high: 36,
        low: 22,
        heatwave: true,
      },
      recordedAt: hoursAgo(2),
      expiresAt: hoursAgo(3),
    },
    {
      id: uuidv4(),
      region: 'US-NY-NewYork',
      temperature: 18.0,
      humidity: 72.0,
      rainfall: 2.5,
      windSpeed: 20.0,
      sunlightHours: 4.0,
      condition: 'RAINY',
      forecast: {
        summary: 'Rain continuing through the week',
        high: 20,
        low: 12,
        precipitation: '80%',
      },
      recordedAt: hoursAgo(3),
      expiresAt: hoursAgo(3),
    },
    {
      id: uuidv4(),
      region: 'US-FL-Miami',
      temperature: 30.5,
      humidity: 80.0,
      rainfall: 0.0,
      windSpeed: 15.0,
      sunlightHours: 11.0,
      condition: 'PARTLY_CLOUDY',
      forecast: {
        summary: 'Humid with afternoon thunderstorms likely',
        high: 32,
        low: 24,
        thunderstorm: true,
      },
      recordedAt: hoursAgo(4),
      expiresAt: hoursAgo(3),
    },
    {
      id: uuidv4(),
      region: 'US-OR-Portland',
      temperature: 14.0,
      humidity: 78.0,
      rainfall: 8.0,
      windSpeed: 10.0,
      sunlightHours: 3.0,
      condition: 'RAINY',
      forecast: {
        summary: 'Persistent rain, flooding possible in low areas',
        high: 16,
        low: 8,
        floodAdvisory: true,
      },
      recordedAt: hoursAgo(5),
      expiresAt: hoursAgo(3),
    },
    {
      id: uuidv4(),
      region: 'US-CO-Denver',
      temperature: 26.0,
      humidity: 25.0,
      rainfall: 0.0,
      windSpeed: 25.0,
      sunlightHours: 12.0,
      condition: 'SUNNY',
      forecast: {
        summary: 'Dry and windy, fire danger elevated',
        high: 28,
        low: 10,
        fireDanger: 'HIGH',
      },
      recordedAt: hoursAgo(6),
      expiresAt: hoursAgo(3),
    },
    {
      id: uuidv4(),
      region: 'US-IL-Chicago',
      temperature: 10.0,
      humidity: 55.0,
      rainfall: 0.0,
      windSpeed: 30.0,
      sunlightHours: 7.0,
      condition: 'WINDY',
      forecast: {
        summary: 'Cold front moving through, temperatures dropping',
        high: 12,
        low: 2,
        windChill: -2,
      },
      recordedAt: hoursAgo(7),
      expiresAt: hoursAgo(3),
    },
  ];

  const createdWeatherRecords = await Promise.all(
    weatherData.map((w) => prisma.weatherRecord.create({ data: w })),
  );
  console.log(`  ✓ Created ${createdWeatherRecords.length} weather records`);

  // =======================================================================
  // 9. AI SCAN RECORDS (10)
  // =======================================================================
  console.log('Seeding AI scan records...');

  const scanData = [
    {
      id: uuidv4(),
      imageUrl: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=400',
      plantName: 'Tomato',
      species: 'Solanum lycopersicum',
      healthScore: 92.0,
      diseases: [
        {
          name: 'Early Blight',
          confidence: 0.03,
          severity: 'none',
        },
        {
          name: 'Healthy Leaf',
          confidence: 0.95,
          severity: 'none',
        },
      ],
      recommendations: [
        'Plant looks healthy, continue regular care',
        'Maintain consistent watering schedule',
        'Apply balanced fertilizer every 2 weeks',
      ],
      userId: admin.id,
      createdAt: daysAgo(5),
    },
    {
      id: uuidv4(),
      imageUrl: 'https://images.unsplash.com/photo-1618375569909-3e861b4e0a30?w=400',
      plantName: 'Basil',
      species: 'Ocimum basilicum',
      healthScore: 85.0,
      diseases: [
        {
          name: 'Downy Mildew',
          confidence: 0.08,
          severity: 'low',
        },
        {
          name: 'Healthy Leaf',
          confidence: 0.88,
          severity: 'none',
        },
      ],
      recommendations: [
        'Minor signs of possible downy mildew',
        'Improve air circulation around plants',
        'Water at soil level, avoid wetting leaves',
      ],
      userId: jane.id,
      createdAt: daysAgo(4),
    },
    {
      id: uuidv4(),
      imageUrl: 'https://images.unsplash.com/photo-1622206151226-18ca2c9ab4a1?w=400',
      plantName: 'Lettuce',
      species: 'Lactuca sativa',
      healthScore: 78.0,
      diseases: [
        {
          name: 'Tip Burn',
          confidence: 0.65,
          severity: 'moderate',
        },
        {
          name: 'Healthy Leaf',
          confidence: 0.30,
          severity: 'none',
        },
      ],
      recommendations: [
        'Tip burn detected — likely calcium deficiency',
        'Add calcium supplement to watering routine',
        'Maintain consistent moisture levels',
        'Consider shade cloth during hottest hours',
      ],
      userId: alice.id,
      createdAt: daysAgo(3),
    },
    {
      id: uuidv4(),
      imageUrl: 'https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?w=400',
      plantName: 'Carrot',
      species: 'Daucus carota',
      healthScore: 95.0,
      diseases: [],
      recommendations: [
        'Excellent crop health',
        'Continue current care routine',
        'Harvest when roots reach desired size',
      ],
      userId: guru.id,
      createdAt: daysAgo(3),
    },
    {
      id: uuidv4(),
      imageUrl: 'https://images.unsplash.com/photo-1464965911861-746a04b4bca6?w=400',
      plantName: 'Strawberry',
      species: 'Fragaria × ananassa',
      healthScore: 45.0,
      diseases: [
        {
          name: 'Gray Mold (Botrytis)',
          confidence: 0.82,
          severity: 'severe',
        },
        {
          name: 'Powdery Mildew',
          confidence: 0.15,
          severity: 'low',
        },
      ],
      recommendations: [
        'Gray mold detected — remove affected fruit immediately',
        'Improve air circulation with pruning',
        'Apply organic fungicide (copper-based)',
        'Avoid overhead watering',
        'Harvest fruit promptly when ripe',
      ],
      userId: reggie.id,
      createdAt: daysAgo(2),
    },
    {
      id: uuidv4(),
      imageUrl: 'https://images.unsplash.com/photo-1597848212624-a19eb35e2651?w=400',
      plantName: 'Sunflower',
      species: 'Helianthus annuus',
      healthScore: 88.0,
      diseases: [
        {
          name: 'Rust',
          confidence: 0.12,
          severity: 'low',
        },
      ],
      recommendations: [
        'Minor rust spots detected on lower leaves',
        'Remove affected leaves',
        'Ensure good spacing for air circulation',
      ],
      userId: alice.id,
      createdAt: daysAgo(2),
    },
    {
      id: uuidv4(),
      imageUrl: 'https://images.unsplash.com/photo-1589908809146-2f6f5b3f6f6b?w=400',
      plantName: 'Lavender',
      species: 'Lavandula angustifolia',
      healthScore: 35.0,
      diseases: [
        {
          name: 'Root Rot',
          confidence: 0.78,
          severity: 'severe',
        },
        {
          name: 'Fungal Leaf Spot',
          confidence: 0.45,
          severity: 'moderate',
        },
      ],
      recommendations: [
        'Root rot detected — overwatering likely',
        'Reduce watering immediately',
        'Improve soil drainage',
        'Remove severely affected plants',
        'Apply fungicide to remaining plants',
      ],
      userId: alice.id,
      createdAt: daysAgo(1),
    },
    {
      id: uuidv4(),
      imageUrl: 'https://images.unsplash.com/photo-1599946347371-68eb71b16afc?w=400',
      plantName: 'Mint',
      species: 'Mentha spicata',
      healthScore: 90.0,
      diseases: [
        {
          name: 'Rust',
          confidence: 0.05,
          severity: 'none',
        },
      ],
      recommendations: [
        'Plant is thriving!',
        'Consider harvesting to encourage bushier growth',
        'Monitor for signs of spreading beyond container',
      ],
      userId: alice.id,
      createdAt: daysAgo(1),
    },
    {
      id: uuidv4(),
      imageUrl: 'https://images.unsplash.com/photo-1563565375-f3f2db3c3c3c?w=400',
      plantName: 'Bell Pepper',
      species: 'Capsicum annuum',
      healthScore: 55.0,
      diseases: [
        {
          name: 'Blossom End Rot',
          confidence: 0.80,
          severity: 'moderate',
        },
        {
          name: 'Calcium Deficiency',
          confidence: 0.75,
          severity: 'moderate',
        },
      ],
      recommendations: [
        'Blossom end rot detected — calcium deficiency',
        'Add calcium-rich supplement to soil',
        'Maintain even watering — avoid drought stress',
        'Mulch around plants to retain moisture',
        'Remove affected fruit to redirect energy',
      ],
      userId: reggie.id,
      createdAt: hoursAgo(12),
    },
    {
      id: uuidv4(),
      imageUrl: 'https://images.unsplash.com/photo-1579033461380-adb47c3eb938?w=400',
      plantName: 'Zucchini',
      species: 'Cucurbita pepo',
      healthScore: 72.0,
      diseases: [
        {
          name: 'Powdery Mildew',
          confidence: 0.55,
          severity: 'moderate',
        },
      ],
      recommendations: [
        'Powdery mildew detected on leaves',
        'Remove affected leaves',
        'Apply milk spray (1 part milk to 9 parts water)',
        'Improve air circulation',
        'Water at soil level only',
      ],
      userId: reggie.id,
      createdAt: hoursAgo(6),
    },
  ];

  const createdScans = await Promise.all(
    scanData.map((s) => prisma.aiScan.create({ data: s })),
  );
  console.log(`  ✓ Created ${createdScans.length} AI scan records`);

  // =======================================================================
  // 10. INVITES (5)
  // =======================================================================
  console.log('Seeding invites...');

  const inviteData = [
    {
      id: uuidv4(),
      code: 'GROW2026',
      type: 'QR' as const,
      passcode: 'GROW2026',
      maxUses: 10,
      useCount: 3,
      isActive: true,
      expiresAt: daysAgo(-60),
      createdById: admin.id,
      createdAt: daysAgo(30),
    },
    {
      id: uuidv4(),
      code: 'FRIENDSEED',
      type: 'CODE' as const,
      passcode: 'SEED',
      maxUses: 5,
      useCount: 5,
      isActive: false,
      expiresAt: daysAgo(-10),
      createdById: jane.id,
      redeemedById: alice.id,
      createdAt: daysAgo(20),
      redeemedAt: daysAgo(15),
    },
    {
      id: uuidv4(),
      code: 'GARDENPARTY',
      type: 'LINK' as const,
      passcode: null,
      maxUses: 50,
      useCount: 12,
      isActive: false,
      expiresAt: daysAgo(5),
      createdById: admin.id,
      createdAt: daysAgo(30),
    },
    {
      id: uuidv4(),
      code: 'GREENPASS',
      type: 'PASSCODE' as const,
      passcode: 'GREEN2026',
      maxUses: 1,
      useCount: 0,
      isActive: true,
      expiresAt: daysAgo(-90),
      createdById: guru.id,
      createdAt: daysAgo(7),
    },
    {
      id: uuidv4(),
      code: 'SPRINGHARVEST',
      type: 'CODE' as const,
      passcode: 'HARVEST',
      maxUses: 20,
      useCount: 8,
      isActive: false,
      expiresAt: daysAgo(15),
      createdById: alice.id,
      redeemedById: reggie.id,
      createdAt: daysAgo(45),
      redeemedAt: daysAgo(30),
    },
  ];

  const createdInvites = await Promise.all(
    inviteData.map((i) => prisma.invite.create({ data: i })),
  );
  console.log(`  ✓ Created ${createdInvites.length} invites`);

  // =======================================================================
  // 11. NOTIFICATIONS (10+, one per user)
  // =======================================================================
  console.log('Seeding notifications...');

  const notificationData = [
    {
      id: uuidv4(),
      type: 'welcome',
      title: 'Welcome to GardenVerse!',
      body: 'Your garden journey begins now. Start by creating your first garden plot.',
      data: { action: '/garden/new' },
      isRead: true,
      userId: admin.id,
      createdAt: daysAgo(60),
    },
    {
      id: uuidv4(),
      type: 'harvest_ready',
      title: 'Harvest Ready!',
      body: 'Your Cherry Tomatoes are ready to harvest! They have reached full maturity.',
      data: { cropId: _adminTomato.id, action: '/garden/crops' },
      isRead: false,
      userId: admin.id,
      createdAt: hoursAgo(3),
    },
    {
      id: uuidv4(),
      type: 'weather_alert',
      title: 'Heatwave Warning',
      body: 'Extreme heat expected in your area. Consider adding shade to your garden.',
      data: { region: 'US-CA', temperature: 38 },
      isRead: true,
      userId: jane.id,
      createdAt: daysAgo(2),
    },
    {
      id: uuidv4(),
      type: 'marketplace',
      title: 'Item Sold!',
      body: 'Your Organic Carrots listing has been sold. Check your transactions.',
      data: {
        listingId: createdListings[2].id,
        action: '/marketplace/sales',
      },
      isRead: false,
      userId: guru.id,
      createdAt: hoursAgo(12),
    },
    {
      id: uuidv4(),
      type: 'community',
      title: 'New Message in Organic Farmers Collective',
      body: 'Guru Garden posted: "Has anyone tried companion planting with marigolds?"',
      data: { groupId: organicGroup.id, action: '/community/groups' },
      isRead: true,
      userId: alice.id,
      createdAt: daysAgo(12),
    },
    {
      id: uuidv4(),
      type: 'streak',
      title: '10-Day Streak!',
      body: 'Amazing! You\'ve logged in for 10 consecutive days. Keep it up!',
      data: { streak: 10, action: '/profile' },
      isRead: true,
      userId: thumb.id,
      createdAt: daysAgo(3),
    },
    {
      id: uuidv4(),
      type: 'achievement',
      title: 'Master Gardener Achievement Unlocked!',
      body: 'Congratulations! You\'ve reached level 42 and unlocked the Master Gardener badge.',
      data: { badge: 'master_gardener', action: '/profile/achievements' },
      isRead: true,
      userId: guru.id,
      createdAt: daysAgo(5),
    },
    {
      id: uuidv4(),
      type: 'plant_care',
      title: 'Water Reminder',
      body: 'Your Roma Tomato plant needs watering! Soil moisture is critically low.',
      data: { cropId: reggieTomato.id, action: '/garden/crops' },
      isRead: false,
      userId: reggie.id,
      createdAt: hoursAgo(2),
    },
    {
      id: uuidv4(),
      type: 'ai_scan',
      title: 'AI Scan Complete',
      body: 'Your Bell Pepper scan is ready. Potential issue detected: Blossom End Rot.',
      data: { scanId: createdScans[8].id, action: '/ai-scanner/results' },
      isRead: false,
      userId: reggie.id,
      createdAt: hoursAgo(12),
    },
    {
      id: uuidv4(),
      type: 'invite',
      title: 'You\'ve Been Invited!',
      body: 'Admin has invited you to join the Seed Swap Society — a private seed trading group.',
      data: { inviteCode: 'GROW2026', action: '/invites' },
      isRead: true,
      userId: warrior.id,
      createdAt: daysAgo(7),
    },
    {
      id: uuidv4(),
      type: 'welcome',
      title: 'Welcome to GardenVerse!',
      body: 'Your garden journey begins now. Start by exploring community groups.',
      data: { action: '/community' },
      isRead: true,
      userId: whisper.id,
      createdAt: daysAgo(14),
    },
    {
      id: uuidv4(),
      type: 'system',
      title: 'Account Suspension Notice',
      body: 'Your account has been temporarily suspended due to inactivity. Log in to reactivate.',
      data: { action: '/auth/login' },
      isRead: false,
      userId: lazyUser.id,
      createdAt: daysAgo(30),
    },
  ];

  const createdNotifications = await Promise.all(
    notificationData.map((n) => prisma.notification.create({ data: n })),
  );
  console.log(`  ✓ Created ${createdNotifications.length} notifications`);

  // =======================================================================
  // 12. INVENTORY ITEMS (for users with gardens)
  // =======================================================================
  console.log('Seeding inventory items...');

  const inventoryItems = [
    // Admin's inventory
    {
      id: uuidv4(),
      itemType: 'tool',
      itemId: uuidv4(),
      name: 'Golden Trowel',
      quantity: 1,
      rarity: 'LEGENDARY',
      userId: admin.id,
    },
    {
      id: uuidv4(),
      itemType: 'seed',
      itemId: uuidv4(),
      name: 'Rare Blue Tomato Seeds',
      quantity: 3,
      rarity: 'EPIC',
      userId: admin.id,
    },
    {
      id: uuidv4(),
      itemType: 'fertilizer',
      itemId: uuidv4(),
      name: 'Premium Organic Compost',
      quantity: 10,
      rarity: 'RARE',
      userId: admin.id,
    },
    // Jane's inventory
    {
      id: uuidv4(),
      itemType: 'tool',
      itemId: uuidv4(),
      name: 'Bamboo Garden Fork',
      quantity: 1,
      rarity: 'RARE',
      userId: jane.id,
    },
    {
      id: uuidv4(),
      itemType: 'decor',
      itemId: uuidv4(),
      name: 'Stone Bird Bath',
      quantity: 1,
      rarity: 'EPIC',
      userId: jane.id,
    },
    // Alice's inventory
    {
      id: uuidv4(),
      itemType: 'seed',
      itemId: uuidv4(),
      name: 'Purple Basil Seeds',
      quantity: 5,
      rarity: 'UNCOMMON',
      userId: alice.id,
    },
    {
      id: uuidv4(),
      itemType: 'potion',
      itemId: uuidv4(),
      name: 'Growth Accelerator',
      quantity: 2,
      rarity: 'RARE',
      userId: alice.id,
    },
    // Reggie's inventory
    {
      id: uuidv4(),
      itemType: 'tool',
      itemId: uuidv4(),
      name: 'Copper Watering Can',
      quantity: 1,
      rarity: 'COMMON',
      userId: reggie.id,
    },
    {
      id: uuidv4(),
      itemType: 'decor',
      itemId: uuidv4(),
      name: 'Garden Gnome',
      quantity: 1,
      rarity: 'COMMON',
      userId: reggie.id,
    },
    // Guru's inventory
    {
      id: uuidv4(),
      itemType: 'tool',
      itemId: uuidv4(),
      name: 'Master Pruner Shears',
      quantity: 1,
      rarity: 'LEGENDARY',
      userId: guru.id,
    },
    {
      id: uuidv4(),
      itemType: 'seed',
      itemId: uuidv4(),
      name: 'Heirloom Tomato Collection',
      quantity: 6,
      rarity: 'EPIC',
      userId: guru.id,
    },
    {
      id: uuidv4(),
      itemType: 'fertilizer',
      itemId: uuidv4(),
      name: 'Worm Casting Tea',
      quantity: 15,
      rarity: 'RARE',
      userId: guru.id,
    },
  ];

  const createdInventory = await Promise.all(
    inventoryItems.map((inv) => prisma.inventory.create({ data: inv })),
  );
  console.log(`  ✓ Created ${createdInventory.length} inventory items`);

  // =======================================================================
  // 13. FEATURE FLAGS
  // =======================================================================
  console.log('Seeding feature flags...');

  const featureFlags = [
    {
      id: uuidv4(),
      name: 'ai_scanner_v2',
      enabled: true,
      description: 'Enable the new AI plant scanner with disease detection v2 model',
    },
    {
      id: uuidv4(),
      name: 'marketplace_escrow',
      enabled: true,
      description: 'Enable escrow-protected marketplace transactions',
    },
    {
      id: uuidv4(),
      name: 'community_chat_encryption',
      enabled: true,
      description: 'Enable end-to-end encryption for community chat messages',
    },
    {
      id: uuidv4(),
      name: 'iot_integration',
      enabled: true,
      description: 'Enable IoT sensor device integration',
    },
    {
      id: uuidv4(),
      name: 'premium_tier_3',
      enabled: false,
      description: 'Enable premium tier 3 subscription features',
    },
    {
      id: uuidv4(),
      name: 'gamification_v2',
      enabled: true,
      description: 'Enable enhanced gamification with new achievement badges',
    },
  ];

  const createdFlags = await Promise.all(
    featureFlags.map((f) => prisma.featureFlag.create({ data: f })),
  );
  console.log(`  ✓ Created ${createdFlags.length} feature flags`);

  // =======================================================================
  // 14. ACHIEVEMENTS
  // =======================================================================
  console.log('Seeding achievements...');

  const achievements = [
    { key: 'species_collector', name: 'Budding Collector', description: 'Discover your first plant species', icon: '🔍', category: 'GARDENING', maxProgress: 1, xpReward: 50, tokenReward: 20 },
    { key: 'collector_5', name: 'Species Spotter', description: 'Discover 5 unique plant species', icon: '🔬', category: 'GARDENING', maxProgress: 5, xpReward: 100, tokenReward: 50 },
    { key: 'collector_15', name: 'Species Hunter', description: 'Discover 15 unique plant species', icon: '🔎', category: 'GARDENING', maxProgress: 15, xpReward: 500, tokenReward: 200 },
    { key: 'perfectionist', name: 'Perfectionist', description: 'Perfect any species (reach max mastery)', icon: '💎', category: 'MILESTONE', maxProgress: 1, xpReward: 500, tokenReward: 250 },
    { key: 'care_taker', name: 'Care Taker', description: 'Perform 50 care actions on crops', icon: '💧', category: 'GARDENING', maxProgress: 50, xpReward: 200, tokenReward: 100 },
    { key: 'streak_master', name: 'Streak Master', description: 'Maintain a 7-day care streak on any crop', icon: '🔥', category: 'GARDENING', maxProgress: 7, xpReward: 300, tokenReward: 150 },
    { key: 'hybrid_pioneer', name: 'Hybrid Pioneer', description: 'Create your first hybrid plant', icon: '🧬', category: 'GARDENING', maxProgress: 1, xpReward: 200, tokenReward: 100 },
    { key: 'mastery_3', name: 'Species Apprentice', description: 'Reach mastery level 3 on any species', icon: '⭐', category: 'MILESTONE', maxProgress: 3, xpReward: 150, tokenReward: 75 },
    { key: 'mastery_7', name: 'Master Botanist', description: 'Reach mastery level 7 on any species', icon: '👑', category: 'MILESTONE', maxProgress: 7, xpReward: 1000, tokenReward: 500 },
    { key: 'harvest_100', name: 'Harvest Legend', description: 'Harvest 100 crops total', icon: '🏆', category: 'GARDENING', maxProgress: 100, xpReward: 2000, tokenReward: 1000 },
  ];

  const createdAchievements = await prisma.achievement.createMany({
    data: achievements,
    skipDuplicates: true,
  });
  console.log(`  ✓ Created ${achievements.length} achievements`);

  // =======================================================================
  // 15. SHOP ITEMS
  // =======================================================================
  console.log('Seeding shop items...');

  const shopItems = [
    { name: 'Tomato Seeds', description: 'Plant delicious tomatoes', category: 'SEED', price: 50, currency: 'GREEN_CREDITS', icon: '🍅', levelRequired: 1, isLimited: false },
    { name: 'Carrot Seeds', description: 'Crunchy carrots ready in 3 days', category: 'SEED', price: 40, currency: 'GREEN_CREDITS', icon: '🥕', levelRequired: 1, isLimited: false },
    { name: 'Sunflower Seeds', description: 'Brighten up your garden', category: 'SEED', price: 60, currency: 'GREEN_CREDITS', icon: '🌻', levelRequired: 2, isLimited: false },
    { name: 'Strawberry Seeds', description: 'Sweet strawberries', category: 'SEED', price: 80, currency: 'GREEN_CREDITS', icon: '🍓', levelRequired: 3, isLimited: false },
    { name: 'Golden Fertilizer', description: 'Boost crop growth by 50%', category: 'FERTILIZER', price: 100, currency: 'GREEN_CREDITS', icon: '✨', levelRequired: 2, isLimited: false },
    { name: 'Premium Soil', description: 'Improve soil quality instantly', category: 'TOOL', price: 200, currency: 'GREEN_CREDITS', icon: '🪴', levelRequired: 3, isLimited: false },
    { name: 'Watering Can Pro', description: 'Water 3 crops at once', category: 'TOOL', price: 150, currency: 'GREEN_CREDITS', icon: '💦', levelRequired: 4, isLimited: false },
    { name: 'Garden Gnome', description: 'Decorative gnome for your garden', category: 'DECORATION', price: 300, currency: 'GREEN_CREDITS', icon: '🧑‍🌾', levelRequired: 5, isLimited: true, stock: 50 },
    { name: 'Rare Seed Pack', description: 'Contains 3 rare plant seeds', category: 'SEED', price: 500, currency: 'GREEN_CREDITS', icon: '🎁', levelRequired: 6, isLimited: true, stock: 20 },
    { name: 'Greenhouse Kit', description: 'Protect crops from bad weather', category: 'STRUCTURE', price: 1000, currency: 'GREEN_CREDITS', icon: '🏠', levelRequired: 8, isLimited: true, stock: 10 },
  ];

  const createdShopItems = await prisma.shopItem.createMany({
    data: shopItems,
    skipDuplicates: true,
  });
  console.log(`  ✓ Created ${shopItems.length} shop items`);

  // =======================================================================
  // SUMMARY
  // =======================================================================
  console.log('\n═══════════════════════════════════════');
  console.log('  ✅ Seed completed successfully!');
  console.log('═══════════════════════════════════════');
  console.log('');
  console.log('  Summary:');
  console.log(`    Users:            ${createdUsers.length}`);
  console.log(`    Plant Species:    ${createdSpecies.length}`);
  console.log(`    Gardens:          ${createdGardens.length}`);
  console.log(`    Crops:            ${createdCrops.length}`);
  console.log(`    Marketplace:      ${createdListings.length}`);
  console.log(`    Groups:           ${createdGroups.length}`);
  console.log(`    Group Members:    ${groupMemberData.length}`);
  console.log(`    Messages:         ${createdMessages.length}`);
  console.log(`    Weather Records:  ${createdWeatherRecords.length}`);
  console.log(`    AI Scans:         ${createdScans.length}`);
  console.log(`    Invites:          ${createdInvites.length}`);
  console.log(`    Notifications:    ${createdNotifications.length}`);
  console.log(`    Inventory Items:  ${createdInventory.length}`);
  console.log(`    Feature Flags:    ${createdFlags.length}`);
  console.log(`    Achievements:     ${achievements.length}`);
  console.log(`    Shop Items:       ${shopItems.length}`);
  console.log('');
  console.log('  Default login for all users:');
  console.log('    Email:    any user email');
  console.log('    Password: Password123');
  console.log('');
  console.log('  Admin login:');
  console.log('    Email:    admin@gardenverse.vercel.app');
  console.log('    Password: Password123');
  console.log('');
}

// ---------------------------------------------------------------------------
// Execute
// ---------------------------------------------------------------------------

main()
  .catch((e) => {
    console.error('❌ Seed failed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
