const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

const plants = [
  {
    commonName: 'Tomato',
    scientificName: 'Solanum lycopersicum',
    family: 'Solanaceae',
    genus: 'Solanum',
    imageUrl: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=400',
    description: 'Popular garden fruit, rich in lycopene. Warm-season crop.',
    growingDays: 70,
    difficulty: 'EASY',
    waterNeeds: 'MODERATE',
    sunlightNeeds: 'FULL_SUN',
    seasons: ['spring', 'summer'],
    edible: true,
    tags: ['fruit', 'warm-season', 'popular'],
  },
  {
    commonName: 'Basil',
    scientificName: 'Ocimum basilicum',
    family: 'Lamiaceae',
    genus: 'Ocimum',
    imageUrl: 'https://images.unsplash.com/photo-1618375569909-ae4f3d10d56e?w=400',
    description: 'Aromatic herb essential for Italian cuisine. Companion plant for tomatoes.',
    growingDays: 60,
    difficulty: 'EASY',
    waterNeeds: 'MODERATE',
    sunlightNeeds: 'FULL_SUN',
    seasons: ['spring', 'summer'],
    edible: true,
    tags: ['herb', 'culinary', 'companion'],
  },
  {
    commonName: 'Lettuce',
    scientificName: 'Lactuca sativa',
    family: 'Asteraceae',
    genus: 'Lactuca',
    imageUrl: 'https://images.unsplash.com/photo-1622206151226-18ca2c9ab4a1?w=400',
    description: 'Cool-season leafy green. Quick growing and perfect for salads.',
    growingDays: 45,
    difficulty: 'EASY',
    waterNeeds: 'HIGH',
    sunlightNeeds: 'PARTIAL_SHADE',
    seasons: ['spring', 'autumn'],
    edible: true,
    tags: ['leafy-green', 'cool-season', 'salad'],
  },
  {
    commonName: 'Carrot',
    scientificName: 'Daucus carota',
    family: 'Apiaceae',
    genus: 'Daucus',
    imageUrl: 'https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?w=400',
    description: 'Root vegetable rich in beta-carotene. Requires deep loose soil.',
    growingDays: 65,
    difficulty: 'MEDIUM',
    waterNeeds: 'MODERATE',
    sunlightNeeds: 'FULL_SUN',
    seasons: ['spring', 'autumn'],
    edible: true,
    tags: ['root', 'cool-season', 'vitamin'],
  },
  {
    commonName: 'Strawberry',
    scientificName: 'Fragaria × ananassa',
    family: 'Rosaceae',
    genus: 'Fragaria',
    imageUrl: 'https://images.unsplash.com/photo-1464965911861-746a04b4bca6?w=400',
    description: 'Sweet perennial fruit. Grows well in containers and garden beds.',
    growingDays: 90,
    difficulty: 'MEDIUM',
    waterNeeds: 'MODERATE',
    sunlightNeeds: 'FULL_SUN',
    seasons: ['spring', 'summer'],
    edible: true,
    tags: ['fruit', 'perennial', 'container-friendly'],
  },
  {
    commonName: 'Mint',
    scientificName: 'Mentha spicata',
    family: 'Lamiaceae',
    genus: 'Mentha',
    imageUrl: 'https://images.unsplash.com/photo-1626455777416-02a28b4a7f38?w=400',
    description: 'Vigorous aromatic herb. Best grown in containers to control spread.',
    growingDays: 50,
    difficulty: 'EASY',
    waterNeeds: 'HIGH',
    sunlightNeeds: 'PARTIAL_SHADE',
    seasons: ['spring', 'summer', 'autumn'],
    edible: true,
    medicinal: true,
    tags: ['herb', 'culinary', 'medicinal'],
  },
  {
    commonName: 'Sunflower',
    scientificName: 'Helianthus annuus',
    family: 'Asteraceae',
    genus: 'Helianthus',
    imageUrl: 'https://images.unsplash.com/photo-1597848212624-a19eb35e2651?w=400',
    description: 'Tall annual with bright yellow blooms. Seeds are edible and attract pollinators.',
    growingDays: 80,
    difficulty: 'EASY',
    waterNeeds: 'LOW',
    sunlightNeeds: 'FULL_SUN',
    seasons: ['spring', 'summer'],
    edible: true,
    attractsPollinators: true,
    tags: ['flower', 'pollinator-friendly', 'edible-seeds'],
  },
  {
    commonName: 'Bell Pepper',
    scientificName: 'Capsicum annuum',
    family: 'Solanaceae',
    genus: 'Capsicum',
    imageUrl: 'https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?w=400',
    description: 'Colorful sweet pepper. Warm-season crop rich in vitamin C.',
    growingDays: 75,
    difficulty: 'MEDIUM',
    waterNeeds: 'MODERATE',
    sunlightNeeds: 'FULL_SUN',
    seasons: ['spring', 'summer'],
    edible: true,
    tags: ['vegetable', 'warm-season', 'colorful'],
  },
  {
    commonName: 'Cucumber',
    scientificName: 'Cucumis sativus',
    family: 'Cucurbitaceae',
    genus: 'Cucumis',
    imageUrl: 'https://images.unsplash.com/photo-1604977042946-1eecc30f269e?w=400',
    description: 'Refreshing vine crop. Fast-growing and productive.',
    growingDays: 55,
    difficulty: 'EASY',
    waterNeeds: 'HIGH',
    sunlightNeeds: 'FULL_SUN',
    seasons: ['spring', 'summer'],
    edible: true,
    tags: ['vegetable', 'vine', 'fast-growing'],
  },
  {
    commonName: 'Lavender',
    scientificName: 'Lavandula angustifolia',
    family: 'Lamiaceae',
    genus: 'Lavandula',
    imageUrl: 'https://images.unsplash.com/photo-1589109505482-9c1f2e9e99c6?w=400',
    description: 'Fragrant perennial herb. Drought-tolerant and attracts pollinators.',
    growingDays: 100,
    difficulty: 'MEDIUM',
    waterNeeds: 'LOW',
    sunlightNeeds: 'FULL_SUN',
    seasons: ['spring', 'summer'],
    medicinal: true,
    attractsPollinators: true,
    tags: ['herb', 'perennial', 'drought-tolerant', 'aromatic'],
  },
];

async function main() {
  console.log('Seeding PlantSpecies...');
  let count = 0;
  for (const plant of plants) {
    await prisma.plantSpecies.upsert({
      where: { scientificName: plant.scientificName },
      update: plant,
      create: plant,
    });
    count++;
    console.log(`  ✓ ${plant.commonName} (${plant.scientificName})`);
  }
  console.log(`\nDone! ${count} plant species seeded.`);
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
